### ISSUE TITLE
Module parse failed - can't run

### ISSUE THREAD

**Issue by JZiebikiewicz** [foxhound87/mobx-ajv-form#1]
Hello,
I'm trying to run MobX AJV Form, but get these errors:

```
ERROR in ./~/ajv/lib/refs/json-schema-draft-04.json
Module parse failed: C:\proj\node_modules\ajv\lib\refs\json-schema-draft-04.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|     "id": "http://json-schema.org/draft-04/schema#",
|     "$schema": "http://json-schema.org/draft-04/schema#",
|     "description": "Core schema meta-schema",
 @ ./~/ajv/lib/ajv.js 352:23-66

ERROR in ./~/ajv/lib/refs/json-schema-v5.json
Module parse failed: C:\proj\node_modules\ajv\lib\refs\json-schema-v5.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|     "id": "https://raw.githubusercontent.com/epoberezkin/ajv/master/lib/refs/json-schema-v5.json#",
|     "$schema": "http://json-schema.org/draft-04/schema#",
|     "description": "Core schema meta-schema (v5 proposals)",
 @ ./~/ajv/lib/v5.js 20:21-58
```

And also warnings `Cannot resolve module`:
- regenerator
- nodent
- js-beautify

**Comment by foxhound87** [comment]
You have to add the json-loader to your webpack config like this:
https://github.com/foxhound87/mobx-ajv-form/blob/master/webpack.config.babel.js#L34-L35

The warnings are not a problem.

**Comment by JZiebikiewicz** [comment]
I had json-loader. Webpack still returns the same error. 

Even if you download package from http://www.webpackbin.com/E1khFEBrZ it will not be working so there is probably error in AJV itself.

```
ERROR in ./~/ajv/lib/refs/json-schema-draft-04.json
Module parse failed: C:\RWportal\node_modules\ajv\lib\refs\json-schema-draft-04.json Unexpected token (2:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:8)
```

**Comment by foxhound87** [comment]
The json-loader was missing on the webpackbin demo too. I just added it and then worked.
So it's definitely a json-loader issue. What node version are you using?

**Comment by foxhound87** [comment]
If you still need help let me know your webpack config. For now, I consider this issue to be closed.

**Comment by patrykkopycinski** [comment]
@JZiebikiewicz take a look: https://github.com/epoberezkin/ajv/issues/117

**Comment by JZiebikiewicz** [comment]
@patrykkopycinski, thanks, `new webpack.IgnorePlugin(/regenerator|nodent|js\-beautify/, /ajv/)` suppressed warnings.

@foxhound87, I had json-loader before. Still not working. My node version is 6.2.2 and my webpack config is:

```
var path = require('path');
var webpack = require('webpack');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  devtool: 'cheap-module-eval-source-map',
  entry: [
    'webpack-hot-middleware/client',
    './client/main'
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/dist/'
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.IgnorePlugin(/regenerator|nodent|js\-beautify/, /ajv/),
    new ExtractTextPlugin('style.css', { allChunks: true }),
    new webpack.NoErrorsPlugin()
  ],
  module: {
    loaders: [
      {
        test: /\.js?$/,
        loaders: [ 'babel' ],
        include: path.join(__dirname, 'client')
      },
      {
        test: /\.(jpg|png)$/,
        loader: 'url?limit=81920',
        include: path.join(__dirname, 'client')
      },
      {
        test: /\.json$/,
        loader: 'json-loader',
        include: path.join(__dirname, 'client')
      },
    ],
  }
};
```

As I mentioned before, when I download your example project from webpackbin, it doesn't work. Here is the error. I downloaded it and installed again few minutes ago.
![image](https://cloud.githubusercontent.com/assets/16606706/16873284/7549e9ec-4a92-11e6-834c-713170b1d090.png)

**Comment by foxhound87** [comment]
Remove the include for the json loader, otherwise cannot load json from node_modules

**Comment by JZiebikiewicz** [comment]
Hah! Now work as it should! Stupid mistake. 

Thanks, @foxhound87. :)

**Comment by foxhound87** [comment]
@JZiebikiewicz great!
