### ISSUE TITLE
Form is mutating state outside form class

### ISSUE THREAD

**Issue by gvelo** [foxhound87/mobx-ajv-form#102]
when init a form like:

```
const fields = {...} 
new Form({ options, fields, ... });

```

the `field` parameter is mutated. Form should not mutate state outside the form class. This allow to reuse form definition in differents forms instances.

**Comment by foxhound87** [comment]
In my case it doesn't mutate. Maybe I don't get your issue.
I'm able to pass the same form structure (same object) in different forms without problem.

**Comment by gvelo** [comment]
Sorry, I was using 1.12.0, This behaviour is not reproducible when I update to  1.13.10.
