### ISSUE TITLE
Error when trying to use .onAdd

### ISSUE THREAD

**Issue by elazer** [foxhound87/mobx-ajv-form#109]
Hi, I tried adding an 'Add Members' button on your demo form.

```
<button type="button" onClick={e => form.$('members').onAdd(e)}>
  <i className="fa fa-plus-circle" data-tip="Add Members" />
</button>
```

I get the following error:
**Uncaught Error: The selected field is not defined (firstname)**

**Comment by foxhound87** [comment]
This method is not yet supported for the nested fields. You can use it only for flat arrays for now.

**Comment by itaylorweb** [comment]
@foxhound87  Any suggested solutions for this problem.  I think this is the last bit I need for my project. :)

**Comment by foxhound87** [comment]
It is a feature that I want to release, but I have not had time to think how to Implement it yet.

**Comment by itaylorweb** [comment]
As a workaround is below a reasonable approach?

``` javascript
// object that matches current field in form
const clientObj = {
  somefield: '',
  someotherfield: {
    something: ''
  }
}
```

``` javascript
class MyForm extends MobxReactForm {

  @action addClient = (form) => {
    // get current form values
    var current = form.values();
    // push new item to field array
    current.clients.push(clientObj);
    // re-init form with values
    form.update(current);
  };

  onSuccess(form) {
    alert('Form is valid! Send the request here.');
    // get field values
    console.log('Form Values!', form.values());
  }

  onError(form) {
    // get all form errors
    console.log('All form errors', form.errors());
    // invalidate the form with a custom error message
    form.invalidate('This is a generic error message!');
  }
}
```

**Comment by foxhound87** [comment]
I recently implemented `pathToFieldsTree` method, which we can use to create an object tree starting from a string path: https://github.com/foxhound87/mobx-react-form/blob/fb0eb6a535bd6f52c5c355409ee3cc02b9a1c61e/src/FieldParser.js#L16 

I think we can start from here to create the object with empty fields for each of the path struct we need to add.

**Comment by itaylorweb** [comment]
@foxhound87 This is great thanks.  Works perfectly.

**Comment by vkrol** [comment]
@foxhound87 pathToFi**le**dsTree -> pathToFi**el**dsTree? :)

**Comment by vkrol** [comment]
@foxhound87 https://github.com/foxhound87/mobx-react-form/blob/abc06aad104a49c1080b04fa5af81fc9c4f4e7c0/src/FieldHelpers.js#L150

init fi**le**d into -> init fi**el**d into
