### ISSUE TITLE
Behaviour of .sync and .update

### ISSUE THREAD

**Issue by leesiongchan** [foxhound87/mobx-ajv-form#110]
It seems `.sync` is only setting the value right immediate of what passed into it;
While `.update` seems to have much complete checking to the nested fields and update accordingly. 

What is the use case for both `.sync` and `.update`?

**Comment by foxhound87** [comment]
`.sync(e)` is an event handler, it gets in input the `Proxy` object and is supposed to be used on input `onChange` property. It updates only the value of the field on which is used. 
It is also an alias of `.onChange(e)` and `onToggle(e)`. [[more info here]](https://foxhound87.github.io/mobx-react-form/docs/events/events-handlers.html)

`.update()` is intended to be used for updating the values of multiple fields and nested fields at once.

**Comment by foxhound87** [comment]
Anyway if you want to set a field value use `.set('value', val)`.
(it sets the `value` property on the field class). 

But it doesn't create nested fields if `val` is `array`, in that case use `.update()` instead.

**Comment by leesiongchan** [comment]
In my case, some of my components are returning not-so-straight-forward value (eg. Object, Array-Object, Array etc). So I can't use `.sync` for these components, I have to check for the value type and use different kind of methods to update my fields, just curious would that be wise to make both behave the same so we could use `.sync` across to all kind of components?

**Comment by foxhound87** [comment]
But not all complex data should be treated as nested fields, so I don't know if we can use .update() for .sync().  Maybe we can make a .sync(e, true) for update nested fields.

Anyway I suggest you to duplicate the demo branch into another branch like `demo-next`. So you can show me which kind of components and data structure you are using, and I will test these cases.

**Comment by leesiongchan** [comment]
@foxhound87 Ok, thank you for your prompt reply.
