### ISSUE TITLE
Behaviour of .clear and .reset

### ISSUE THREAD

**Issue by elazer** [foxhound87/mobx-ajv-form#111]
```
const fields = [
  'places[]',
];

const values = {
  places: [
    'NY',
    'NJ',
  ],
};

form = new MobxForm({ fields, values }); 
// OR
form = new MobxForm({ fields });
form.update(values);

form.$('places').clear(); // no change, form.values() returns { places: [ 'NY', 'NJ' ] }
form.$('places').clear(true); // form.values() returns { places: [ '', '' ] }
```

**Comment by foxhound87** [comment]
This is correct, the array values are treated as individual nested fields of the `places` "field container". Using the `boolean` for the `.clear()` method allows to clear nested values too.

 If you use the `onClear(e)` event handler, it calls `.clear(true)` by default.  [[more info here]](https://foxhound87.github.io/mobx-react-form/docs/events/events-handlers.html)

But now you make me realize that maybe is the case to set this behavior as default for the clear method. 

What do you think? 

Thanks

**Comment by elazer** [comment]
Yeah, when using .clear() for a field, I would usually assume that even the nested values would be cleared too.
It would good to make it the default behaviour, unless there is a use case where for some reason we want the nested values to be retained.

And I think it should return an empty array, instead of the empty strings in place of the cleared elements.

**Comment by benjamingeorge** [comment]
I'm on version 1.33 and clear(), clear(true), or reset() still does not set the array field to [] or back to its default value (null).  Only way i can accomplish it is `form.update({ customerList: [] })`
