### ISSUE TITLE
Defining and array field?

### ISSUE THREAD

**Issue by itaylorweb** [foxhound87/mobx-ajv-form#116]
I am trying to define a fairly complex nested field set.  Below is an example.  
How do I define an array in the field definition?

``` javascript
const fields = [{
  name: 'someField',
  label: 'Some Field',
  rules: 'required|string'
}, {
  name: 'clients',  //  This need to be an array of clients.
  label: 'Clients',
  fields: [{
    name: 'title',
    label: 'Title',
    rules: 'required|string'
  }, {
    name: 'firstname',
    label: 'Firstname',
    rules: 'required|string'
  }, {
    name: 'surname',
    label: 'Surname',
    rules: 'required|string'
  }],
}];
```

example JSON:

``` javascript
{
  someField: 'value',
  clients: [{
    title: 'Mr', 
    firstname: 'John', 
    surname: 'Smith',
  }, {
    title: 'Mrs', 
    firstname: 'Susan', 
    surname: 'Smith',
  }],
}
```

**Comment by foxhound87** [comment]
In your example you are defining fields with [Unified Properties](https://foxhound87.github.io/mobx-react-form/docs/defining-nested-fields/unified-properties.html) which is not so straight for handling collections.

I suggest using [Separated Properties](https://foxhound87.github.io/mobx-react-form/docs/defining-nested-fields/separated-properties.html) with an initial fields `structure`:

``` javascript
const fields = [
  'someField',
  'clients',
  'clients[].title',
  'clients[].firstname',
  'clients[].surname',
];

const rules = {
  'someField':            'required|string',
  'clients[].title':      'required|string',
  'clients[].firstname':  'required|string',
  'clients[].surname':    'required|string',
};

const labels = {
  'someField':            'Some Field',
  'clients[].title':      'Title',
  'clients[].firstname':  'Firstname',
  'clients[].surname':    'Surname',
};

const values = {
  someField: 'value',
  clients: [{ 
    title: 'Mr', 
    firstname: 'John', 
    surname: 'Smith'
  }, {
    title: 'Mrs', 
    firstname: 'Susan', 
    surname: 'Smith'
  }]
};

new Form({ plugins, fields, rules, labels, values });
```

or you can choose to init/update the fields values after the initialization:

``` javascript
const form = new Form({ plugins, fields, rules, labels });

// INIT FIELDS
form.init(values);
// OR UPDATE
form.update(values);
```

I hope this can help you. Let me know.

**Comment by itaylorweb** [comment]
I thought that might be the case.  Thanks for confirming. 👍

**Comment by foxhound87** [comment]
I close this question, It can be found here:

https://foxhound87.github.io/mobx-react-form/docs/faq.html

**Comment by simon998yang** [comment]
Even it's not straight-forward, is there a way to use Unified Properties to define an 'array' field? I'd like to use unified properties as i can keep all the info regarding one field in one place.

**Comment by Dakkers** [comment]
@foxhound87 is it possible? (regarding question above)
