### ISSUE TITLE
how to disable strict mode

### ISSUE THREAD

**Issue by liveresume** [foxhound87/mobx-ajv-form#117]
What is the recommended way to disable mobx's strict mode?

Seems like it is decided for us in src/index.js.  Why not allow dev's to disable?

**Comment by foxhound87** [comment]
I think is better to have the strict mode enabled for a better control over the app state.

But I can provide a method to disable it.

**Comment by foxhound87** [comment]
Now the mobx strict mode is disabled by default, 
it is turned on only for the test command.

**Comment by liveresume** [comment]
@foxhound87 I think that is the better way to go. Thanks
