### ISSUE TITLE
Field has error but is still valid

### ISSUE THREAD

**Issue by DominikGuzei** [foxhound87/mobx-ajv-form#118]
Hey there, thanks for this great library! Everything worked perfectly so far, except now I have a very strange behavior for a text field that has errors (they are even shown in the form correctly) but still validates to `true` and the `onSuccess` handler is called on the form.

Here is a screenshot of the console.log output of the `form.get` call for this field:
<img width="284" alt="screenshot 2016-10-28 um 13 56 33" src="https://cloud.githubusercontent.com/assets/172414/19805723/63169bd6-9d16-11e6-9caf-d2ba665dc7d2.png">

I guess this state (errors are set & displayed but field `hasError` is `false`)  should not be possible?

It worked fine on a form where we used [material-ui](http://www.material-ui.com/#/) and now im trying it with [react-toolbox](http://react-toolbox.com/#/) although i don't think that is the problem?

**Comment by foxhound87** [comment]
Please, can you show me your validation setup?

**Comment by DominikGuzei** [comment]
Here is the from and validation setup:

``` javascript
const isValidWalletName = ({ field }) => {
  const isValid = field.value.length >= 3;
  return [isValid, messages.invalidWalletName]; // this is defined elsewhere (not important)
};

const fields = {
  walletName: {
    value: '',
    validate: [isValidWalletName]
  },
};

const options = {
  validateOnChange: false
};

class WalletCreateForm extends MobxReactForm {

  onSuccess(form) {
    // always called although walletName is invalid
  }

  onError(form) {
    // get all form errors
    console.log('All form errors', form.errors(), this); // eslint-disable-line
  }
}

export default new WalletCreateForm({ options, fields });
```

Here is the `render` method of the validated component:

``` javascript
actions = [
    { label: 'Create personal wallet', onClick: this.props.validator.onSubmit }
]
render() {
    const { intl } = this.context;
    const { validator } = this.props;
    const walletName = validator.$('walletName');
    return (
      <div className={styles.component}>

        <Dialog
          title="Create Wallet"
          actions={this.actions}
          active
        >

          <Input
            type="text"
            label={intl.formatMessage(messages.walletName)}
            hint="e.g: Shopping Wallet"
            value={walletName.value}
            error={walletName.error ? intl.formatMessage(walletName.error) : null}
            onChange={walletName.onChange}
            onFocus={walletName.onFocus}
            onBlur={walletName.onBlur}
          />

        </Dialog>
      </div>
    );
```

Sorry, i had to simplify this example to not show any sensitive code but this is the setup for `walletName` field (which has the problem)

**Comment by foxhound87** [comment]
I tested your setup and I don't find any issue, I tried react-toolbox too.

Make sure you are using mobx `observer` on your components.

**Comment by DominikGuzei** [comment]
That's the weird thing … everything looks correct (i have another form where it works perfectly) but somehow it doesn't in this case. It's probably some weird side-effect that's not obvious from these code snippets.

**Comment by DominikGuzei** [comment]
@foxhound87 we haven't found the issue yet but are one step further: we are using [react-intl](https://github.com/yahoo/react-intl) on the same form and when we remove it everything works fine. Do you have any experience with it / know potential problems there?

**Comment by foxhound87** [comment]
I don't know how react-intl work, I never used it. 
You can try to use stateless components if you are using classes with local state.
If you can setup a small test project I will take a look.

**Comment by darko-mijic** [comment]
Thanks @foxhound87. We where using [react-intl](https://github.com/yahoo/react-intl) and our validators where returning an object instead of a string for validation errors. This was causing the issue. 

From @DominikGuzei's example:

``` javascript
const isValidWalletName = ({ field }) => {
  const isValid = field.value.length >= 3;
  return [isValid, messages.invalidWalletName]; // this is defined elsewhere (not important)
};
```

`messages.invalidWalletName` was an object:

``` javascript
invalidWalletName: {
    id: 'wallet.create.form.errors.invalidWalletName',
    defaultMessage: '!!!The wallet name must have at least 3 letters.',
    description: 'Error message shown when invalid wallet name was entered in create wallet dialog.'
  }
```

And it needed to be a string so the fix was to provide a validator with i18n features of `react-intl` to return a string for validation error instead of passing an object.
