### ISSUE TITLE
LodashModuleReplacementPlugin issue

### ISSUE THREAD

**Issue by mladen107** [foxhound87/mobx-ajv-form#124]
Hello,
It seems that current version is broken, I can't get fields initialisation to work

```
import MobxReactForm from 'mobx-react-form';

let fields = {
    username: {name: 'username', label: 'Email'},
    password: {name: 'password', label: 'Password'}
};

const loginForm = new MobxReactForm({fields});

console.log(loginForm.$('username').label);
```

it logs `undefined`, even inspecting `loginForm` in debugger shows that fields are empty.

**Comment by foxhound87** [comment]
Which version are you using?

The "current" version is 1.13.16 and it's working.

**Comment by mladen107** [comment]
After some debugging I found that   

`$this.handleFieldsNested(fields, initial);`

returns empty object for fields and from that point on fields are lost.

It turned out that [LodashModuleReplacementPlugin](https://github.com/lodash/lodash-webpack-plugin) removed `_.has` function that was used by `.handleFieldsNested` method.

Removing LodashModuleReplacementPlugin solved issues but I think it would be good to document what methods can't be removed with LodashModuleReplacementPlugin for people that care about every byte.

**Comment by foxhound87** [comment]
I'm not using `lodash-webpack-plugin`, only `babel-plugin-lodash`.
