### ISSUE TITLE
field touched and focus don't seem to work?

### ISSUE THREAD

**Issue by dmackerman** [foxhound87/mobx-ajv-form#125]
Not sure how these are supposed to work, but `touched` and `focus` are never true. What's the proper usage for these?

**Comment by liveresume** [comment]
Was wondering how to use these as well.

I would assume it is up to our components to determine whether they have been touched/focused. So then should we update mobx-form as shown below, and potentially let it pass back that state so our components remain stateless.  (BTW really liking the paradigm here of fully controlled/stateless components that mobx-form allows, great work)

```
<TextField
onFocus={ () => form.$(model).focus = true, form.$(model).touched = true }
onBlur={ () => form.$(model).focus = false }
focused={ form.$(model).focus }
touched={ form.$(model).touched }
/>
```

**Comment by liveresume** [comment]
I'm getting errors when trying to set focus and touched that they are computed values and cannot be set.  Can confirm @dmackerman issue.

**Comment by liveresume** [comment]
Just dug around the code to figure it out.  This works:

```
const helpers = (form, model) => ({
  onFocus: () => form.$(model).onFocus(),
  onBlur: () => form.$(model).onBlur(),
  focused: form.$(model).focus,
  touched: form.$(model).touched,
})
```

Also made a PR #126 to move touched=true to when the field is first focused.

**Comment by foxhound87** [comment]
Here you can find more info on **onFocus(e)** and **onBlur(e)** event handlers:

https://foxhound87.github.io/mobx-react-form/docs/events/events-handlers.html

**Comment by liveresume** [comment]
Thanks @foxhound87 touch/blur are working now. Appreciate the fast merge!

Looks like you can close this one.

**Comment by foxhound87** [comment]
@liveresume thank you for your contribution!
