### ISSUE TITLE
Post demo / example code.

### ISSUE THREAD

**Issue by diffractometer** [foxhound87/mobx-ajv-form#127]
Just wondering: Would it be possible to post the demo code? Having a bit of trouble following the tutorial. I'm confused about how to get from "Initialize the Form" to "Pass the form to a react component" as it seems as though you're implementing two different approaches. Anyway, thanks either way.

**Comment by foxhound87** [comment]
You can find the demo code on the `demo` branch:

https://github.com/foxhound87/mobx-react-form/tree/demo

**Comment by foxhound87** [comment]
I will also create a dedicated repo as asked in #94

**Comment by diffractometer** [comment]
@foxhound87 thanks a ton mang!!!

**Comment by foxhound87** [comment]
@diffractometer  FYI

I created a [dedicated demo repo](https://github.com/foxhound87/mobx-react-form-demo), and It's updated with custom components.

**Comment by diffractometer** [comment]
@foxhound87 Cool, thanks for doing that!
