### ISSUE TITLE
Bug using Array as value depending on Form init

### ISSUE THREAD

**Issue by liveresume** [foxhound87/mobx-ajv-form#132]
If we init the Form using separated props:

`new MobxReactForm({ plugins, values, defaults, rules })
`
Then using an Array as a value does not work.  

However, if initialized with unified props Array as value works:

`new MobxReactForm({ fields, plugins })
`

**Comment by foxhound87** [comment]
Please, can you post your complete code?

**Comment by liveresume** [comment]
Sorry made a mistake here.  Array as value issues seem to be happening when using deep fields.  Trying to dig further.

**Comment by liveresume** [comment]
Its a bug on my side.
