### ISSUE TITLE
Unable to update() array field values

### ISSUE THREAD

**Issue by chrissm79** [foxhound87/mobx-ajv-form#148]
I'm having a bit of an issue trying to set the values for an array (nested) field. I have a form that has a "files" field, which is an array. The user uploads a file and I want to append the file names returned in the response to the "files" field. I tried to use both `update` and `sync`, but with no success:

```javascript
// Fields defined as separated properties
const fields = [
  'files',
  'files[]',
  // ...
];

// `response` is an array of strings
_handleUploadSuccess = (response) => {
  const files = this.props.form.$('files');
  const values = files.value.concat(response);
  files.update(values);
  console.log(values); // ['file1', 'file2', ...]
  console.log(files.value); // displays empty array
  console.log(this.props.form.values()); // { files: [] ... }
}
```

**Comment by foxhound87** [comment]
**The array values of `files` are treated as fields.**

By design, you can not create the nested fields passing values to `update()` or `set()`.

`update()` expects an object of fields in input.
`set()` doesn't handle nested fields creation.

But you can use `update()` from the parent field container 
(the `form` in your case) passing the object to it:

``` javascript
const files = form.$('files');

const values = files.value.concat(['file1', 'file2']);

form.update({ files: values });


console.log(files.value); 
// => [ 'file1', 'file2' ]

console.log(files.values()); 
// => [ 'file1', 'file2' ]

console.log(form.values()); 
// => { files: [ 'file1', 'file2' ] }
```

**Comment by foxhound87** [comment]
Pay attention to the behavior of `.values()` which is to get all nested fileds values.

In the following example, the last log **is correct** because `foo` does not have nested fields!

``` javascript
const form = new Form({ fields: ['foo'] });

form.$('foo').set('value', 'bar');


console.log(form.$('foo').value);
// => bar

console.log(form.values());
// => { foo: 'bar' }

console.log(form.$('foo').values()); 
// => { }
```

**Comment by chrissm79** [comment]
Perfect, thanks @foxhound87!

I must say, I've never put together a form with nested fields and arrays so fast and easily before
