### ISSUE TITLE
Typings for Typescript

### ISSUE THREAD

**Issue by anotherpit** [foxhound87/mobx-ajv-form#150]
I'm going to provide typings for Typescript. There are two common ways of doing it:
1. Add `d.ts` file(s) to the library itself (the way `mobx` does, for example).
2. Publish typings under [DefinitelyTypes](http://definitelytyped.org/) a.k.a. [@types](https://www.npmjs.com/~types).

I'd prefer the first one. @foxhound87, any objections?

**Comment by foxhound87** [comment]
I never used TS, but I definitely want to try it. 

Adding the `.ts` files should be the way to go.

We can start a `typescript` branch before, so I can introduce it gradually.

**Comment by anotherpit** [comment]
Please, start it so I can create a PR and show come code to discuss. There're several options to consider, and I'd love to get some feedback from those who use `mobx-react-form` with Typescript.

**Comment by foxhound87** [comment]
I will create a separate branch initially.

**Comment by anotherpit** [comment]
@dalcib Does your upvote mean that you're using `mobx-react-form` with Typescript, no?

**Comment by anotherpit** [comment]
@foxhound87 Yep, that's what I'm asking for

**Comment by dalcib** [comment]
@anotherpit  I use Typescript in my projects and I did some experiments with mobx-react-form, but not with Typescript yet.

**Comment by anotherpit** [comment]
@dalcib For now you can check out [my fork](https://github.com/anotherpit/mobx-react-form/tree/typescript2). As soon as @foxhound87 creates `typescript` branch in this repo, I'll provide PR

**Comment by foxhound87** [comment]
branch created: https://github.com/foxhound87/mobx-react-form/tree/typescript

**Comment by anotherpit** [comment]
@foxhound87 Great, thanks! I need some time to reflect recent API changes in TS declarations, and then I'll create a PR.

**Comment by Metavirulent** [comment]
What's the status of this branch? Will it get merged into master at some point?
I think having types would be a huge benefit for us Typescript users and make the library easier to get into.

**Comment by foxhound87** [comment]
Hi @Metavirulent,  
it's on the [roadmap](https://gist.github.com/foxhound87/f176f19054148647e2a38d60cc09259b) and yes I will merge it when it's ready, but I don't have an ETA, @anotherpit started initially, but now the branch needs an update, the code is an older version,
If someone can help us to speed up the process I will update the branch with the new version asap.

**Comment by devdoomari** [comment]
how about moving the whole project to typescript? it's nearly a double-work to write JS and then write d.ts files when you can just write TS once...

**Comment by devdoomari** [comment]
@foxhound87 the typescript branch is going nowhere... (1 yr since last update)
and maintaining separate d.ts files is quite a work...

how about doing a gradual migration to Typescript?
e.g. start with one file, one function/variable definition, and start from there

**Comment by wwahammy** [comment]
@foxhound87 @devdoomari I have a local version converted to typescript. A lot  of the types are set to `any` initially but that can be improved. I'd be happy to prepare for submission if we think it'd be accepted if I submitted it. What would be required from your end @foxhound87 for it to meet your requirements? The reason I ask is that there's a lot of build tasks that would have to be figured out if that's a requirement.

**Comment by abhilashAtCopperMobile** [comment]
Anyone has a working sample of mobx-react-form with typescript.

**Comment by wwahammy** [comment]
@abhilashAtCopperMobile I have a pull request for an update of mobx-react-form in typescript https://github.com/foxhound87/mobx-react-form/pull/442

**Comment by abhilashAtCopperMobile** [comment]
@ericschultz 

I was able to create a typedef for my file and made it to work. Thanks for the quick reply. Hoping they will merge your PR asap.

**Comment by wwahammy** [comment]
@abhilashAtCopperMobile glad it helped! Do be careful about the types as MANY of them are set to `any`. So, while you get typing, they don't provide you much protection yet. Any improvements to the types though would be appreciated!

**Comment by prontiol** [comment]
Any updates on this?

**Comment by wwahammy** [comment]
@prontiol: you can get the typescript version at https://github.com/foxhound87/mobx-react-form/pull/442. @foxhound87 mentioned that he'd prefer to wait until he's made some progress on other things before merging the typescript version into master. I haven't made any progress on improving the types since https://github.com/foxhound87/mobx-react-form/issues/150#issuecomment-413256309 so a lot of types which should be more specific are still set to `any`. If you'd like to improve those types, I'd very much welcome pull requests to my repo to submit upstream. I hope that helps!

**Comment by rodolphofr** [comment]
Any updates? Already in 2019 haha

**Comment by wwahammy** [comment]
@rodolphofr I haven't worked on them since the updates in #442. I'm all for doing it but it's a lot of work to keep them as separate types definitions. Short of a clear path to #442 being committed, i.e. the project moving to Typescript, I don't think I can commit the kind of time necessary. Sorry.

**Comment by louiidev** [comment]
So there's no type package yet?

**Comment by danielwalczak** [comment]
+1 for typescript

**Comment by timmartin19** [comment]
Is there any way I can help with this?

**Comment by zif002** [comment]
+1 for typescript

**Comment by biels** [comment]
I have type definitions that I use in my projects: 
https://gist.github.com/biels/ed3b1549d74145e9d3615bba73997599
Those could be used as a starting point for adding full support for typescript.

**Comment by biels** [comment]
Any news on this? I can help if needed.

**Comment by foxhound87** [comment]
Version 4 prerelase has beed released with typscript support!
feel free to contribute in the `ts` and `next` branch!

**Comment by maurobender** [comment]
Hi @foxhound87! I see there is a pre-release for version v4.0.0 which supports Typescript but it is not set in npm as the latest release. Is it safe to use it anyways? Thank you!

**Comment by foxhound87** [comment]
@maurobender yes it is safe. The main functionalities are covered under tests.
I keep it as pre-release because I'm still in the process of typings all internals, 
but the public apis are already typed and the lib provide the main interfaces.
The latest pre-release has also some new tests and some new functionalities.
