### ISSUE TITLE
Allow `add()` to include `initialValue`

### ISSUE THREAD

**Issue by leesiongchan** [foxhound87/mobx-ajv-form#153]
Now the `.add()` is only accepting `path` which there is no way for us to include the `value` for some reasons.

**Comment by foxhound87** [comment]
I will implement this, thanks!

**Comment by foxhound87** [comment]
now you can do for example:

```javascript
form.$('hobbies').add('soccer');
```

**Comment by foxhound87** [comment]
`add()` now can accept only the field value (or nothing), 
and not a `path` or `key` anymore.
