### ISSUE TITLE
How to detect whether field is changed

### ISSUE THREAD

**Issue by lozinsky** [foxhound87/mobx-ajv-form#154]
Hi. Whether it is possible to add a flag **changed**, which changes once, like **touched**?

**Comment by foxhound87** [comment]
I think you can use isPristine, or should be a different behavior?

**Comment by lozinsky** [comment]
isPristine === isDefault, these flags may change again when the value comes back to the initial state.
For example, i have empty field for password, if password exists, i show placeholder until user wants to enter a value.


![example](https://cloud.githubusercontent.com/assets/15981489/20489230/e87d5aa0-b01a-11e6-984b-3d8798c34a1d.gif)

**Comment by lozinsky** [comment]
I did it like this
```js
class Password extends Component {
 //...
 @observable
 changed = false;

 handleOnChange = action(e => {
  this.props.field.sync(e);
  this.changed = true;
 });
 //...
}
```
but I have a problem with validation.

**Comment by foxhound87** [comment]
what kind of validation problem?

**Comment by foxhound87** [comment]
I added `changed` property in the new version: https://github.com/foxhound87/mobx-react-form/commit/63dedec005d965f8d141991a9f2a3628eb910372

**Comment by lozinsky** [comment]
Thank you!
