### ISSUE TITLE
field.setInvalid isn't working properly?

### ISSUE THREAD

**Issue by elazer** [foxhound87/mobx-ajv-form#168]
This is when some special conditions are not met after submitting the form. 
Errors are returned by the api. So I tried to use setInvalid to show the errors.

form.$('images').setInvalid('Please specify a primary image');

form.$('images').hasError is true
form.$('images').error is undefined.

**Comment by foxhound87** [comment]
Now should work, I will updated the docs too because it is referred to an the older implementation.

now is: `setInvalid(message<string>, async<boolean>);`

**Comment by foxhound87** [comment]
FYI `setInvalid()` will be deprecated in the version 1.17 and will be replaced with `invalidate()`.
