### ISSUE TITLE
Returning field key from add(); Provide way to set key on add()

### ISSUE THREAD

**Issue by liveresume** [foxhound87/mobx-ajv-form#169]
What do you think about these api improvements?

First, when we add a new nested field we should return its newly created key value.
`key = add({field1: 'hello'})`

Secondly, we should allow the key to be set when the object is first created.
`key = add({field1: 'hello'}, {key: 12345})`

We should only need some small changes in `src/shared/Actions.js`
Recommend we add an options object:
```
add(value = null, options ={}) {
    const { key = null } = options
   
    ... 
}

```

**Comment by foxhound87** [comment]
Should be ok, I will implement this.

**Comment by liveresume** [comment]
@foxhound87 Thank you

**Comment by foxhound87** [comment]
You are welcome!
