### ISSUE TITLE
How validate calculated values?

### ISSUE THREAD

**Issue by tiagowippel** [foxhound87/mobx-ajv-form#173]
How could I validate the sum of all persons who were added in certain table?
This sum could not be greater than 100 kgs for example.

Or I would have to need at least 5 people added ....

**Comment by tiagowippel** [comment]
example:

const rules = {
  'someField':            'required|string',
  'clients[].title':      'required|string',
  'clients[].firstname':  'required|string',
  'clients[].surname':    'required|string',
  'clients.length':  'min:5',
};

**Comment by foxhound87** [comment]
Hi @tiagowippel 

I don't know if I understood your first question.

About the number of people,
assume that you have a **fields** object with an **array** of people:

```javascript
const fields = {
   'people',
   'people[]',
}; 
```

using the **DVR** Validation Mode can be done using a **rules** object like this:

```javascript
const rules = {
   'people': 'array|between:0,5',
}; 
```

But there seem to be a bug: after the validation, the error is not thrown for `fields containers`, the form validation will `success`.

Anyway, the fields properties are correct: the error message is defined, you can use `form.$('people').error` inside your components to show the message, the field props `hasError` and `isValid` are correct,  but you have to manage the error inside the `onSuccess` manually, until I fix it.

```javascript
export default class Form extends MobxReactForm {

  onSuccess(form) {

    if(form.$('people').hasError) {

      form.invalidate();
    }
  }
}
```

**Comment by tiagowippel** [comment]
ok, I understood.

Now let me try to explain the first question.

supposing I have:


```
const fields = {
   'people',
   'people[].name',
   'people[].weight',
   'people.sumOfWeights'
}; 
```


where sumOfWeights would be a @computed value.... how could I do/validate this ?

```
var rules = {
    sumOfWeights : 'max:100'
};
```

**Comment by foxhound87** [comment]
That can't be done out of the box. You need to [Extend the Form](https://foxhound87.github.io/mobx-react-form/docs/api-reference/extend.html) and do it manually.

I think you can use the mobx `reaction` on the extended Form which will sum all your fields values to be set into another field `peopleSumOfWeights` and handle the validation on that.

something like:

```javascript
const fields = {
   'people',
   'people[].name',
   'people[].weight',
   'peopleSumOfWeights'
}; 

const rules = {
    peopleSumOfWeights : 'numeric|max:100',
};
```

```javascript
import { reaction } from 'mobx';
import _ from 'lodash';

const parseArrayOfStringsToInt = (array) => {
  // first you have to get the values of the `weight` field for each person,
  // set them into an array, and then you can parse to int and sum the values as following:
  return _.sum(_.map(array, _.ary(parseInt, 1)));
};

class MyForm extends MobxReactForm {

  onInit(form) {

    reaction(
      () => form.$('people').value,
      // the data handling is not completely correct, just an idea to use `reaction`
      array => form.$('peopleSumOfWeights').set('value', parseArrayOfStringsToInt(array)),
    );
  }
}
```

**Comment by foxhound87** [comment]
You can eventually keep the value `peopleSumOfWeights` hidden and show only the error message.

Keep in mind that you can't define `people.sumOfWeights` if you are defining `people[]` as array.

**Comment by foxhound87** [comment]
> where sumOfWeights would be a @computed value.... how could I do/validate this ?

All fields have computed values/properties, like `form.$('peopleSumOfWeights').value`

You can find all field **computed** props on the docs in the [Fields Properties](https://foxhound87.github.io/mobx-react-form/docs/api-reference/fields-properties.html) section.

The validation rules will only work against the `value` computed prop.

**Comment by tiagowippel** [comment]
Great, thank you!

**Comment by foxhound87** [comment]
You are welcome.

I reopen this because the `validation` for the `fields containers` values should be still fixed.

Thank You.

**Comment by foxhound87** [comment]
After some testing, I noticed that an empty array can be only validated against a `required` rule.

It depend on [skaterdav85/validatorjs](https://github.com/skaterdav85) implementation.
I opened an issue for the case:  https://github.com/skaterdav85/validatorjs/issues/152

Anyway I'm releasing an updated of the computed `hasError` and `isValid` properties which will fix the nested fields checks.

**Comment by truztee** [comment]
expanding on this question a bit, how do we define a computed property for a field in an array?
```javascript
const fields = {
   'people',
   'people[].firstName',
   'people[].lastName',
   'people[].fullName', // <-- this should be a computed property of firstName + lastName
   'people[].weight',
   'people.sumOfWeights'
}; 
```

**Comment by foxhound87** [comment]
Hi @truztee 

I'm sorry, I noticed your message just right now.

You can find an example in this issue: https://github.com/foxhound87/mobx-react-form/issues/235

In your case you need to concatenate the values in the `set()` method when using the `observers`.

I will post a blog article in the future to explain in details how to use the observers.

Thank You.

**Comment by zhaoyi0113** [comment]
Does `reaction` work as same as `observers`?

**Comment by foxhound87** [comment]
@zhaoyi0113 

The mobx docs says:

**observe** can be used to monitor the changes of a single observable (they don't track nested observables).

**reaction** is a variation on autorun. Unlike autorun the side effect won't be run directly when created, but only after the data expression returns a new value for the first time. The side effect will only be triggered when the data returned by the expression has changed. In other words: reaction requires you to produce the things you need in your side effect.
