### ISSUE TITLE
Can we use `decorators` instead of `extends`?

### ISSUE THREAD

**Issue by sanketsahu** [foxhound87/mobx-ajv-form#174]
I always recommend [Composition over Inheritance](https://www.wikiwand.com/en/Composition_over_inheritance).

Is there an option to use `decorators` instead of `extends`? Something like

```
@validatedForm
class MyForm {
    // ...
}
```

**Comment by foxhound87** [comment]
Thank you for the suggestion, should be very cool to use decorators.

Recently I was looking for a solution to inject plugins before the form instance is created, using decorator seems definitely the way to go.

I have to think about of new apis design for the next major version, other enhancements are already scheduled!

**Comment by sanketsahu** [comment]
@foxhound87 That's awesome! Thanks!

**Comment by foxhound87** [comment]
I reopen this issue. I will close it when the new apis will be released.

**Comment by foxhound87** [comment]
MobX removed the use of decorators in newer versions, so I’m closing this issue.
