### ISSUE TITLE
Wrong deep field path for initField() on update()

### ISSUE THREAD

**Issue by w-** [foxhound87/mobx-ajv-form#179]
if i have a form that is defined 

```
// this was edited to correct a typo. was originally "const rules"
const fields =[
	'name',
	'list.cat1',
	'list.cat1[].name',
	'list.cat1[].url',
	'list.cat2',
	'list.cat2[].name',
	'list.cat2[].url',
]

```

is it correct for me to define the rules like:
```
const rules = {
	'name': 'string|required|between:1,255',
	'list.cat1[].url' : 'url|required',
	'list.cat2[].url' : 'url|required',
}
```

when i attempt to validate the form, it appears that the nested fields are not getting validated. i.e. list.cat1[].url and list.cat2[].url

**Comment by foxhound87** [comment]
You can find a working example on the [demo repo in /src/forms/nestedFields.js](https://github.com/foxhound87/mobx-react-form-demo/blob/259773ae71487c703ea400c04240d99155250447/src/forms/nestedFields.js
).

In your example you are defining two const with the same name `rules`, you should name the first one as `fields`.

**Comment by w-** [comment]
sorry for the confusion. i typoed the first code block. As you correctly point out, the const shoudl be called "fields". fixed my typo.

I did have it defined the correct way in the code, thats why i'm curious as to why it isn't validating properly

**Comment by foxhound87** [comment]
I need to replicate your code and test it. 
If you can prepare a repo I will take a look.

**Comment by w-** [comment]
ok. Thank you for the generous offer. I'll review it again first and if i still can't figure it out i'll ping you.

**Comment by w-** [comment]
quick question.
in my example, if I were to create new values to list.cat1 by simply calling update 
```
cat1_arr = [
	{ name: 'blah', age: 99},
	{ name: 'argh', age: 'not an age'},
]
form.$(list.cat1).update(cat1_arr)
```

and not using
```
form.$(list.cat1).add({ name: 'blah', age: 99})
form.$(list.cat1).add({ name: 'argh', age: 'not an age'})
```

does it wipe out the rules somehow? 
I'm unsure if it is me, but usign the devtools when i drill down to this path:

```
list
	fields
		cat1
			fields
				0
					fields
						age
							rules
```

there is a rule there initially, but then after the update it becomes null. Do you have any idea what might be going on here?

**Comment by foxhound87** [comment]
You cannot pass an array in the `update()` method, it accepts only an object describing the fields keys with theirs values, not the value directly, you should do:

```javascript
    form.$('list').update({
      cat1: [{
        name: 'blah',
        age: 99,
      }, {
        name: 'argh',
        age: 'not an age',
      }],
    });
```

Then the rules should be there, but I noticed that the fields values are no more observed for validation after an update, similar to [this issue when using add()](https://github.com/foxhound87/mobx-react-form/issues/136) (but the validation still work on submit). Have you noticed the same?

I will update the docs with the correct input type for the `update()` method.

**Comment by w-** [comment]
thanks again for quick response.
wierd, i just checked my code and in fact i'm doing what you recommend. I must be making a mistake somewhere that is causing different behavior.

I haven't noticed the validation issue after update that you mention. thanks for the heads up and i'll watch for it

**Comment by w-** [comment]
do you mind taking a quick look at this gist?
it's pretty much my form at this point
https://gist.github.com/w-/3e15cadc60c9910c66c16b3b8f9d37c4

in onInit, i've commented out one of the del() statements.
this is so i can verify the rule is correct. in devtools we can see that the rule is added successfully to the default element added.

i'm basically testing the update and validation behavior by calling "createNewArticle"

When I call that function and observe the dev tools, the rules suddenly disappear after running the update. both in the old element and the new one.

**Comment by foxhound87** [comment]
- What's in the `layout` value passed to the `update()` method? 
- If you run `createNewArticle()`  without the `update()` method, the rules are still there? 

try to print this `onInit()`, before and after `update()`:

```javascript
console.log('Initial Rules', form.state.initial.props.rules);
console.log('Current Rules', form.state.current.props.rules);
```

and show me what you see. We should expect the same values.

**Comment by w-** [comment]
> If you run createNewArticle() without the update() method, the rules are still there?  

Yes

this screenshot shows the changes to onInit and after update you suggest.
it also shows the contents of "layout" that are passed to the update() method.
it appears that the rules are still there, but for some reason don't show up in devtools, nor do they validate properly when i call form.validate(). (the value of isValid is true, when it should really be false and complaining about the invalid url value)

![capture](https://cloud.githubusercontent.com/assets/357317/21431416/ba0e9f2a-c899-11e6-9f81-0ed6c8fb8b4c.JPG)

**Comment by foxhound87** [comment]
have you tried to print the rules into `createNewArticle()` before `update()`?

what do you see?

If you are using `createNewArticle()` as an event handler, try to avoid using `this`,  pass the whole form instead as I do in the other methods.

**Comment by w-** [comment]
regarding using "this" issue, isn't that kind of wierd? when i call the form method it becomes
something like
```
let vals = {
	/* some key vals */
}
let bForm = new BlahForm(vals)
bForm.createNewArticle(bForm)
```
or am i missing something?

**Comment by foxhound87** [comment]
where are you calling `createNewArticle()` ?

I mean doing this:

```javascript
createNewArticle(form, layoutKey='column1', idx=0) { 

  ...

  form.update();

  ...
}
```

**Comment by w-** [comment]
createNewArticle is called externally to the form.

so for example, i pass the form to a react component.
on the react component there is a button. when you press the button you call `createNewArticle()`

since `createNewArticle()` is defined as an instance method on the form, why would we need to pass the instance in again?

(i did notice your style of passing in the form as a parameter even when extending methods of the form. I was curious and wanted to ask the reason behind this)

**Comment by foxhound87** [comment]
Because if you call `createNewArticle()` on `onClick`it loose its context, like in [this example](https://github.com/foxhound87/weather-forecast-react-app/blob/bf0216601bc75cbdbf2413a45215f2fe01b87d63/src/components/SearchForm.jsx#L16).

**Comment by w-** [comment]
I think i'm misunderstanding.
in the example you have
`onChange={values => form.onChange(values, form)}`
in the docs 
https://foxhound87.github.io/mobx-react-form/docs/events/events-handlers.html  
it says that `onChange()` is an alias of `sync()` which looks like it takes an event as a param. 
are these the same function?

in any case i'll give your suggestion a go. i need to step away for a while so won't be able to report back till later.

Thanks for your continued support!

**Comment by foxhound87** [comment]
You are welcome. Yes `onChange()` and `sync()` are the same.

In the example I reimplemented `onChange` [here](https://github.com/foxhound87/weather-forecast-react-app/blob/bf0216601bc75cbdbf2413a45215f2fe01b87d63/src/forms/Search.js#L37) because in that case react-select has a different output for the `onChange` handler.

**Comment by foxhound87** [comment]
Try to do this which should auto-bind the form instance:

```javascript
createNewArticle = (layoutKey='column1', idx=0) => { ... }
```

then in the component:

```html
<button onClick={form.createNewArticle}>New Article</button>
```

otherwise, create a working repo, so I will get the whole picture.

**Comment by w-** [comment]
unfortunately, neither of those suggestions resolved the issue.

i created a repo that recreates the issue.
https://github.com/w-/argh

basically just do 
```
npm install
npm run build
```
then you should be able to load the index.html in a browser. 

Once in the file the starting state if the form will be that 
- `layout.column1` will have one element (the issue we discussed in #178 )
-if you drill down into the mobx-react-form dev tools, you will see that the expected rule shows up here. `url|between:0,255`
- this rule also shows up in the console output (from `onInit()`)

When you click the button, it will call `createNewArticle()`
- if you search mobx react form devtools, you will see that for both elements in `layout.column1`, the rules are wiped out 
- the rules are still reported as defined correctly per `form.state.current.props.rules`
- when we validate the form as a whole or the field individually, both report that the field value is valid and no errors are given.

Am interested to see what you think the underlying issue may be.

thanks

**Comment by foxhound87** [comment]
I think I found the issue, 
there is a strange bug using deep nested fields with fields array.

I will replicate the issue in the tests and release a fix for it asap.

In the meantime you can do this:

Removing the `layout` field container:

```javascript
const fields = [
  'id',
  'title',
  'column1',
  'column1[].id',
  'column1[].title',
  'column1[].img_url',
  'column2',
  'column2[].id',
  'column2[].title',
  'column2[].img_url',
];
```

and getting the values with `this.values()` instead of `this.$('layout').value`,

OR 

update the form with the complete object structure:

```javascript
this.update({
  layout: {
    column1: [{
      title: 'THE NEW TITLE',
    }]
  }
});
````

instead of:

```javascript
this.$('layout').update({
  column1: [{
    title: 'THE NEW TITLE',
  }]
});
```

In your case, you can simply change:

```javascript
this.$('layout').update(layout);
```

to:

```javascript
this.update({ layout });
```

Thank you for the repo and for your patience.

**Comment by foxhound87** [comment]
Fixed, now should work. 

Let me know if you encounter other issues.

Thanks.

**Comment by w-** [comment]
awesome. just tried it out. works.
Thanks very much for all your support and quick response!
