### ISSUE TITLE
Field.clear() only handles certain data types - bugs when field value is a Date

### ISSUE THREAD

**Issue by levic92** [foxhound87/mobx-ajv-form#180]
I have run across an issue with the ```.clear()``` method on a field. This field stores a Date. I took a look at the clear function and it looks like it only handles arrays, bools, numbers, and strings. Should there be a default action for other data types or an if statement added to handle Dates?

**Comment by levic92** [comment]
The ```isEmpty``` check also fails with a Date value

**Comment by foxhound87** [comment]
Thank you for reporting this issue. 

I will fix it asap.

**Comment by foxhound87** [comment]
Let me know if you encounter other issues.

Thank You!

**Comment by levic92** [comment]
Thanks for looking at this so quickly!
