### ISSUE TITLE
computed value is not an empty array when fields are undefined

### ISSUE THREAD

**Issue by w-** [foxhound87/mobx-ajv-form#183]
hi, 
ran into an issue today when attempting to use del()

I have an array for a field

```
let fields = [
    'argh',
    'argh[]',
]

```
if i give `argh` the value ['a', 'b', 'c']
and then attempt to do `form.$(argh).del(1)` the new value will be `['b', 'c']` (1-based index) instead of `['a', 'c']` (0-based index)

is this intentional? if so why?

Thanks

**Comment by foxhound87** [comment]
The arrays indexes are 0-based. It should work as expected.

Maybe your issue can be related to the use of `del()` used in `onInit()` as we previously discussed [here](https://github.com/foxhound87/mobx-react-form/issues/178)

**Comment by w-** [comment]
so digging around more it looks like `argh[]` field is implemented as a mobx observable map. and each element in the array is an element in the map.
The wierd thing is, when it starts up, the observable map has 1 element in it by default. not sure if this is related to #178 
The specific behaviour is
- values contains 0 elements
- fields contains 1 element

a side note,
When we use `del()` we need the key of the entry in the observable map. this is not necessarily the index of the element in the array we get from `.value`
so far the only thing i can think of is to get the map key from calling `.entries()`
e.g.

```
let index = form.$('argh').indexOf(val)
let entries = form.$('argh').fields.entries()
let targetKey = entries[index].key
```

is there a better way of doing this?

**Comment by w-** [comment]
> Maybe your issue can be related to the use of del() used in onInit() as we previously discussed here

the fields where this is happening are seperate to the fields i run del() on as per #178

**Comment by w-** [comment]
here's a screenshot of dev tools in case my explanation above isn't very clear.

![capture](https://cloud.githubusercontent.com/assets/357317/21483132/143cd0d4-cbb0-11e6-8086-e1227a8221ef.JPG)

**Comment by foxhound87** [comment]
The values are derived from the Map, in your case the **field container** "dl" will have only the values defined on its fields values, so if the new added field "1" doesn't have a value yet, you don't see it in the array

**Comment by w-** [comment]
i should've expanded the arrow. 
- 0 is there by default.
- 1 is the newly added value.

if I don't add anything to "dl" this is how the dev tools look
![capture](https://cloud.githubusercontent.com/assets/357317/21483557/b47fe7e2-cbb6-11e6-8c4b-3676081fce2a.JPG)

is this expected?

**Comment by foxhound87** [comment]
If the value of dl[0] is null/undefined/empty is right

**Comment by w-** [comment]
dl[0] is undefined. as you can see in the screenshot in the last post, dl is an empty array.

**Comment by w-** [comment]
check out the latest version of this repo
https://github.com/w-/argh

i modified the form and made another button.

when you first load the page, if you use the dev tools, you can drill down into `blah.fields.abe`
- values is an empty array (as expected)
- fields has 1 element in it

when you press the button, it executes `form.$('blah').init()` with an object `{ abe: [] }`
- values is an empty array
- fields is undefined

side effect here is that when we try and do something like
`for (let abe of form.$('blah').$('abe').value)` we get an error because `.value` no longer returns an empty array.

This seems like a bug, but it may be me just mis understanding how to consume the library.

**Comment by foxhound87** [comment]
Ok should be a side effect of init(). 

I have to write tests for the init() method, and I will fix it. 

It seems like I forgot to parse values there.

Thank you for replicating the issue on the repo.

**Comment by w-** [comment]
alrites. i'll test further once you've got a fix. thanks again for responsiveness.

**Comment by foxhound87** [comment]
* computed value is not an empty array when fields are undefined
Should be fixed in this release: https://github.com/foxhound87/mobx-react-form/releases/tag/v1.17.1

let me know if it is ok. Thank You!

**Comment by foxhound87** [comment]
PS: Do not use `init()` for now. It should work with `update()`.

**Comment by foxhound87** [comment]
It seems the issue occurs only if using `update()` after `init()`.
The `abe` field container stops to handle the nested fields as array and set it as empty string.

But if you initialize the form with the initial values the issue does not occur anymore:

```javascript
const nlForm = ArghFormFactory({
    blah: {
        abe: []
    }
}); 
```

this is very strange behavior, I will investigate deeply.

**Comment by foxhound87** [comment]
Anyway, I had not expected this behavior because the `init()` method is not intended to be used for updating the fields but only for initializing. 

It accept a **fields struct** in input if using **separated props**  or **fields values** if using **unified props**.

As you are using the **separated props** method, you should provide the struct to the `init()` method and not the values.

I will update the docs too.

**Comment by foxhound87** [comment]
And it seems also that `init()` should be removed from the fields apis. 
It work well only called from the Form, and it will re-initialize all the fields.

**Comment by foxhound87** [comment]
I think this fix will solve your first question: 

Fix: https://github.com/foxhound87/mobx-react-form/commit/611d909c0be103a628ef359bd0ba21fbbed42078
Issue: https://github.com/foxhound87/mobx-react-form/issues/195

**Comment by foxhound87** [comment]
The handling of arrays is improved in [version 1.19](https://github.com/foxhound87/mobx-react-form/commit/005d04c7)
