### ISSUE TITLE
Specific PropType for mobx-react-form?

### ISSUE THREAD

**Issue by w-** [foxhound87/mobx-ajv-form#184]
potential enhancement

The mobx package surfaces some custom propTypes for mobX observables etc.
as we are often passing fields/forms in as props, does it make sense for this package to define its own propTypes as well?

**Comment by foxhound87** [comment]
Yes, good idea, I will implement this. 

Thank you for the suggestion!

**Comment by foxhound87** [comment]
I tought more about this, and I think we don't need this as we only need one PropType for both the **Form** and **Field** objects. I suggest to use the `observableObject` PropType  provided by the [mobx-react](https://github.com/mobxjs/mobx-react) package.

**Comment by foxhound87** [comment]
Added to the FAQ

https://foxhound87.github.io/mobx-react-form/docs/faq.html
