### ISSUE TITLE
date field support

### ISSUE THREAD

**Issue by truztee** [foxhound87/mobx-ajv-form#185]
I'm trying to use a date type field inside a form, but the I cannot use the update method to update the date field.

```javascript
const fields = {
  someDate: {
    label: 'some date',
    rules: 'required|date',
  };

const form = new Form({fields, plugins});
form.update({ someDate: new Date()}); // this line failed to update the field
```

is there any workaround for this? I want to avoid using string for my date field.

**Comment by foxhound87** [comment]
Thank you for reporting this issue.

I will fix it asap.

**Comment by foxhound87** [comment]
The bug is fixed, let me know if you encounter other issues.

Thank You.

**Comment by truztee** [comment]
Great! Thanks for the quick update.
