### ISSUE TITLE
Defining a simple array of strings

### ISSUE THREAD

**Issue by kitze** [foxhound87/mobx-ajv-form#186]
This is my form structure:

```js
const fields = [
  {
    name: 'name',
    label: 'Name',
    rules: 'required|string|min:8',
  },
  {
    name: 'question',
    label: 'Main question you want to ask all participants',
    rules: 'required|string|min:8'
  },
  {
    name: 'description',
    label: 'Description',
    rules: 'required|string'
  },
  {
    name: 'endDate',
    label: 'End Date',
    rules: 'required',
    value: new Date()
  },
  {
    name: 'categories',
    label: 'Categories',
  }
};
```

I want the ```categories``` field to be a simple array of strings becaue I want to connect it to [this component](https://github.com/TeamWertarbyte/material-ui-chip-input).

I saw [this answer](https://github.com/foxhound87/mobx-react-form/issues/116) but I don't like to split my field definitions into 3 arrays, I want to keep it as an object. Also I don't need ```'categories[].title'``` etc. I just want each category to be a string, not an object.

Can you please help with this?

Thank you!

**Comment by foxhound87** [comment]
Hi @kitze 

It depends on how the custom input component is designed.

In your case I think you don't need **nested fields**.

You should do something like this using `value` as array of strings:

```javascript
  fields: [{
    name: 'categories',
    label: 'Categories',
    value: [], // <<< set initial value as empty array or array of strings
  }],
```

the `initial` and `default` property will be filled with the initial value, but they can be overwritten as well into the field object just like using `value`.

now you can use them on the component:

```javascript
  <ChipInput
    defaultValue={form.$('categories').default}
    onChange={form.$('categories').onChange}
  />
```

**Comment by kitze** [comment]
The tricky part is that in order for [this component for chip input](https://github.com/TeamWertarbyte/material-ui-chip-input#usage) to be "controlled" it needs the "value" property to be an array of strings and then it has 2 callbacks for add/remove chip:

```js
// controlled input
<ChipInput
  value={yourChips}
  onRequestAdd={(chip) => handleAddChip(chip)}
  onRequestDelete={(chip) => handleDeleteChip(chip)}
/>
``` 

In your solution, you're using defaultValue and onChange but that's not how this component works.

Is what I'm asking for possible, or do I need to mess around with a custom solution?

Thanks for your help!

**Comment by foxhound87** [comment]
you can do:

```javascript
      <ChipInput
        value={form.$('categories').value}
        onRequestAdd={form.$('categories').sync}
        onRequestDelete={form.$('categories').sync}
      />
```

> `sync()` is just an alias of `onChange()`

or eventually you can reimplement the handlers if you need.

**Comment by foxhound87** [comment]
more precisely in your case:

```javascript
const onAdd = (form, chip) => {
  const value = form.$('categories').value;
  console.log('values', [...value, chip]);
  form.$('categories').sync([...value, chip]);
};
```

```javascript
<ChipInput
  value={form.$('categories').value}
  onRequestAdd={(chip) => onAdd(form, chip)}
  onRequestDelete={(chip) => onDel(form, chip)}
/>
```

**Comment by kitze** [comment]
Alright, got it. 

Thank you!

**Comment by casper-fernandes** [comment]
What if each of the above categories field is bound by validation like string length?
