### ISSUE TITLE
placeholder does not hold values for nested separate properties

### ISSUE THREAD

**Issue by Log-of-e** [foxhound87/mobx-ajv-form#190]
values and labels persist in mobx store but placeholders does not persist in mobx store. I am doing a workaround by adding extra values and then mapping into the form. 

fld.js:
const fields = [
  'someField',
  'club.name',
  'club.city',
  'members',
  'members[].firstname',
  'members[].lastname',
  'members[].hobbies',
  'members[].hobbies[]',

]

const values = {
  club: {
    name: 'Jazz Club',
    city: 'New York',
  }
}

const placeholders = {
    'someField':'placholder'
     club: {
    name: 'plachedolder Jazz Club',
    city: 'placholder New York',
  }

}

const labels={/\*labels object\*/}

export default { fields, values, placeholders, labels };

**Comment by foxhound87** [comment]
Hi @Log-of-e 

I cannot replicate it. 
It works in tests and demo repo.

Are you doing some operations on the form?

**Comment by Log-of-e** [comment]
I used some of your demo code - which extends the Form class. Then I looked for the placeholder property with and without "get" but instead got 'undefined'.

  Could you please point me to the demo- I will check what I am missing. Does your demo use 'separate' and 'nested'? Maybe I should not use 'separate' and 'nested'.

 Thanks!

**Comment by foxhound87** [comment]
You can use separated and nested.

You can find the field definitions here: 
https://github.com/foxhound87/mobx-react-form-demo/blob/master/src/forms/nestedFields.js

The demo form component here:
https://github.com/foxhound87/mobx-react-form-demo/blob/master/src/components/forms/FormWithNestedFields.jsx

**Comment by foxhound87** [comment]
Also if you are using the 1.18 version, the constructor arguments are a bit changed:
https://foxhound87.github.io/mobx-react-form/docs/api-reference/form-initialization.html

Options, plugins and bindings goes on the second argument now.

**Comment by Log-of-e** [comment]
Thanks I will look thru.
