### ISSUE TITLE
.value and .values() return the field definitions instead of actual values

### ISSUE THREAD

**Issue by kitze** [foxhound87/mobx-ajv-form#193]
After updating to latest version of mobx and mobx-react-form, the return values of ```.value``` and ```.values()``` are always the field definitions, instead of the actual values.

Probably a bug with MobX 3.

**Comment by foxhound87** [comment]
Hi @kitze 

I cannot reproduce your issue. 

The field computed **value** should return the actual field value (with its nested fields values), but **values()** should return only its nested fields values (so if the fields doesn't have nested field, should return an empty object).

If the fields computed **value** are not working properly then you should have trouble also when you type into the inputs (using sync() / onChange()).

I recently also updated the [demo repo](https://github.com/foxhound87/mobx-react-form-demo) with mobx 3 and it seems to work.

Are you performing some operations with some form/fields actions?

Using the version **1.18**+ check the [constructor arguments](https://foxhound87.github.io/mobx-react-form/docs/api-reference/form-initialization.html) which are a bit changed, some objects are moved on the second argument (form options, plugins, bindings), and the first argument is reserved to the fields props.

**Comment by kitze** [comment]
Ah, that was it. Thanks!

I'll try to look through the changelogs before opening an issue next time. 

👍
