### ISSUE TITLE
del and add behavior

### ISSUE THREAD

**Issue by luthv** [foxhound87/mobx-ajv-form#195]
```javascript
const fields = [
  'items[]',
  'items[].qty',
  'items[].amount'
];

const store = new Form({ fields });
const items = store.$('items');
items.del(0); // delete the initial array item
items.add({ qty: 0, amount: 0  }); // add new item

// access the newly added item
const newItem = items.$(0); // <--- this will throw an error, the new item is actually available at index 1
```

Is this the expected behavior? the starting index is now starts at 1 instead of 0 when the array field is deleted and then re-added.

**Comment by foxhound87** [comment]
@luthv thank you for reporting this. 

Now should work as expected.

Thank You!

**Comment by luthv** [comment]
Thanks I can confirm that it worked as expected now.

However is there any way to re-index the keys after deletion?
Let's say we have three items in the array and we delete the item at index 1 (```store('items').del(1)```), in this state we can no longer access item at index 1, I was expecting that the item at index 2 will be shifted up to replace the deleted item like a normal array.

```javascript
const fields = [
  'items[]',
  'items[].qty',
  'items[].amount'
];

const store = new Form({ fields });
const items = store.$('items');
items.add({ qty: 1, amount: 0  }); // add second item
items.add({ qty: 2, amount: 0  }); // add third item

items.del(1); // delete the second item, the third item should move up to replace the deleted item

console.log(items.$(1)); // this will fail
```

**Comment by foxhound87** [comment]
This because the nested fields are handled with an observable map.

This behavior should be implemented, I'll see what I can do.
