### ISSUE TITLE
Material DatePicker

### ISSUE THREAD

**Issue by ghost** [foxhound87/mobx-ajv-form#196]
Any examples from this repo for creating the popup DatePicker from Material-UI? I can't get a click action on the DatePicker myself, so it's functional (I can set defaultDate etc.) but no pop-up ensues.

**Comment by foxhound87** [comment]
Hi @stevecawdery 

are you getting some errors in the console?

**Comment by foxhound87** [comment]
If you are getting **Uncaught TypeError: Cannot read property 'target' of null** I made a fix that will allow to use the built-in **sync() / onChange()** handlers:

https://github.com/foxhound87/mobx-react-form/releases/tag/v1.18.8

(It is a generic implementation for handling a second arg as value)

**Comment by foxhound87** [comment]
I close this issue for inactivity.

Feel free to reopen this if you need more help.
