### ISSUE TITLE
Fill the gap for unified mode to handle complex structure like separated mode

### ISSUE THREAD

**Issue by dmackerman** [foxhound87/mobx-ajv-form#197]
Hi there!

Sorry for the long issue, but it's the only way I can explain what I'm trying to do. 😄 

I'm trying to create a component that looks like this:

<img width="586" alt="screenshot 2017-01-31 08 31 36" src="https://cloud.githubusercontent.com/assets/289938/22471519/cbf4a2c4-e78f-11e6-8c90-de9086379d58.png">

I've chosen to use the "unified" fields definition, because it seems to make more sense for large forms that have a lot of values versus keeping them separated. Here's what the definition looks like for the field.

```js
  {
    name: 'sending_ips',
    label: 'Sending IPs',
    rules: 'required',
    value: [],
  },
```

Based on what I've seen in the documentation, this is correct? If I look at the Form dev tools, it properly has captured the values as an array:

<img width="226" alt="screenshot 2017-01-31 08 35 10" src="https://cloud.githubusercontent.com/assets/289938/22471653/3501989e-e790-11e6-8cc1-80dcae14e3f3.png">

I've created a component that I use to render the fields and Add/Remove them as needed. I simply pass in the `field` prop like so:

```js
<InputMultiple
  field={form.$('sending_ips')}
  inlineLabel
/>
```

And the component itself:

```js
const InputMultiple = ({ field }) => {
  return (
    <Box>
      <Label field={field} inlineLabel>
        {field.map((f) => {
          return f && (
            <Box className="pt-input-group" mb={1} key={f.id}>
              <Input field={f} key={f.key} showLabel={false} />
              <Button
                className="pt-minimal"
                intent={Intent.DANGER}
                onClick={f.onDel}
                iconName="cross"
              />
            </Box>
          );
        })}
        <Button iconName="plus" onClick={field.onAdd} text="Add Value" />
        <ErrorBlock field={field} />
      </Label>
    </Box>
  );
};

export default observer(InputMultiple);
```

I've copied some of this code from your demo-examples (which are great, btw). The issue I'm having is that:
- `{field.onAdd}` does not do anything. The removal of individual fields works as expected inside of the `map`.
- The validation rules are not applied to the individual fields
- If I change the field definitions to use the "separate" style - and use `sending_ips[]`, the `field.onAdd` works correctly. 

Am I missing something, or is it not possible to achieve this with the unified field definition style? I've read over the FAQs and I'm not sure my question has been answered. I believe my issue is similar to https://github.com/foxhound87/mobx-react-form/issues/186, except I'm just trying to create multiple standard input fields to render the values into.

Thanks again!

**Comment by foxhound87** [comment]
Hi @dmackerman 

Your code is ok, and your observation about the **separated props** mode is right as well, in fact when you have a field structure with nested fields, the lib must know the **fields structure** in order to add new fields. I still don't have implemented a way for the **unified props** mode to be automatically aware of the deep fields structure.

**Comment by foxhound87** [comment]
Anyway, right now, using **separated props** mode will let you define more complex deep nested fileds array and objects, and better props handling for nested fields as well.

For example the validation props for the array elements, cannot be defined before the fields are created if you are using **unified props** mode, **separated props** mode is required in this case:

```javascript
const rules = {
  'sending_ips': 'required', // <- only for the field container
  'sending_ips[]': 'required', // <- for each field in the array
};
```

**Comment by foxhound87** [comment]
If you want to stick to **unified props** you can also have the opportunity to update the fields props dynamically when the form is initialized, for example:

```javascript
class MyForm extends MobxReactForm {

  onInit() {
    this.$('sending_ips')
      .forEach(field => field.set('rules', 'required'));
  }
}
```

**Comment by dmackerman** [comment]
Thanks for the reply. I'm in the process of debating whether or not I want to write a transformation layer that essentially converts the nested style into the separated style, and then initializing the form with those objects.  Something like...

```js
const transformFields = (fields) => {
  const fieldMap = {
    fields: [],
    labels: {},
    placeholders: {},
    related: {},
    rules: {},
    types: {},
    values: {}
  };

  Object.keys(fields).forEach((fieldName) => {
    const field = fields[fieldName];

    // handle "array" fields and create entries dynamically here.

    fieldMap.fields.push(fieldName);
    fieldMap.labels[fieldName] = field.label;
    fieldMap.placeholders[fieldName] = field.placeholder;
    fieldMap.related[fieldName] = field.related;
    fieldMap.rules[fieldName] = field.rules;
    fieldMap.types[fieldName] = field.type;
    fieldMap.values[fieldName] = field.value;
  });

  return fieldMap;
};
```

**Comment by foxhound87** [comment]
Thank you for the suggestion, that's a good starting point.

To be complete it should handle fields recursively (with flat array and array of objects too).

With a proper implementation this can fill the gap for the two modes.

**Comment by foxhound87** [comment]
Right now, the lib is doing the opposite of that, this because the **unified properties** reflects the data structure of the form fields **stores**.

Here you can see the [prepareFieldsData](https://github.com/foxhound87/mobx-react-form/blob/c5250a420d04d447e76fb9a2a909a6a590d864c1/src/parser.js#L117) method, which is responsible to create the proper **unified** data structure.

**Comment by mwarger** [comment]
Thanks for looking into this.  I am also looking forward to using the unified field structure, and was dismayed when I realized that onAdd would not work in that case.  Filling this gap will be a great addition.

**Comment by foxhound87** [comment]
HI @mwarger 

Right now the big issue is that with the unified mode you cannot specify deep nested fields, for example, if I have an array of objects. But I will figure it out!

**Comment by sangallimarco** [comment]
I'm using the unified props and converting it in to a separate props using something like: 

``` javascript
class FormService {

//.....

  normalise(
    data,
    struct = { fields: [], labels: {}, extra: {}, rules: {} },
    prevName = ""
  ) {
    data.forEach(fieldDef => {
      const { name, label, extra, rules } = fieldDef;
      const key = this.getName(name, prevName);

      struct.fields.push(key);

      if (fieldDef.fields) {
        this.normalise(
          fieldDef.fields,
          struct,
          this.calculateName(name, prevName)
        );
      } else {
        struct.extra[key] = extra;
        struct.labels[key] = label;
        struct.rules[key] = rules;
      }
    });

    return struct;
  }

  getName(name, prevName) {
    return `${prevName}${name}`;
  }

  calculateName(name, prevName) {
    return `${prevName}${name}[].`;
  }

//...

}

export const formService = new FormService();
```

The result can be passed to the form:

```javascript 
const normalised = formService.normalise(unifiedProps);
// ...
const form = new Form({ ...normalised, values }, { plugins, hooks });
```

**Comment by foxhound87** [comment]
I've updated the package introducing the `struct` prop.

Take a look here: 
https://github.com/foxhound87/mobx-react-form/blob/master/tests/data/forms/fixes/form.q1.js

**Comment by biels** [comment]
Any updates on this? As far as I know, unified mode is still way less powerful than separated mode. What about standarising something based on the solutions (transformation layers) people shared in this issue?
