### ISSUE TITLE
Validate Field onBlur

### ISSUE THREAD

**Issue by DominikGuzei** [foxhound87/mobx-ajv-form#198]
I wonder if it is possible to only validate a field on blur? Or at least to trigger the validate function *also* when the field is blurred. I had to introduce a state variable to make it work:
```jsx
<Input
  value={this.state.password}
  onChange={(password) => this.setState({ password })}
  onBlur={() => {
    this.form.$('password').onChange(this.state.password);
    this.form.$('password').onBlur();
  }}
/>
```

**Comment by foxhound87** [comment]
You should just use `this.form.$('password').validate()` into the `onBlur()` handler and without the need to use local component state, so you should be able to use the built-in `onChange()`.

**Comment by foxhound87** [comment]
Assume we have reimplemented the `onBlur()` handler like this:

```javascript
const onBlur = field => (e) => {
  e.preventDefault();
  field.onBlur();
  field.validate();
};
```

> In this case the handler is a function which takes the `field` in input and returns a function which accept a `Proxy` object in input.

Now we can use the handler in 2 different ways:

**Using Props Bindings Priority:**

```javascript
export default observer(({ field, type = 'text' }) => (
  <div>
    <div>
      <label htmlFor={field.id}>{field.label}</label>
      <i>{field.error}</i>
    </div>
    <input {...field.bind({ type, onBlur: onBlur(field) })} />
  </div>
));
```
> The `onBlur` prop passed to the `bind()` method will take precedence on the `field.onBlur()` method.

Read more about [Using Default Bindings](https://foxhound87.github.io/mobx-react-form/docs/bindings/default.html) on the docs.

**Using a Custom Bindings Template:**

```javascript
export default {

  MyCustomInput: ({ $try, field, props }) => ({
    ... // define here other custom bindings 
    onBlur: $try(props.onBlur, onBlur(field)),
  }),

}
```

> The $try() helper will check first if there is custom `onBlur` for the `.bind()` method, if it doesn't exist will use the `onBlur` handler specifically defined for that binding template.

Read more about [Defining Custom Bindings](https://foxhound87.github.io/mobx-react-form/docs/bindings/custom.html) on the docs.

**Comment by foxhound87** [comment]
I made a [blog post](https://medium.com/@foxhound87/validate-field-onblur-using-props-bindings-in-mobx-react-form-3de48ba00576) as It seems a good case to explain also how to use bindings. 

If you are having other issues or something is not yet clear let me know.

I'm closing this issue as it is linked to the [FAQ](https://foxhound87.github.io/mobx-react-form/docs/faq.html) too, Thank You.
