### ISSUE TITLE
changing form option after init for validateOnChange doesn't work

### ISSUE THREAD

**Issue by ghost** [foxhound87/mobx-ajv-form#201]
If I setup my form using options in extended form class with `validateOnChange : false` and then later use `form.state.options.set({validateOnChange: true})` the option does get changed however form doesn't actually validate on change.

As an example using rfx-stack,

add following to 'src/shared/forms/_.extend.js'
```
options() {
    return {
        validateOnChange: false,
    };
}
```
and add these lines to the onError function
```
form.state.options.set({ validateOnChange: true });
console.log(form.state.options.get('validateOnChange')); // correctly returns true
```
expected functionality is that the form will not show validation errors until form has attempted to be submitted, then validation will be shown / updated as values are being changed.
(so the validation errors should disappear as the errors are being resolved)

**Comment by foxhound87** [comment]
This because the mobx `observe` is called once when a field is created.

I will fix this behavior to play well when options changes.

**Comment by foxhound87** [comment]
Now should work, let me know.
