### ISSUE TITLE
ways to navigate the field tree (with repeating subforms)

### ISSUE THREAD

**Issue by faassen** [foxhound87/mobx-ajv-form#202]
I found myself having to write code like this in a validator, where the validation state of one field is
dependent on another in the same repeating value:

```
  // we want to validate entries[2].b
  // split it into parts
  const parts = field.path.split(".");
  // cut off the 'b' bit and add 'a', on which validation depends
  const aPath = [...parts.slice(0, -1), "a"].join(".");
  // extra value of a
  const a = form.$(aPath).value;
  // now validate field.value based on 'a'
```

I now find myself having to write something very similar for another use case: I want to implement an onBlur handler for one field that clears another. 

It would be nice to have a navigation API to navigate to the parent field:

```
parentField = field.parent
```

If I read it correctly ``field.select`` can be used to navigate downwoards.

**Comment by faassen** [comment]
A bit hacky, but this code works for me:

```
function siblingField(field, name) {
  const parts = field.path.split(".");
  const parentPath = [...parts.slice(0, -1), name].join(".");
  return field.state.form.$(parentPath);
}
```

But ``state.form`` is an internal I am not sure is safe to use.

**Comment by foxhound87** [comment]
This feature is already implemented, we have the **container()** method which will return the parent field container. I forgot to mention it on the docs, I will update it. 

https://github.com/foxhound87/mobx-react-form/blob/master/src/shared/Utils.js#L44
