### ISSUE TITLE
Negative boolean value does not synced

### ISSUE THREAD

**Issue by lozinsky** [foxhound87/mobx-ajv-form#203]
**Version: 1.18.13**

Hi, i have field with boolean value.

When i call:
```
field.sync(false);

console.log(field.value); // -> null
```
but i can call:
```
field.sync(null, false);

console.log(field.value); // -> false
```
This is normal behavior?

**Comment by foxhound87** [comment]
The `sync` method is an **Event Handler**, so normally the first value should be a **Proxy** object. But I made its logic to also change a field value directly, so it should work. I will fix it asap.

**Comment by lozinsky** [comment]
Thank you.

**Comment by foxhound87** [comment]
Now should work. Let me know.
