### ISSUE TITLE
fields value converters: parsers & formatters

### ISSUE THREAD

**Issue by faassen** [foxhound87/mobx-ajv-form#204]
To make this question as general as possible: is mobx-react-form about producing submit values that could potentially contain any JS or Json datatype as values, or is it about producing a subset of strings, lists and objects?

Do we want to support field values that are not strings, such as numbers? Is something like that possible now? If you attached a "turn number into string" and the inverse "turn string into number" to
a field you could make it possible to use numbers as form values (both as initial values as well as output).

This implies that field input also needs to be able to decode an incoming value to the internal value it is using (typically a string displayed in the UI).

Related to this is the validation system. Validation is used to check whether a field value is valid. Conversion takes that valid value and converts it into another datatype. I would imagine a JSON-schema
validator in particular would benefit from doing the validation on the resulting datatypes instead of on the form values.

Here is a concrete use case that could be solved with such a system and only involves strings:

I'm using a particular date picker widget which sets a field to an iso datetime string. I actually just want the date component and remove the time component. I can write this code manually just before submit, but it gets cumbersome, especially when you have nested forms. It would be nice if I could specify this more declaratively on a per-field basis. An input converter and output converter would do the trick.

**Comment by foxhound87** [comment]
Implemented in [version 1.19](https://github.com/foxhound87/mobx-react-form/commit/005d04c7)

[Converters](https://foxhound87.github.io/mobx-react-form/docs/api-reference/converters.html)

**Comment by nuschk** [comment]
@foxhound87, for some reason (I'm having multiple forms of the same class on the same screen), I'm setting the form's initial values after the form is constructed. 

    form.set(initials);

Now, with converters, I need to pass in the parsed value here, correct?

Is there a better way to do this?

*Edit*: I just realized I can intermingle separate fields definitions with unified ones, so I'm able to write this:

    form = new MyForm({ fields, values: initials })

which correctly uses the converters and solves that for me.

(BTW, the amount of use cases that are already possible to handle with this library is amazing, and in a very clean way. Keep up the good work and thanks a lot for making it!)

**Comment by foxhound87** [comment]
Hi @nuschk 

The parser is not working when using `set()`? I can make a fix for this.

Anyway using the constructor is better to initialize forms data.

**Comment by nuschk** [comment]
Hey, thanks for your fast reply. Well, from my point of view that would make sense, as you'd expect the model to operate on parsed values. But then again, I'm still working on my first form with mobx, so I don't really know what that implies, nor if it reflects the general architecture. 

I changed my code to use the constructor, so no problem for me. 

Your decision I guess!
