### ISSUE TITLE
Support for file type

### ISSUE THREAD

**Issue by DominikGuzei** [foxhound87/mobx-ajv-form#205]
Hey there,
i'm running into a problem with a custom file select input component that expects an optional instance of `File` for the `selectedFile: PropTypes.instanceOf(File)` prop.

Now i defined a mobx-react-form field with `type: 'file'` and `value: null` for it but it still has a default value of `''` (empty string), which results in an error because the file picker does not accept strings. How can i set default value to `null` in this case?

**Comment by foxhound87** [comment]
File type is still not supported.

Which component are you using for handling files? is it open sourced?

I have to figure out how to handle this.

**Comment by DominikGuzei** [comment]
Hey @foxhound87 thanks for the fast respone. It's not open source but just a thin wrapper around [react-dropzone](https://github.com/okonet/react-dropzone)

**Comment by foxhound87** [comment]
I think this fix should work.

Set the fields props as follow: 

`type: 'file'` and **optionally** `value: null` or `default: null`

**Comment by DominikGuzei** [comment]
Thanks for the ultra fast fix! works like a charm now 😉

**Comment by foxhound87** [comment]
@DominikGuzei 
Using `null` on a simple input with `type="file"` I get:

```
Warning: `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.
```

So the default value should be an empty string, and you should set `null` manually on your custom component.
