### ISSUE TITLE
Validation error with 3rd party jquery library

### ISSUE THREAD

**Issue by pyprism** [foxhound87/mobx-ajv-form#210]
I am trying to use [this](https://github.com/itsjavi/fontawesome-iconpicker) library . I initialized the plugin in componentDidMount method .

```
 let icon = ReactDOM.findDOMNode(this.refs.iconPicker);
 $(icon).iconpicker();
```
When I tried to save the form I got following error
`The Icon field is required.`

**Comment by foxhound87** [comment]
I don't have so much info to understand your issue.

What's the use of the **Icon** Field?

Can it be a minification issue? (Seems like the **$** should be the jquery instance but got the Form instance?)

Show your form configuration please.

**Comment by pyprism** [comment]
Here is my codes:
```
const plugins = { dvr: validatorjs };

const fields = {
    icon: {
        label: 'Icon',
        rules: 'required|string'
    }
};


class NewPasswordForm extends MobxReactForm {
    onSuccess(form) {
        console.log(form.values());
    }

    onError(form) {
        // get all form errors
        console.log('All form errors', form.errors());
        // invalidate the form with a custom error message
        form.invalidate('Form is not valid!');
    }
}

export default new NewPasswordForm({ fields }, { plugins });
```

```
@observer
export default class Form extends React.Component {
 componentDidMount() {

        let icon = ReactDOM.findDOMNode(this.refs.iconPicker);

        $(icon).iconpicker();
}

 render() {

        return (
            <div >
                <div className="row">
               <form className="form-horizontal" >
               <div className="form-group" >
                        <label className="control-label col-sm-2" htmlFor={NewPasswordForm.$('icon').id} > {NewPasswordForm.$('icon').label} </label>
                        <div className="col-sm-10">
                            <input className="form-control " ref="iconPicker" {...NewPasswordForm.$('icon').bind()} />
                            <span className='error text-danger' >{NewPasswordForm.$('icon').error}</span>
                        </div>
                    </div>
<div className="form-group">
                        <div className="col-sm-offset-2 col-sm-10">
                            <button type="submit" className="btn btn-default" onClick={NewPasswordForm.onSubmit}><i className="fa fa-save" /> Save</button>
                        </div>
                    </div>
                </form>
            </div>
            </div>

```
and demo

![demo](https://cloud.githubusercontent.com/assets/1469242/22960282/b03fd8c2-f366-11e6-905d-a1b6ec60c208.gif)

**Comment by foxhound87** [comment]
Are you using the built-in onSubmit event handler?

**Comment by pyprism** [comment]
Of course in the submit button.
`<button type="submit" className="btn btn-default" onClick={NewPasswordForm.onSubmit}><`

**Comment by foxhound87** [comment]
Why the value is disappearing when clicking the save button?

**Comment by foxhound87** [comment]
I think the value is not applied on the field store. Can you check it using the [DevTools](https://github.com/foxhound87/mobx-react-form-devtools)

Maybe you have to get the value from the plugin instance and set it to the field store manually.

**Comment by foxhound87** [comment]
Probably the jquery plugin contrast the react rendering.
You should try to control the iconpicker from a separate element.
Then the field value should be set manually.

**Comment by foxhound87** [comment]
Solved?
