### ISSUE TITLE
Cannot set error on individual (nested) field. 

### ISSUE THREAD

**Issue by liveresume** [foxhound87/mobx-ajv-form#211]
Choose a field then invalidate it with msg.  
Note that this is using nested fields.

```js
model = form.$('jobs[0]')
key = 'company name'

model.$(key).invalidate('some error')

// This is correct
model.$(key).error == 'some error'

```
However, no error whatsoever is being passed via bind() to the component.

**Comment by foxhound87** [comment]
I think we can close both the issues.

**Comment by liveresume** [comment]
Still having a problem with this one unfortunately.

**Comment by foxhound87** [comment]
Keep in mind that the props passed to the `bind()`method should be accepted by the component you are using. the default input tag doesn't accept the `error` prop.

**Comment by liveresume** [comment]
these are the only props I am getting from bind()

```
disabled: false
id: "jobs-0-companyName--65"
label: "companyName"
name: "companyName"
onBlur: ()
onChange: ()
onFocus: ()
placeholder: ""
type: "text"
value: "c"

```

**Comment by foxhound87** [comment]
Sorry... What's the issue?

**Comment by foxhound87** [comment]
To pass the error prop to the bind method you need to implement a new binding template.

https://foxhound87.github.io/mobx-react-form/docs/bindings/custom.html

**Comment by liveresume** [comment]
```js
class MyForm extends MobxReactForm {
  bindings() {
    return {
      default: {
        id: 'id',
        name: 'name',
        type: 'type',
        value: 'value',
        label: 'label',
        placeholder: 'placeholder',
        disabled: 'disabled',
        onChange: 'onChange',
        onFocus: 'onFocus',
        onBlur: 'onBlur',
        error: 'error' //////////////////////////////////////
      }
    }
  }
}
```

Is there any way to set them like:

```js
const form = new MobxReactForm( { fields, values }, { bindings } )
```

**Comment by foxhound87** [comment]
you can do that in both ways.

**Comment by foxhound87** [comment]
https://foxhound87.github.io/mobx-react-form/docs/api-reference/form-initialization.html

**Comment by liveresume** [comment]
thanks
