### ISSUE TITLE
null converted to "value" 

### ISSUE THREAD

**Issue by liveresume** [foxhound87/mobx-ajv-form#212]
```js
form.$('people').set([
  { name: null },
  { name: null },
  { name: null },
])
```

Results in values being converted from `null` to `"value"`
Shouldn't it (if anything) convert to an empty string?

And there is another bug, only the first object is being copied!

```js
form.values()
{
  people: [{ name: "value" }]
}
```

**Comment by foxhound87** [comment]
What's the field structure?

**Comment by foxhound87** [comment]
Replicated. I will fix it asap.

Anyway the `set()` method is not intended to handle array of fields.

If you have array of fields you can use the `update()` method which will handle add/del of nested fields automatically. (I will clarify this on the docs)

**Comment by liveresume** [comment]
Do you see any reason `set()` shouldn't handle array of fields?

**Comment by liveresume** [comment]
I tried it with update() instead but nothing happens.  form.values() are same as before the call.

**Comment by foxhound87** [comment]
The **set()** method is intended to be used to change the **properties** of existent/selected fields.

The **update()** method  is intended to be used to recreate a fields tree (add/del fields array) and provide new values.  

keep in mind that **update()** accepts only objects, not arrays or other types of values.

In your case you should do:
```javascript
form.update({
  people: [
    { name: null },
    { name: null },
    { name: null },
  ]
});
```

I will test the **update()** method with null values too.

**Comment by liveresume** [comment]
The null value conversion has been fixed, however there are still 2 issues:

```js
form.$('people').set([
    { name: null },
    { name: null },
    { name: null },
  ]);
```

Only sets the first field.

And the same but with update() does not do anything at all!
```js
form.$('people').update([
    { name: null },
    { name: null },
    { name: null },
  ]);
```

However calling it on form works fine:  `form.update({ jobs: res })`

I need it to also work on a selected child, please allow for something like:
`form.$('people').update([...])`

**Comment by foxhound87** [comment]
Yes, the update() method needs a change, I will make it. 

'set()' should fill only the existent fields.
