### ISSUE TITLE
How to set error message when required field is missing?

### ISSUE THREAD

**Issue by liveresume** [foxhound87/mobx-ajv-form#213]
It seems that setting a 'required' rule does not result in an error message when value is missing.
```js
const rules = {
  'name': 'required|string|between:10,75',
}
```

How can I set a custom message?

Since everything else results in an error message, doesn't it make sense to add as package default?

**Comment by foxhound87** [comment]
`required` error is working in my case.

To set custom messages depends on the plugin you are using.
We discussed here: https://github.com/foxhound87/mobx-react-form/issues/49

**Comment by liveresume** [comment]
What message are you getting?  

Try updating to the latest version of validatorjs.  What version are you on?

**Comment by foxhound87** [comment]
"validatorjs": "3.11.0"

The message is "The Username field is required."

**Comment by liveresume** [comment]
looks like the update fixed it
