### ISSUE TITLE
Async validation runs twice

### ISSUE THREAD

**Issue by fridays** [foxhound87/mobx-ajv-form#214]
You can see this in the demo, uncomment the `console.log` statement here:
https://github.com/foxhound87/mobx-react-form-demo/blob/master/src/forms/extension/_.async.js#L12
```
console.log('Loading promised data...');
```

When the value changes, it happens twice:

```
Loading promised data...
Loading promised data...
```

Any ideas?

**Comment by foxhound87** [comment]
Noticed it. I will deepen this issue.

**Comment by foxhound87** [comment]
This is caused from the nature of the [validatorjs](https://github.com/skaterdav85/validatorjs) passes/fails callbacks: 

https://github.com/foxhound87/mobx-react-form/blob/38989a0c292d879be3eaa76e47e065eca6f20cff/src/validators/DVR.js#L89

The package forces to use two calls to the two methods (passes/fails) which is firing the promise 2 time. Maybe I should open an issue on the validatorjs repo.

**Comment by fridays** [comment]
Oh, that's special! I wonder why it's done like this in validatorjs. Would you better recommend one of the other validation packages?

**Comment by foxhound87** [comment]
You can handle async validation with js function (VJF plugin which is enabled by default) and using other DVR rules at the same time if you still want to use validatorjs

**Comment by fridays** [comment]
Thanks. VJF + chriso's validator work great for me.

**Comment by foxhound87** [comment]
Fixed here: https://github.com/foxhound87/mobx-react-form/commit/005d04c7
