### ISSUE TITLE
Pending async validation sets field.error: "validating..."

### ISSUE THREAD

**Issue by fridays** [foxhound87/mobx-ajv-form#215]
During async validation, when there is no result yet, field properties are set to:
```
field.hasError: true
field.error: "validating..."
```
That results in flashing error messages:

![mobx-form-async](https://mobx-form-async-nouwbqldym.now.sh/mobx-form-async.gif)

It would be great if there was another property like `isValidating` for this state, and `hasError` and `error`  only get set when an error happened.

**Comment by foxhound87** [comment]
`hasError` depends on the presence of the error messages.

In the moment that we have the error messages as `"validating..."` then `hasError` will be true.

I will deepen this to make a better behavior, the problem is we need another type of loading indicator in the meantime the async call happen.

**Comment by fridays** [comment]
That would be awesome. I think `field.isValidating` would be a good fit to the existing field properties.

Thanks for this impressive library!

**Comment by foxhound87** [comment]
Implemented in version [1.20](https://github.com/foxhound87/mobx-react-form/releases/tag/v1.20.0)
