### ISSUE TITLE
How to pass form instance to react component

### ISSUE THREAD

**Issue by ghost** [foxhound87/mobx-ajv-form#217]
I'm relative new to React so my experience may be off base.  I was following your example in the README and everything was making sense until "Initialize the form" section.  I couldn't see how MyForm is being used in the following section (Pass form to react component)

https://github.com/foxhound87/mobx-react-form#pass-the-form-to-a-react-component

**Comment by foxhound87** [comment]
"_Pass form to react component_" means you can pass the Instance of the Form as `form` prop of the component shown in the example. 

Assume the form component file is `MyForm.jsx`, this is the usage:

```javascript
import React from 'react';
import MyFormComponent from 'MyForm.jsx' 
import MobxReactForm from 'mobx-react-form';
import { observer } from 'mobx-react';

const myForm = new MobxReactForm();

export default observer(() => (
  <div>
    <MyFormComponent form={myForm} />
  </div>
));
```

You can take a look at the [demo repo](https://github.com/foxhound87/mobx-react-form-demo). 

I know it has a more complex configuration, but you can start from a minimal setup as well and scale as you need.

**Comment by ghost** [comment]
Thanks for the quick response.  I'm overwhelmed by all the pieces in the demo.  If/when I can put together a minimal complete working example I'd be happy to share.

**Comment by foxhound87** [comment]
This issue can now be found on the [FAQ Section](https://foxhound87.github.io/mobx-react-form/docs/faq.html)
