### ISSUE TITLE
Debounce validation

### ISSUE THREAD

**Issue by shanielh** [foxhound87/mobx-ajv-form#219]
Hi.

I would like to debounce validation since it calls the server side in my case.

Is there a way to do that?

Thanks.

**Comment by foxhound87** [comment]
I will implement it.

**Comment by foxhound87** [comment]
Release scheduled for the version `1.20`

Branch: https://github.com/foxhound87/mobx-react-form/tree/debounce

**Comment by foxhound87** [comment]
Implemented in version [1.20](https://github.com/foxhound87/mobx-react-form/releases/tag/v1.20.0)

**Comment by mwarger** [comment]
@foxhound87 - I updated to this and I'm getting an error that says setTimeout is not defined.  I haven't yet looked into why this is happening.

```
ReferenceError: setTimeout is not defined
    at leadingEdge (:103:15) ->     timerId = setTimeout(timerExpired, wait);
    at debounced (:170:16)
    at validate (:268:17)
    at Form (:164:13)
```

**Edit**:   I've confirmed this (at least in my environment) by downgrading to 1.19.2.  Everything worked after purging node_modules and running npm install.  Seems to be a bug in the debounce functionality added with 1.20.0.

**Comment by foxhound87** [comment]
The error is related to the debounce function for validate introduced in the new 1.20 version. 
It seems an error in lodash, but can't understand more from this output. 
Can you show the full error stack trace? Afterwards also your form config could be useful.
Thank You.

**Comment by mwarger** [comment]
I will try and pull that up for you some point soon.  I had to downgrade and move on for now.

FYI - I was not using the debounce functionality and have not looked into how - I am not using anything but basic DVR at the moment.

**Comment by foxhound87** [comment]
The debounced validation has been introduced as default behavior.

**Comment by foxhound87** [comment]
Try to set the `validationDebounceWait` option to `0`. (it should disable debouncing for the moment)

**Comment by mwarger** [comment]
I will give that a try.  Thank you.

**Comment by foxhound87** [comment]
@mwarger any updates on the debounce error?
