### ISSUE TITLE
bug in onAdd/isEvent?

### ISSUE THREAD

**Issue by faassen** [foxhound87/mobx-ajv-form#222]
In Base.js:

```
  onAdd = (e, val = null) => {
    e.preventDefault();
    this.add(utils.isEvent(val) ? null : val);
  };
```

This passes ``val``, which can be ``null``, into ``utils.isEvent``. This reads as follows:

```
const isEvent = (obj) => {
  if (typeof Event === 'undefined') return false;
  return (obj instanceof Event || !_.isNil(obj.target)); // eslint-disable-line
};
```

This returns true if ``obj`` is an instance of the event, or if ``obj.target`` is not nill. But what happens when ``obj`` is ``null``? It would fail because ``null.target`` doesn't work.

I'm trying to debug a bug that seems to hit this, and it only shows up when I do a production build, not during development. I don't know why I'm hitting it now and not before, as I haven't updated any dependencies. It's a mystery. But nonetheless, this looks like a bug, correct?

**Comment by faassen** [comment]
Okay, I *can* now replicate this bug in the development build as well.

I don't get it during development when I do ``onClick(field.onAdd)``, but when I do ``onClick(e => field.onAdd(e)`` it occurs in production builds and dev builds. In some other situation where I
bind ``onAdd`` to another object and then use that I get the error only in production builds and not in development builds.

A workaround is ``e => field.onAdd(e, e)``.

**Comment by mwarger** [comment]
I'm encountering this as well with 1.19.2.  Calling field.onAdd gives me ```Uncaught TypeError: Cannot read property 'target' of null```

@faassen Thank you for the workaround, that did the trick.

**Comment by foxhound87** [comment]
I will deepen this issue and fix it asap.

**Comment by foxhound87** [comment]
Thank you guys. 
Should work now, 
let me know if you encounter other issues.
