### ISSUE TITLE
Props names collision with fields names

### ISSUE THREAD

**Issue by elazer** [foxhound87/mobx-ajv-form#224]
Here's a sample of how I got this error, modifying code from the test and running it to reproduce this error:

```
const fields = [
  'hobbies[]',
  'member.hobbies[]',
  'member.info[]',
  'member.info[].name',
  'member.info[].type',
];

form.$('member.info').add({
  name: 'AAA',
  type: 'BBB',
});
```

Running the test would fail when trying to select .name and .type respectively.
Error: The selected field is not defined (member.info[1].name)
Error: The selected field is not defined (member.info[1].type)

**Comment by foxhound87** [comment]
Still some props name collisions, thank you for reporting this.

**Comment by foxhound87** [comment]
Other reserved props name which cause error: 

'value', 'initial', 'default', 'label', 'placeholder', 'disabled', 'related', 'options', 'bindings', 'type', 'error'

**Comment by elazer** [comment]
Alright, then I will just rename the fields with a prefix or suffix to get it working for now.

**Comment by foxhound87** [comment]
Now should work, please let me know if it's working for you.

Thank You.

**Comment by elazer** [comment]
It is still broken for me, when I try to .add() without values and try to select the field.
Using the same example as above:

```
const fields = [
  'hobbies[]',
  'member.hobbies[]',
  'member.info[]',
  'member.info[].name',
  'member.info[].type',
];

const idx = form.$('member.info').add();
form.$(`member.info[${idx}].name`).sync('AAA');
form.$(`member.info[${idx}].type`).sync('BBB');
```
I get this error.
The selected field is not defined (member.info[1].name)

**Comment by foxhound87** [comment]
Should be index 0 not 1

**Comment by elazer** [comment]
I used the return from .add() as the index. So it does not return the index of the newly added field? I remember doing it this way in previous versions.

**Comment by foxhound87** [comment]
@elazer now is returning only the index if is an array element, otherwise you have to provide the key.
