### ISSUE TITLE
field.container() returns undefined

### ISSUE THREAD

**Issue by faassen** [foxhound87/mobx-ajv-form#226]
I tried to use the ``container`` method to get the container field for a parent, in order to select a sibling field. This didn't work however. I have a nested field, ``foo.0.bar``. ``container()`` on that returns ``undefined``. I tried running it through the debugger, and saw the regular expression do absolutely nothing to the path ``foo.0.bar``, and then pass it into ``select``, which proceeded to return undefined. Both functions seem to behave badly in this case -- I'd expect container() to correctly manipulate the path to ``foo.0`` and for ``select`` to correctly interpret the path ``foo.0.bar`` as an existing field.

See also #202

**Comment by foxhound87** [comment]
This is weird, I'm using [this code](https://runkit.com/foxhound87/57ff732068352c0014597037) to manipulate the field path (which is working pretty well), but the same code doesn't work well in the package, I have to deepen this.

**Comment by foxhound87** [comment]
Now `container()` should work as expected!
Thank You!
