### ISSUE TITLE
observe/observers arguments inconsistency

### ISSUE THREAD

**Issue by faassen** [foxhound87/mobx-ajv-form#227]
I just read https://foxhound87.github.io/mobx-react-form/docs/events/observe.html

At first I was disappointed as ``data`` is not enough for my use case for ``observers`` (using nested fields); I also need the field in order to construct a sibling field, and since it's documented for ``observe`` I tried ``({field}) => `` but it did not work; I got undefined for ``field``.

When I examined ``data`` I saw that it's called ``$field`` however, not ``field``. This is either an inconsistency between ``observe`` and ``observers``, or a documentation issue. I'd prefer it to be ``field`` without ``$`` as I'd like to prefer ``$`` in the public API as much as possible, and it's difficult to explain why it's there and not for ``form`` or ``change``.

The documentation should be clear that ``observers`` gets an object with a ``form``, ``field`` and ``change`` entry, and it should be ``field``, not ``$field`` everywhere.

**Comment by faassen** [comment]
I've now used the observers API and it works nicely, thank you so much!

I do have a new suggestion for ``observers``: to allow users to put in a single object instead of always arrays, to reduce verbosity in the API.  So this:

```
const observers = {
  "foo[].bar": {
      key: "value"
      call: myThing
  }
}
```

I've tried this but it doesn't seem to work -- it just does nothing.

My use case is to listen for ``value`` changes. If this turns out to be the common use case, then we could consider also allowing functions as a non-object argument, so this:

```
const observers = {
   "conditions[].field": myThing
}
```

**Comment by foxhound87** [comment]
The callback doesn't have the field because I wrongly used `$field` as prop and not `field`.

`$field` will be removed in the next 1.21 version.

Anyway it has `form` and `path` and you can select it: `form.$(path)`.

I'm releasing a fix for this.

About using different style for defining the observers, I don't think I will implement it for now, but we can reopen the issue in the future when I implement the mono-repo with external plugins and drivers.

**Comment by foxhound87** [comment]
@faassen with the new update you can pass only the callback, the default key will be `value`.
