### ISSUE TITLE
Demo currently not functional

### ISSUE THREAD

**Issue by carbureted** [foxhound87/mobx-ajv-form#230]
Sends a 502 with an error page.

https://mobx-react-form-demo-kwpocgnjxa.now.sh/

**Comment by foxhound87** [comment]
Hi @carbureted 

Thank you for reporting this.

I updated the link:

https://foxhound87.github.io/mobx-react-form/demo.html

**Comment by mwarger** [comment]
This seems down again.

**Comment by foxhound87** [comment]
re-fixed
