### ISSUE TITLE
Dynamic validation rules

### ISSUE THREAD

**Issue by ghost** [foxhound87/mobx-ajv-form#231]
Consider a form with one dropdown list and one text input.  I want validation rules for the text field to be dynamically assigned depending on the selected dropdown.  Let's say the dropdown has 2 values, Alpha and Numeric.  I want to assign "required|alpha" or "required|numeric" to the text field depending on what is being selected. Any advices would be appreciated.

**Comment by foxhound87** [comment]
Hello @vietnugent 
I made a fix for your case, 
now you can use the `set()` method on the field to edit the validation properties dynamically:

```javascript
    form.$('username')
      .set('rules', 'required|string');
```

**Comment by ghost** [comment]
Can you please provide some context how to use the API?  Something like this?
```
class MyField extends Field {

  // ...

  constructor(data) {
    super(data);

    // ...
  }
}
```

**Comment by foxhound87** [comment]
You don't need to extend the field, you can use set() on the field instance itself when you need it, you should use it for example in the onChange(e) of another field (that's your case I think)

**Comment by foxhound87** [comment]
You can find some good approach reading this article: https://medium.com/@foxhound87/validate-field-onblur-using-props-bindings-in-mobx-react-form-3de48ba00576?source=linkShare-53ff86cf2063-1489143331

It shows the use of onBlur() with validation, but you can use onChange() passing another field to it, then follow the steps about the props bindings.

**Comment by tomgutz** [comment]
Piggy backing from this scenario. I use a Material Autocomplete created the template and binded the disabled and other properties. Aside from turning off/on a certain dependent field, in this instance a text field. I turn off the rules and enablement of that text field for certain value on the autocomplete. When I trace, I can see that the "field.rules" and "field.disabled" is set properly, however, the UI does not reflect it. My expectation is that when its binded the UI follows the value set on the field that is binded. Help! Need some insight on the best way to do this.

**Comment by foxhound87** [comment]
Hi @tomgutz 

First of all check if the component is decorated with the **mobx-react** `observer`.

Otherwise, can you show your code and the debug? Thank You.

**Comment by tomgutz** [comment]
Below is the code. Let me know if it makes sense.
```

//MaterialAutoComplete.js

import React from 'react'
import { observer } from 'mobx-react'
import AutoComplete from 'material-ui/AutoComplete'

// Validate per character change on the field
const handleAutoCompleteChange = (field, searchText) =>{
    field.set('value', searchText) 
}

export default observer(({
  field,
  placeholder = null,
  fullWidth = false,
  validatingText = 'validating...',
  dataSource = [],
  openOnFocus = true,
  dataSourceConfig = null,
  maxSearchResults = 5,
  onUpdateInput = handleAutoCompleteChange.bind(this, field),
  disabled = false
}) => (
  <div>
    <AutoComplete
      filter={AutoComplete.fuzzyFilter}
      {...field.bind({ 
          placeholder, 
          validatingText, 
          openOnFocus,
          fullWidth,
          maxSearchResults,
          dataSource,
          dataSourceConfig,
          onUpdateInput,
          disabled
        })}
    /><br />
  </div>
))``


//Form.js

import React from 'react';
import { observer } from 'mobx-react';

import MaterialTextField from '../../inputs/MaterialTextField';
import MaterialAutoComplete from '../../inputs/MaterialAutoComplete';
import { commonDataSourceConfig } from '../../common/util'

const handleAutoCompleteChange = (field, depField, searchText) =>{
    field.set('value', searchText) 
    if (searchText === 'Fixed Width'){
      depField.set('rules', '');
      depField.set('disabled', true);
    } else {
      depField.set('rules', 'required');
      depField.set('disabled', false);
    }
}

export default observer(({ form, props }) => (
  <form>
//   ...
    <MaterialAutoComplete 
      field={form.$('dataParserImpl')} 
      openOnFocus={true}
      maxSearchResults={6}
      dataSource={props.metadata.dataParserImpl.values}
      dataSourceConfig={commonDataSourceConfig}
      onUpdateInput={handleAutoCompleteChange.bind(this, form.$('dataParserImpl'), form.$('fieldSize'))}
    />
    <MaterialTextField 
      field={form.$('fieldSize')} 
      />
  </form>
));
```

**Comment by foxhound87** [comment]
@tomgutz When using `bind()` you can pass only the props defined in a **bindings rewriter/template**. 

Using the **default bindings**, other props passed to `bind()` are discarded, so you need to define a custom binding rewriter/template for the custom component (for the `AutoComplete` in your case).

Otherwise, pass the other props to the component like usually with the JSX syntax.

Read more here: https://foxhound87.github.io/mobx-react-form/docs/bindings/custom.html

**Comment by asifsaho** [comment]
@foxhound87 Thank you, I was badly looking for a way to change the validation rule programmatically :)

Also @vietnugent for raising the issue :)
