### ISSUE TITLE
Storing objects in a field?

### ISSUE THREAD

**Issue by nuschk** [foxhound87/mobx-ajv-form#232]
Not so much of an issue, more a question: I'd like to store lists and objects in a field, is that possible?

For example, we have image uploads which always come as `{ uid, caption, url }` object. We have single image uploads (e.g., a profile photo) or lists of uploads (e.g., photos on a blog post), which can be edited (i.e., adding, removing, changing the caption) in a form.

It doesn't work setting the array or object directly in the field. Updates to the field (using `field.set()`) do not trigger a change in the form model.

Should I be using nested fields for this? If so, how would I specify a field containing a list with `{ uid, caption, url }` objects in it, using unified notification?

What does work though is serializing the array or object to JSON and then putting this into the form. This is a bit inconvenient though.

Thanks!

**Comment by foxhound87** [comment]
If you handle a single image you can use the **unified mode**.

```javascript
const fields = [{
  name: 'image',
  fields: [{
    name: 'uuid',
    value: '...',
  }, {
    name: 'caption',
    value: '...',
  }, {
    name: 'url',
    value: '...',
  }],
}];
```

if you need a form with a list of images you need **separated mode**:

```javascript
const fields = [
  'image',
  'image[].uuid',
  'image[].caption',
  'image[].url',
];
```

then you define the `values` object separately.

Can you explain better your issue about "serializing the array or object to JSON" thanks.
What's the "inconvenient" part?

Thank You.

**Comment by nuschk** [comment]
Ah, thanks, will try that (though, for some reason, I like the unified mode better, so I'm a bit sad to be required to use separated mode.. :-), but I will try!). Thanks for your detailed response!

Regarding inconvenient: Well, might also be I'm wrong, but I think I first need parsers for each of those fields:

```
fields = {
    images: {
      label: 'Images',
      parse: value => (value ? JSON.stringify(value) : ''),
      format: value => (value ? JSON.parse(value) : null),
    },
}
```

Second, where I would usually use `form.$('images').value` (to render some preview of the pics), I now need to write `form.$('images').get('value')`, because the formatter isn't used otherwise.

Third, `set()` is not symmetric to `get()`. The latter, I need to feed with the serialized value, so I need to remember to do this:

```
images.set(JSON.stringify(newImages));
```

Thanks again!

**Comment by foxhound87** [comment]
Thank you for the code example

**Comment by bvallant** [comment]
@foxhound87 I'm having somehow a similar problem, also with an image upload component. I've specified the fields the same way you mentioned it in unified mode. After modifying the image in the image upload component I would call something like

    // this.props.field is the "image" field
    this.props.field.onChange({url, caption}) 

This sets `$value` on the field correctly, but `field.value` still returns the initial value. Not sure still if this is the right way to handle it?
Couldn't find any examples on what would we the right way to set the value of a nested field the right way, therefore I'm also not totally sure if calling the `onChange` of the "parent" field would be the right way...

**Comment by foxhound87** [comment]
@lazerscience I think your problem is not related to this issue. Using the built-in `onChange(e)` the first input argument is a `Proxy` object and not a value.  You should set the field value with `set()` for change single field value or `update()` if you need to change more fields or nested fields values at time. In your case:

```javascript
this.props.field.update({ 
   url: 'urlValue',
   caption: 'captionValue',
}); 
```

**Comment by bvallant** [comment]
@foxhound87 Thanks for your quick reply. Tried it but now `value` still returns the initial value while for some reason not known to me yet `$value` turned into an array of undefined values... But if you say that using `update()` would be the way to go I'll try to debug that...

**Comment by foxhound87** [comment]
@lazerscience do not use `$value`, it is only for internal use. use `value` instead.
Anyway if you have undefined values may be a bug or a wrong implementation.
Please provide your custom handler and I will take a look.

**Comment by bvallant** [comment]
Well it's mainly this now as I have stripped it down for debugging:

```js

const fields = [
  {
    name: 'title',
    label: 'Title',
    placeholder: 'Title',
    rules: 'required|string|between:5,125',
  }, 
  {
    name: 'image',
    fields: [
      {
        name: 'url',
        label: 'Image URL',
      },
      {
        name: 'caption',
        label: 'Image Caption',
       }
    ]
  }
]

const form = new MobxReactForm({fields});
// .....
form.update(title: 'Whatever', image: {url: 'http://someurl', caption: ''})

// and in the image upload component
this.props.field.update({url: 'http://someotherurl', caption: 'test'})

console.log(this.props.field.value) // still outputs the initial value

```
Not really sure what can go wrong here anymore, but thank you again for your assistance!

**Comment by foxhound87** [comment]
The first call of `updated()` has wrong argument. Anyway it depends how you used the `update()` method inside the component.

**Comment by bvallant** [comment]
Well what's wrong about it? Don't really see it :)

**Comment by foxhound87** [comment]
`form.update(title: 'Whatever', image: {url: 'http://someurl', caption: ''})` **(your)**
`form.update({ title: 'Whatever', image: { url: 'http://someurl', caption: '' } });` **(correct)**

**Comment by bvallant** [comment]
Oh sorry, that just happened when copying it over to GH... Well i'll try to get it working somehow, but thanks for your help anyways!

**Comment by bvallant** [comment]
Well just as an update: Found out what the problem was... The component with the form was reinitialized for some weird reason which led also re-initializing the form and overwriting the updated value again. Though your hint @foxhound87 with using `update()` for nested fields was quite useful, thanks! :+1:
