### ISSUE TITLE
How to make two form fields dependent on one another?

### ISSUE THREAD

**Issue by zhaoyi0113** [foxhound87/mobx-ajv-form#235]
I have two form fields and one has a dependency on the other. When I update a field value, the other field value need to be changed accordingly. How can I make this dependent between fields?

**Comment by foxhound87** [comment]
You can use [observers](https://foxhound87.github.io/mobx-react-form/docs/events/observe.html) in conjunction with the `set()` method.

```javascript
class MyForm extends MobxReactForm {

  onInit() {
    this.$('fieldOne').observe({
      key: 'value', // can be any field property
      call: () => this.$('fieldTwo').set( ... ), // set new value here
    });
  }
}
```

**Comment by zhaoyi0113** [comment]
I tried to use obervers but it doesn't trigger the call function. Below is my Form class:
```
import MobxReactForm from 'mobx-react-form';

export default class ProfileForm extends MobxReactForm {

  onInit() {
    this.$('hostRadio').observe({
      key: 'value', // can be any field property
      call: ({ form, field, change }) =>{
        console.log('xxxx')
      }, // set new value here
    });
  }


  onSuccess(form) {
    alert('Form is valid! Send the request here.');
    // get field values
    console.log('Form Values!', form.values());
  }

  onError(form) {
    // get all form errors
    console.log('All form errors', form.errors());
    // invalidate the form with a custom error message
    form.invalidate('This is a generic error message!');
  }
}
```

It observes the value of hostRadio field. Below is the hostRadio component. It set the value on `onChange` function. I can see the when I click on the `Radio` button, the value got changed but the call function defined in `ProfileForm ` didn't get called.

```
export default observer(({field}) => (

  <div className={field.name + '-input-content pt-form-group pt-inline '}>
    <div className="input-content">
      <Radio className={field.name + '-radio-input'} {...field.bind()} checked={field.get('value')}
             onChange={()=> field.set('value', !field.get('value')}/>
    </div>
  </div>
));
```

**Comment by foxhound87** [comment]
What is the Radio component?

**Comment by foxhound87** [comment]
What is the Radio component? 
Is it a custom component or is it from a lib?
Can you post its implementation?

Thanks.

**Comment by zhaoyi0113** [comment]
The Radio is a component from `blueprint/Radio`. Below is the code:

`import {Radio} from '@blueprintjs/core';`

You can find it from this link: http://blueprintjs.com/docs/

it is just a wrapper of `<input type="radio">`.

**Comment by foxhound87** [comment]
So I suppose it doesn't work with the built-in `onChange` handler.
If so I can help you to implement it.

**Comment by zhaoyi0113** [comment]
that's would be great. In stead of using build-in `onChange` handler, what is the other way to handle the change?

**Comment by foxhound87** [comment]
There's no other solution than creating a custom handler.

**Comment by zhaoyi0113** [comment]
Do you mean I create a separate handler and then call this handler from the `build-in` handler?

**Comment by foxhound87** [comment]
No, I mean, to create a complete new `onChange` handler dedicated for that particular component.
Then use [bindings](https://foxhound87.github.io/mobx-react-form/docs/bindings/) with `Properties Overwrite` or creating a `Custom Template`.

**Comment by zhaoyi0113** [comment]
Ok that sounds good. Thanks for your help.
