### ISSUE TITLE
How to add more functions on extended Form class

### ISSUE THREAD

**Issue by zhaoyi0113** [foxhound87/mobx-ajv-form#236]
I created a Form class extends from `MobxReactForm` and I am able to extend `onSuccess(form)` and `onError` functions when users click the submit button. I am going to create more buttons on that form and how I can add more functions to support these buttons. As an example, I added below buttons on my form component. The first two works fine but the third one(`form.onTest`) doesn't work well. Is there a way for me to add function dynamically?

```
<button className="pt-button pt-intent-success" type="submit" onClick={form.onSubmit}>Connect</button>
            <button className="pt-button pt-intent-primary" type="button" onClick={form.onReset}>Reset</button>
            <button className="pt-button pt-intent-primary" type="button" onClick={form.onTest}>Test</button>
```

If it doesn't support dynamic function, how can I get the form values in my customized function `onTest`?

**Comment by foxhound87** [comment]
You can do that, but you need to create an event handler and not a simple function, like in [this example](https://github.com/foxhound87/weather-forecast-react-app/blob/26bef3e63b7734ab26b8bf2e91e5b1cd846f16be/src/forms/Search.js#L52) using **autobinding** which usually should take the `Proxy` object in input: 

`onTest = (e) => { ... }` 

You can read more on the [events handlers](https://foxhound87.github.io/mobx-react-form/docs/events/events-handlers.html) on the docs.

**Comment by zhaoyi0113** [comment]
I have tried that as below:

`<button className="pt-button pt-intent-primary" type="button" onClick={form.onTest.bind(form)}>Test</button>`

I have to put `form.onTest.bind(form)` on the `onClick` function in order to access `this` in `onTest` function. Is this correct way to do that? 

I see in your example, you can access the value directly from the `onChange(values)` parameter as below. How did you achieve that? I have tested that without `xxx.bind(form)`, I couldn't access `this` in the function. In addition, the parameter in the function is a Proxy object.

```
onChange = (values) => {
    this.$('search').set('value', values);

   ...
  }
```

**Comment by foxhound87** [comment]
You should be able to access the Form or Field instance using `this` when you define a method inside the class. 

It seems like, when you used the method, maybe you assigned it to a prop of another object, or if you are using React classes take a look at the [autobinding on the docs](https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#autobinding), `bind()` can be avoided in some cases.

The parameter in the function depends on what component you are using it. 
It can change but usually you find a `Proxy` object.

**Comment by zhaoyi0113** [comment]
Yes I got a Proxy object as the parameter. How can I make it to be a real parameters? I have checked your example and you can access the `values` directly in the `onChange` method. I looked into your code but didn't find the right place. How did you make that happen on your code?

**Comment by foxhound87** [comment]
You can get the real value from `Proxy` with `e.target.value`.

The link of the example code shows the using of **autobinding** and it has already the `values` and not the `Proxy` because it is the custom handler of the `react-select` package which is implemented differently.

**Comment by zhaoyi0113** [comment]
That makes sense. Thanks.
