### ISSUE TITLE
Parent does not update

### ISSUE THREAD

**Issue by mxmtsk** [foxhound87/mobx-ajv-form#239]
Hey,

In my Login Component I have the folowing code where I pass a field down to a specific input component. When I type in the input and submit the form, the email field returns undefined although I have a value.

Did I miss something here? Shouldn't the parent get updated with the value?

```
<form onSubmit={form.onSubmit}>
   <Input field={form.$('email')} />
</form>
```

Input.js
```
class Input extends React.Component {
  render() {
    const { field } = this.props;

    return (
      <div>
        <div className={s.field}>
          <input {...field.bind()} />
          <label htmlFor={field.id}>
            {field.label}
          </label>
        </div>
        <p>{field.error}</p>
      </div>
    );
  }
}
```

**Comment by foxhound87** [comment]
Have you decorated all your components with mobx-react observer?

**Comment by mxmtsk** [comment]
Hi @foxhound87,

yes, my Component and the Input Component do have the observer:

```Javascript
export default inject('store')(withStyles(s)(observer(Login)));
```

```Javascript
export default inject('store')(withStyles(s)(observer(Input)));
```

The LoginForm does not have the observer, but doesn't need it anyway right?

```Javascript
export default new LoginForm({ fields }, { plugins });
```

**Comment by foxhound87** [comment]
No need observer on the Form instance

**Comment by mxmtsk** [comment]
So everything is correct the way I set it up?

**Comment by foxhound87** [comment]
It seems ok, I don't know if you are using all the decorators in the correct order (you are using for example also `withStyles`). Try to simplify things using a functional component for the field.

**Comment by mxmtsk** [comment]
Nevermind... I got confused with my own code, thanks for the help :)

**Comment by foxhound87** [comment]
fixed it?

**Comment by pankajparkar** [comment]
@foxhound87 It should have certain sequence, I have ended up with below (`typescript`)

`export default (withStyles as any)(styles)(observer(MyComponent))`
