### ISSUE TITLE
Validating nested field based on another nested field

### ISSUE THREAD

**Issue by il-tmfv** [foxhound87/mobx-ajv-form#242]
Hi!
I have a problem validating one nested field value based on another one (I'm using separated declarations).

For example, lets consider following setup:
```js
const fields = [
  // ...
  'legalEntitiesInfo[].leaveBeginAt',
  'legalEntitiesInfo[].leaveEndAt',
];
```

`leaveBeginAt` and `leaveEndAt` are date stings, so `leaveEndAt` must be after or equal `leaveBeginAt`.

How can I declare `related` and `validate` (VJF) properties for a form constructor in this case?

**Comment by foxhound87** [comment]
I think you can use `.set('related', path)` and `.set('validate', validators)` when new elements are added.

**Comment by il-tmfv** [comment]
Thank you! I'll try it tomorrow.

**Comment by il-tmfv** [comment]
So, I've tried this:
```js
employeesCreateFormState.$(`legalEntitiesInfo[${newTab}].leaveBeginAt`).set('validate',
    shouldBeEarlierOrEqualTo(`legalEntitiesInfo[${newTab}].leaveEndAt`)
);
```
and it doesn't work. 
```js
employeesCreateFormState.$(`legalEntitiesInfo[${newTab}].leaveBeginAt`)
``` 
returns `Field` with null `validators`.

I tried to find a reason for this. And I think I've found.
In `src/shared/Actions.js` there is method `set` in which there is next line of code:
```js
if (_.isObject(data)) this.deepSet($, data, '', true);
```
But, `isObject()` from `lodash` returns `true` for functions and arrays as well.
I tried to fix this by adding this check before `if (_.isObject(data)) this.deepSet($, data, '', true);`
```js 
if (_.isFunction(data) || _.isArray(data)) { 
    _.set(this, `$${$}`, data); 
} else if (_.isObject(data)) { 
    this.deepSet($, data, '', true); 
} else {
    _.set(this, `$${$}`, data);
}
```
and validation started to work.

Please, can you verify this?

**Comment by foxhound87** [comment]
I will take a look asap, thank you.

**Comment by foxhound87** [comment]
I'm trying to replicate your issue but seems to work for me.
Right now editing the code as you suggested will fail 1 test.

**Comment by foxhound87** [comment]
Do you think you can provide a test code?

**Comment by il-tmfv** [comment]
Sorry, it is internal project.
I also noticed failed test. So I tried simplest thing ever (at `tests/data/forms/fixes/form.m.js`):
```js 
this.$('items[0]').set('validate', [() => { console.log('hi'); }]);
console.log(this.$('items[0]').validators);
```

and I see `null` in console when I run tests. And with my "fix" I see there `[Function]`.
Do I miss something? Maybe I misunderstood the way you set validators?

**Comment by il-tmfv** [comment]
If it is not enough I can try to reproduce it in a separate project lately.

**Comment by il-tmfv** [comment]
So, I managed to recreate it in a separate project: https://github.com/il-tmfv/reproduce-mobx-react-form-242

It only works on second, third, etc rows with my "fix". It is normal :)

For a simplicity I changed node_modules version of `Action.js`:
```js
var _isFunction2 = require('lodash/isFunction');
var _isFunction3 = _interopRequireDefault(_isFunction2);

// ********

if ((0, _isFunction3.default)(data) || (0, _isArray3.default)(data)) {(0, _set3.default)(this, '$' + $, data); }
else if ((0, _isObject3.default)(data)) { this.deepSet($, data, '', true); }
else {(0, _set3.default)(this, '$' + $, data);}
```

**Comment by foxhound87** [comment]
@il-tmfv thank you so much. I will fix it asap.

**Comment by il-tmfv** [comment]
Also added 
```js
set('related' /*...*/)
``` 
Again, works with fix only, otherwise `related` Field property equals to `[]`.

**Comment by shnarasi** [comment]
Is this issue resolved?  having the same issue with  1.23.2
Just added this... and getting the following console error..
const related = {
  "distributionCenters[].Email": "distributionCenters[].ConfirmEmail"
};
const validate = {
  "distributionCenters[].ConfirmEmail": [
    isEmail,
    shouldBeEqualTo("distributionCenters[].Email")
  ]
};

export default {
  fields,
  values,
  initials,
  labels,
  placeholders,
  validate,
  related,
  rules
};


Uncaught (in promise) Error: The selected field is not defined (distributionCenters[].Email)

**Comment by foxhound87** [comment]
@shnarasi the `related` **distributionCenters[].ConfirmEmail** should have the array index. Right now is not yet supported the check on multiple nested fields at the same time. I will see if can be implemented.

**Comment by foxhound87** [comment]
@shnarasi see answer in #249
