### ISSUE TITLE
Can't set Field options dynamically after initialization

### ISSUE THREAD

**Issue by dmackerman** [foxhound87/mobx-ajv-form#246]
Is there anyway to change the `options` that we pass into a field dynamically?

We've tried doing:

```js
field.set('options', [{ label: 'Equals', value: 'equals' }, ... ]);
```

`field.set('label')`, etc all work fine. Is there anyway to change options after the Form has been initialized?

Does this have to do with the `set` method check not working properly? https://github.com/foxhound87/mobx-react-form/issues/242

```js
if (_.isObject(data)) this.deepSet($, data, '', true);
```

**Comment by foxhound87** [comment]
Yes, should be related to that issue. 
Thank You for reporting this.
