### ISSUE TITLE
Defining fields using an array of objects and initial values (mixed mode)

### ISSUE THREAD

**Issue by d4rky-pl** [foxhound87/mobx-ajv-form#247]
If I define fields as an object then I cannot pass initials separately because the value is set not to the specified initial but to the object inside fields.

Simple test case to reproduce:

```javascript
const fields = {
  email: {
    label: 'E-mail',
    rules: 'required|email|string'
  }
}

const initials = {
  email: 'test@example.com'
}

class MyForm extends MobxReactForm {}

const form = new MyForm({ fields, initials })
console.log(form.$('email').value) // => {label: "E-mail", rules: "required|email|string"}
```

This works correctly if we specify everything by hand:

```javascript
import MobxReactForm from 'mobx-react-form'

const fields = ['email']
const labels = { email: 'E-mail' }
const rules = { email: 'required|email|string'}
const initials = { email: 'test@example.com' }

class MyForm extends MobxReactForm {}

const form = new MyForm({ fields, labels, rules, initials })
console.log(form.$('email').value) // => test@example.com
```

**Comment by d4rky-pl** [comment]
Apologies for the noise, seems that the starter app I've been using as a base for my application used `1.20.5` version, it seems to be no longer the case in `1.22.2`. I'm closing this issue now.

**Comment by foxhound87** [comment]
Using the **Unified** mode you should set the `initial` prop inside the `fields` object.

But is that configuration now working using the "experimental" **Mixed** mode?

Thank You

**Comment by d4rky-pl** [comment]
Yes, it seems to be working (with the warning about mixed mode in console)

**Comment by d4rky-pl** [comment]
In case someone googles here: using the Unified mode you should set `value` not `initial` prop. Took me a moment to figure this out 😅

**Comment by foxhound87** [comment]
The initial prop should take precedence on value

**Comment by foxhound87** [comment]
@d4rky-pl The `initial` prop behavior is changed and I didn't noticed that because it's not tested yet. I will fix it in the next release. Thank you for reporting this.

**Comment by foxhound87** [comment]
@d4rky-pl The `initial` prop is now handled correctly in [v1.30](https://github.com/foxhound87/mobx-react-form/commit/2807d6f8)
