### ISSUE TITLE
Support for multiple Fields Array Items related validation without index in selector.

### ISSUE THREAD

**Issue by shnarasi** [foxhound87/mobx-ajv-form#249]
Having the same issue with 1.23.2
 Just added this... and getting the following console error..
 const related = {
 "distributionCenters[].Email": "distributionCenters[].ConfirmEmail"
 };
 const validate = {
 "distributionCenters[].ConfirmEmail": [
 isEmail,
 shouldBeEqualTo("distributionCenters[].Email")
 ]
 };

export default {
 fields,
 values,
 initials,
 labels,
 placeholders,
 validate,
 related,
 rules
 };

Uncaught (in promise) Error: The selected field is not defined (distributionCenters[].Email)

**Comment by foxhound87** [comment]
@shnarasi the `related` **distributionCenters[].ConfirmEmail** should have the array index. Right now is not yet supported the check on multiple nested fields at the same time. I will see if can be implemented. The selector needs to select a single field with a specific key/path.

**Comment by foxhound87** [comment]
Closing this issue. 
Discussion continues in #328 
(temporary solution and examples available)
