### ISSUE TITLE
focus() field method or ability to retrieve underlying DOM input reference?

### ISSUE THREAD

**Issue by jayalfredprufrock** [foxhound87/mobx-ajv-form#250]
Would it be possible to add a `focus()` method on form fields? I realize programmatic focusing is possible by using `ref` on the input, but mobx-react-form has literally provided everything else I need so I hate to start pulling in DOM references for this one little piece of functionality that seems to come up quite often.

**Comment by foxhound87** [comment]
Nice to have, I will implement this. Thanks!

**Comment by foxhound87** [comment]
@jayalfredprufrock Released `v1.27.0`. Let me know if it's working properly for you. Note that the `focus` prop is now changed to `focused` and a `field.focus()` method is now available to set focus programmatically.

**Comment by foxhound87** [comment]
Make sure to use the built-in `field.bind()` or manually bind the `autoFocus` Field prop on your input component (or reimplementing [bindings](https://foxhound87.github.io/mobx-react-form/docs/bindings/custom.html)).

**Comment by foxhound87** [comment]
Related #529 #524
