### ISSUE TITLE
flag to prevent certain fields from affecting field 'changed' or isPristine

### ISSUE THREAD

**Issue by mwarger** [foxhound87/mobx-ajv-form#252]
It would be nice to be able to update certain field properties without the field marked as dirty.  Think of being able to set a 'showItem' property on a row to control whether it renders, but otherwise keep the row pristine (that way if you want to grab the dirty items, this row wouldn't qualify).  Currently, changing this property would mark the row field as changed.

I hope this makes sense - let me know if this isn't clear.

**Comment by foxhound87** [comment]
Hmm... not so clear but I assume you are talking about nested fields and some sort of show/hide functionality for some fields.

Which property are you talking about which is changing the `changed`/ `isDirty` / `isPristine` props? I mean, these props changes only if the `value` has changed. Other props doesn't affect them.

If you could provide a simple example would be better.

Thank You.

**Comment by mwarger** [comment]
I will check my code, that could be a problem with how I'm doing things - maybe I'm changing the value and didn't realize it - this would explain it.  I will re-open if necessary.  Thanks.
