### ISSUE TITLE
Empty object added when initializing nested fields

### ISSUE THREAD

**Issue by d4rky-pl** [foxhound87/mobx-ajv-form#253]
<img width="772" alt="screenshot 2017-04-05 09 23 29" src="https://cloud.githubusercontent.com/assets/284395/24694297/a9ed6e34-19e1-11e7-89d1-1a8330388dad.png">

**Comment by foxhound87** [comment]
Thank You for reporting this.

**Comment by IngoValente** [comment]
I have the same issue, and seems that I can’t remove it using the standard del method (ie. using the above example): form.$(‘roles’).del(0)

**Comment by foxhound87** [comment]
@IngoValente I replicated that, thank you. Until I fix it you can do: `form.$('roles').$(0).del();`

**Comment by foxhound87** [comment]
@IngoValente I also noticed that the issue occurs only when doing `del(0)`. Other indexes greater then zero are working correctly, do you confirm it?

**Comment by IngoValente** [comment]
Yes other indexes work as expected. Thanks for the quick response!

**Comment by foxhound87** [comment]
Fixed in [v1.28.0](https://github.com/foxhound87/mobx-react-form/releases/tag/v1.28.0)
