### ISSUE TITLE
Implement showErrors() on Form instance

### ISSUE THREAD

**Issue by sebastian-zarzycki-apzumi** [foxhound87/mobx-ajv-form#254]
There is a form method described in docs - showErrors() - which doesnt seem to be in place. I would actually like to have this, to manually trigger this in specific cases.

**Comment by foxhound87** [comment]
The showErrors() method can be used only on the fields. Cannot be used on the form instance. Are you doing this?

**Comment by sebastian-zarzycki-apzumi** [comment]
This suggests otherwise - https://foxhound87.github.io/mobx-react-form/docs/api-reference/form-methods.html

Why would I do this for particular fields? Or rather - if I can do this on form fields, why not on the form itself? (effectively, toggling it for all fields)

**Comment by foxhound87** [comment]
That's an error on the docs. shouldn't be there. But I can implement it anyway. 

To achieve that now:

form.forEach(field => field.showErrors());

**Comment by foxhound87** [comment]
Fixed in [v1.28.0](https://github.com/foxhound87/mobx-react-form/releases/tag/v1.28.0)

**Comment by sebastian-zarzycki-apzumi** [comment]
Nice, thanks!
