### ISSUE TITLE
HTML properties overwritten

### ISSUE THREAD

**Issue by sebastian-zarzycki-apzumi** [foxhound87/mobx-ajv-form#255]
When using the `<input type="password" {...form.$('username').bind()} />` syntax, the type seems to be overwritten with "text", even though I didn't specify it in form field definitions. It doesn't seem right that form definition overrides the HTML. Am I missing something?

**Comment by foxhound87** [comment]
I think you want this:

<input {...form.$('username').bind({ type: 'password' })} />

**Comment by foxhound87** [comment]
@sebastian-zarzycki-es my suggestion helped?

**Comment by sebastian-zarzycki-apzumi** [comment]
Well, it did, but that wasn't really the question. It's a more convoluted version of specifying type directly in field definition.

My question was: why the newly defined field always have type='text' as default and I have to overwrite it? I would imagine, that if I don't have the type specified, then it shouldn't have any value, thus not overriding my inline html definition.

**Comment by foxhound87** [comment]
The default `type` is `text`. If you need to set the `type` prop as `password` you can do it when defining the fields properties on from initialization, then the `bind()` method will set all the field props on the input component, `type` included.

**Comment by sebastian-zarzycki-apzumi** [comment]
I understand. It's more of a question, whether the type (and other field properties) should default to anything, if they are commonly bound back to html controls. But that's ok, I guess, it's just a design decision.

**Comment by foxhound87** [comment]
Have you read [fields props bindings](https://foxhound87.github.io/mobx-react-form/docs/bindings/) on the docs? Let me know if there is something unclear.

**Comment by sebastian-zarzycki-apzumi** [comment]
I did, yes. But I'm not sure how much related it is to the "problem". If you take a look at - https://foxhound87.github.io/mobx-react-form/docs/api-reference/fields-properties.html - you will see that "text" is the only field that has a default value (at least according to the documentation). It's this discrepancy that sort of irks me. Since type is the mostly commonly defined property for a HTML control, chances that someone will bump into this overwrite are just bigger than average. To me, specifying the type of control in HTML just gives a better visual feedback, than looking to an arbitrary form field definition list, that might even be in different file. 

I think that bind() just shouldn't overwrite what is already there, defined in HTML - to avoid any potential confusions. But that's just me :)

**Comment by foxhound87** [comment]
The current implementation of the bind() method using the E6 spread operator forces the components props to be overwritten by the bind data.

**Comment by foxhound87** [comment]
anyway the packages does not force you to use the `bind()` method. You can pass each props manually to the input. Or if you want to use `bind()` you can create a new [default bindings](https://foxhound87.github.io/mobx-react-form/docs/bindings/default.html#default-rewriter) `rewriter/template` omitting the `type` prop.

**Comment by sebastian-zarzycki-apzumi** [comment]
I know. Like I said, not that big of an issue. Just a surprise that type="text" was a default (rather than no default value). Picking a library just to instantly create your own workarounds for that library is something I want to avoid.

I'll stick to defining type in field definitions.

**Comment by foxhound87** [comment]
furthermore the `bind()` methods accept new props in input, so you don't have to create a `rewriter/template`. So you can just use my initial example.

**Comment by foxhound87** [comment]
You can also create a component like this:

```javascript
const MyTextField = observer(({
  field,
  type = 'text',
  placeholder = null,
  validatingText = 'validating...',
  // define other props and pass them to the bind() method
}) => (
  <MaterialTextField {...field.bind({ type, placeholder, validatingText })} />
));

```

and use it with explicit props definition:

```javascript
<MyTextField type="password" />
```
