### ISSUE TITLE
multiple file input (upload)

### ISSUE THREAD

**Issue by timarney** [foxhound87/mobx-ajv-form#259]
Is there a way to get access to the raw file array i.e. let fileSelected = this.files[0]; from a file input

```
 <input type="file" id="simplefile" />
```
Or even is there a way to get access to event.currentTarget for an onChange event?

I tried using .observe for the on change but I can only get the filename as a value.

**Comment by timarney** [comment]
Looks like onBlur (will work).
```
<input
                {...form.$("myfield").bind()}
                type="file"
                onBlur={e => {
                  console.log(e.currentTarget.files[0]);
                }}
              />
```

I don't think I can use onChange as the browser doesn't let me set the value directly (maybe there's another way).

That said can I get access to the 'raw' values somehow onSubmit?

**Comment by foxhound87** [comment]
Hi @timarney 

Right now the package's Field `value` will handle only 1 file. I will do some researches about it.

@DominikGuzei seems to have used [react-dropzone](https://github.com/okonet/react-dropzone) successfully (see #205). But I don't know if he managed multiple files.

**Comment by timarney** [comment]
Thanks @foxhound87 

For my current use case using onBlur works (single file) ... come to think of it I could probably store a reference to the 'files' value captured from the Blur event for later use submit etc... 

Should work for multiple files as well.

**Comment by foxhound87** [comment]
This setup is working using `onChange` tested on **chrome**:

> SimpleFile.jsx
```javascript
import React from 'react';
import { observer } from 'mobx-react';
import _ from 'lodash';

const onDrop = (field) => (e) => {
  const files = _.map(e.target.files); // workaround to get all files
  field.state.extra({ [field.name]: files }); // set files into extra state
  console.log('files', field.state.extra()); // get files from extra state
};

export default observer(({
  field, multiple = false,
}) => (
  <input
    multiple={multiple}
    {...field.bind({
      value: '',
      type: 'file',
      onChange: onDrop(field),
    })}
  />
));
```

component usage:

```javascript
<SimpleFile field={form.$('myFile')} multiple />
```

`form.state.extra()` can be called everywhere to set or get additional custom form data.
You can use this behavior in the meantime I implement a better solution.

**Comment by timarney** [comment]
Nice @foxhound87 also didn't know about form.state.extra so that's handy.

**Comment by foxhound87** [comment]
@timarney you can also access it from Fields too: `field.sate.extra` access same data, I forgot that :D 

I also updated the example above and it's now more concise without using the form instance into the component.

**Comment by timarney** [comment]
@foxhound87 nice thanks - loving how flexible this is.

**Comment by foxhound87** [comment]
Implemented:
* `onDrop(e)` Event Handler.
* `onDrop` Field Hook.
* `file` Field Prop.

Also some new example are added to the demo repo:

* [Simple File Input](https://github.com/foxhound87/mobx-react-form-demo/blob/80fb85346ffdd02abd2993c9c5c59070d7027a69/src/components/inputs/SimpleFile.jsx)
* [DropZone](https://github.com/foxhound87/mobx-react-form-demo/blob/80fb85346ffdd02abd2993c9c5c59070d7027a69/src/components/inputs/DropZone.jsx)
