### ISSUE TITLE
Ship source code with NPM?

### ISSUE THREAD

**Issue by dmackerman** [foxhound87/mobx-ajv-form#260]
Is there any reason the `src` directory isn't a part of the package? It would make debugging and stepping through code inside the library much easier.

**Comment by foxhound87** [comment]
I will look into that. Right now the source code is transpiled with babel to es5 code which seems the recommended approach. I can enable the "src" directory in the package.json `files` array. But I don't know if and how can be accessed because the default entry point is `"main": "lib/index.js"`

**Comment by dmackerman** [comment]
Thanks. Not sure if the `main` entry matters much, since us using module loaders can just reference the source files directly, right? 

Something like: `import { Form } from '~mobx-react-form/src/blah.js`

**Comment by foxhound87** [comment]
So updating the **files** array in the package.json should be enough, is it ok for your use?

**Comment by foxhound87** [comment]
Added "src"
