### ISSUE TITLE
Not getting initial empty object in array since version 1.24.0

### ISSUE THREAD

**Issue by itaylorweb** [foxhound87/mobx-ajv-form#264]
Fields Definition:
```javascript
export const fields = [
  'clients',
  'clients[].clienttype',
  'clients[].title',
  'clients[].firstname',
  'clients[].surname',
  'clients[].DOB',
  'clients[].address1',
  'clients[].address2',
  'clients[].town_city',
  'clients[].state',
  'clients[].postcode',
  'clients[].tel1',
  'clients[].tel2',
  'clients[].tel3',
  'clients[].tel4',
  'clients[].email',
];
```

In v 1.24.0 when initializing the form I would get an initial client object but since upgrading the clients array is empty?

**Comment by foxhound87** [comment]
maybe can be related to #253 from [v1.28.0](https://github.com/foxhound87/mobx-react-form/releases/tag/v1.28.0)

**Comment by foxhound87** [comment]
Can you elaborate more?

**Comment by itaylorweb** [comment]
If I fix my version to 1.24.0 in package.json then I get an initial client object when the form initialises.
If I use the latest version of mobx-react-form then I dont.  see screen shots.
Working: 1.24:
<img width="950" alt="mobx1_24" src="https://cloud.githubusercontent.com/assets/1579538/25474746/3cdcc7de-2b2c-11e7-9856-a1f0511b287e.png">
Not working: latest
<img width="1246" alt="mobx-latest" src="https://cloud.githubusercontent.com/assets/1579538/25474768/50289c1e-2b2c-11e7-8ee9-739d9d841e13.png">

**Comment by foxhound87** [comment]
I see it in my code

**Comment by foxhound87** [comment]
I think we can close this, please reopen if you see errors ;)
