### ISSUE TITLE
Convert material-ui date object onSuccess

### ISSUE THREAD

**Issue by benjamingeorge** [foxhound87/mobx-ajv-form#268]
When a form is submitted and passed validation, how/where would I convert the date object to a string in the format "yyyy-MM-dd".  I would like to do it at the field level, not the onSuccess of the form. 

I tried following the Field extension method outlined in the docs but I had no success.

**Comment by foxhound87** [comment]
Can you elaborate more about your needs? If you want the field's **value** property to be converted you cannot do this directly because the object is needed by the input component but you should derive it to another prop. This can be done using a mobx **computed** when extending the field class.

**Comment by benjamingeorge** [comment]
Thanks i will look into doing it with a computed value.
