### ISSUE TITLE
field only get the default field value not the updated value

### ISSUE THREAD

**Issue by freedom19920918** [foxhound87/mobx-ajv-form#274]
when we need the field value(not default value,actualIy I  need the updated values in the "compoentWillMount" hook to init my options for "Select" component) to init some functions .The value is always the default form field value that lead to a problem that my UI is not the updated result But the default status. So it's lead to some errors

**Comment by foxhound87** [comment]
If you can show your form code with the component you are using and the data structure you need to update I will help you better. 

If the value is not updating consider to check the onChange event handler

**Comment by foxhound87** [comment]
Please, I cannot help you if you don't elaborate better your issue.
I'm going to close this issue. If you need help feel free to reopen it.
