### ISSUE TITLE
Handling checkboxes

### ISSUE THREAD

**Issue by d4rky-pl** [foxhound87/mobx-ajv-form#275]
Default bindings don't handle checkboxes very well. A checkbox have both `value` and `checked` property but there's no way of passing the latter, only the former.

As a workaround for now we're using `checked={field.value}`.

**Comment by foxhound87** [comment]
Maybe this can be enhanced to avoid the use of `checked={field.value}` on the component. I will look into that.

**Comment by foxhound87** [comment]
With this fix the `checked` prop is handled automatically using `type: 'checkbox'` in the field definitions. 

NOTE: Using `type: 'checkbox'` as `bind()` arguement method is useless because cannot update the **type** prop of the **Field Store** but only of the input component.
