### ISSUE TITLE
dispose() should dispose all the events if no object is given

### ISSUE THREAD

**Issue by sadasant** [foxhound87/mobx-ajv-form#276]
Hi!

It's unfortunate that we have to specify what to dispose. Could we make it so that if nothing is given, everything is disposed?

Thank you so much for the effort put into this project!

**Comment by foxhound87** [comment]
Hi @sadasant 

Thank you for your suggestion, I will implement it!

**Comment by sadasant** [comment]
@foxhound87 thank you! \o/ have a wonderful weekend/week. ✌

**Comment by foxhound87** [comment]
You too!

**Comment by foxhound87** [comment]
I released a fix so you can now use `form.dispose()` without argument to dispose of all observers/interceptors in one shot. It can be used only by the **Form** instance.

Next is to implement to dispose of all by a selected path.

**Comment by sadasant** [comment]
@foxhound87 thank you very much!!!
