### ISSUE TITLE
Cannot dynamically replace rules for entire form

### ISSUE THREAD

**Issue by d4rky-pl** [foxhound87/mobx-ajv-form#277]
Even though it's possible to replace rules for single field with field.set('rules', {}) (as explained in #231), unfortunately running the same on `form` does not work.

If it's by design then it'd be nice if an error message was thrown, instead of being a surprising no-op.

**Comment by d4rky-pl** [comment]
Another thing related to this bug, not sure if it merits separate issue: since it's impossible to replace rules form-wide, it's also impossible to create dynamic rules for `nested[]` fields, or at least I have no idea how to accomplish that

**Comment by foxhound87** [comment]
If you are using the **separated mode** you can pass this to the constructor:

```javascript
const rules = {
  'nested[]': 'required',
};
```

so these rules will be applied to all newly added fields.

OR dynamically using `map()` and `set()`:

```javascript
form.$('nested').map(field => field.set('rules', 'required'));
```

what do you mean for **replace rules form-wide**?
what's your intended behavior?

If I understood correctly, you need to change all fields rules included the nested ones, for this purpose you can use `each()` which will iterate ALL fields and NESTED fields recursively:

```javascript
form.each(field => field.set('rules', 'required'));
```

**Comment by d4rky-pl** [comment]
Yeah, eventually I put the nested rules at the beginning of the process and then added new rules as I went. My use case was a 5-step wizard where after every step the data was included / transformed in the form and the last step submitted it. Every step needed extra validations. I removed the 'back' button so the wizard now only goes one way and I'm adding rather than replacing validation rules but it would still be nice to replace them.

As for the `you can use each()` - the problem is that `each` does not list uninitialized nested fields so I wouldn't be able to add validation rules this way (other than grouping the nested rules, applying them first and then going this way which is what I did eventually but it still feels like hack):

```
const fields = [ 'records[]', 'records[].email' ]
const form = new MobxReactForm({ fields })
form.each(field => console.log(field.path)) // will only print 'records'
```

**Comment by foxhound87** [comment]
So you have same structure on each step and need different rules for same fields? If so you can consider to get Form values of each step and then reinitialize the form with different rules but same values for new steps. It sounds good?

**Comment by d4rky-pl** [comment]
Yeah, that may work, though I won't be able to look into it right now as I already finished and pushed this feature to production 😄

**Comment by foxhound87** [comment]
I think you should consider this behavior, also having different forms states you can persist them and enable the back button for the steps.

**Comment by foxhound87** [comment]
Back to the first question, you can actually set rules or others props from the **Form** Instance if you have nested fields as object (without array) like this:

```javascript
    form.set('rules', {
      club: {
        name: 'required',
        city: 'required',
      },
    });
```

what's your use case and when you expected to see the error message?

Thank You.

**Comment by d4rky-pl** [comment]
I'm on a weeklong vacation right now with no access to laptop or any other same dev environment so when I get back I'll check but I'm pretty sure the last example didn't work for entire form instance and just quietly failed without changing any rules. I will try to make a test case and see if I'm able to reproduce the original issue, sorry for not doing it in the first place :)

**Comment by d4rky-pl** [comment]
All right, so: my use case was already solved with everything we've discussed before. The only issue is with array-based fields, everything else must've been a bug in my own code as I can't seem to reproduce the issue anymore. I'm closing this for now, if I ever run into this problem again I'll reopen.
