### ISSUE TITLE
How to deal with complex/nested property

### ISSUE THREAD

**Issue by leesiongchan** [foxhound87/mobx-ajv-form#28]
What is the practice for dealing with complex/nested property if we have property like below:

``` javascript
const attraction = {
  name: 'A',
  address: {
    country: 'B',
    streetAddress: 'C',
  },
  alternateNames: ['D', 'E', 'F'],
  geo: {
    latitude: 12.3456,
    longitude: 23.4567,
  },
};
```

**Comment by foxhound87** [comment]
This package does not support nested properties yet, but you can accomplish what you need also using flat inputs. It also depends on the input component of your choice.

Generally you can do this:

**set initial state**

``` javascript
const fields = {
  addressStreet: {
    label: 'Address',
    value: attraction.address.streetAddress,
  },
  addressCountry: {
    label: 'Country',
    value: attraction.address.country,
  }
};


const form = new Form({ fields });
```

**get form values**

``` javascript
const values = form.values();

const attraction = {
  ...
  address: {
    country: values.addressCountry,
    streetAddress: values.addressStreet,
  },
  ...
};
```

Which input component are you using for dealing with geolocation data?

**Comment by leesiongchan** [comment]
@foxhound87 See you've been working hard on the nested fields, it looks neat!! Is there any release date on it? Would love to try it out and contribute if found any bugs.

**Comment by foxhound87** [comment]
@leesiongchan you can try it out if you checkout the `nested-fields` branch.

I still have some features to implement (two of which are not so easy).

I'm thinking to release the new version asap (but without these two hard features and release them after when I found a good solution).
