### ISSUE TITLE
Is it possible to set computed values in the schema directly?

### ISSUE THREAD

**Issue by sadasant** [foxhound87/mobx-ajv-form#280]
Hi team!
I'm able to set a computed label, but not a computed placeholder. I'm not sure why this is happening.

**Comment by foxhound87** [comment]
Do you mean using .set('placeholder', ...); ?

This is supposed to work as expected. I will test it.

**Comment by foxhound87** [comment]
Or maybe you mean in the fields definitions? I didn't tested that.

**Comment by sadasant** [comment]
Hi! In the field definitions ✌

**Comment by foxhound87** [comment]
Please, can you show the code of your computed label?

**Comment by foxhound87** [comment]
I'm closing this issue. Feel free to reopen if needed.
