### ISSUE TITLE
Form option property to trim values 

### ISSUE THREAD

**Issue by mdansei** [foxhound87/mobx-ajv-form#283]
Hi there ! 
Could we add an option property to trim form values before validation ?

**Comment by foxhound87** [comment]
Ok, I will implement it.

**Comment by daedalus28** [comment]
@foxhound87 did this ever get implemented?

**Comment by mogadanez** [comment]
Any directions to implement this? maybe some hooks?

**Comment by mogadanez** [comment]
what about such way:

```
const fields = {
  email: {
    label: 'Email',
    rules: 'required|email|string|between:1,150',
    placeholder: 'Email',
    hooks: {
      onChange: (field) => {
        field.value  = field.value.trim()
      },
    }
  }
}
```
is it good enough?

**Comment by foxhound87** [comment]
now are available these form options:
`validateTrimmedValue`
`autoTrimValue`

and the field `trim()` method.
