### ISSUE TITLE
question: Best practise for adding dynamic values to a set of fields

### ISSUE THREAD

**Issue by alexrindo** [foxhound87/mobx-ajv-form#284]
Hi!

We are in the process of adding dynamic values through a fetch call, but haven't been able to add the loaded data into the 'value' property and get it to display in the field. 

What are your recommendations for fetching some of the field properties from a server side location?

**Comment by foxhound87** [comment]
If you need to update the form values, consider to use the [`.update()` method](https://foxhound87.github.io/mobx-react-form/docs/actions/shared.html#update-the-fields).

For example, using a promise-based request:

```javascript
apicall().then((data) => form.update(data));
```

**Comment by jamhus** [comment]
Where is the right place to use the form.update() method? 
i used it in the beginning of the form 
`export default observer(({ form }) => (
    <form>
        {
            form.update({
                YearOfRegistration: EmployeesStore.employees.YearOfRegistration,
                RegisteredIn: EmployeesStore.employees.RegisteredIn,
                WorkingArea: EmployeesStore.employees.WorkingArea,
                PresciptionNumber: EmployeesStore.employees.PresciptionNumber,
                CurrentEmploymentAndReferences: EmployeesStore.employees.CurrentEmploymentAndReferences,
                ShortCVSummary: EmployeesStore.employees.ShortCVSummary,
                ID: EmployeesStore.employees.RegisterID,
                CV: EmployeesStore.employees.CV,
                ClearedByNationalPractitionersDatabase: EmployeesStore.employees.ClearedByNationalPractitionersDatabase,
                ApprovedFederationOfStateMedicalBoards: EmployeesStore.employees.ApprovedFederationOfStateMedicalBoards,
                PriorEMRKnowledge: EmployeesStore.employees.PriorEMRKnowledge,
                WorkCountries: EmployeesStore.employees.WorkCountries,
                PreferredRegions: EmployeesStore.employees.PreferredRegions
                
            })
        }
        <h2 className="light-red">Position Details</h2>
`
but i always get this message 

Warning: forceUpdate(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.

**Comment by foxhound87** [comment]
React is telling you that the component render method is not a pure function. Where are you using the update() method?

**Comment by jamhus** [comment]
i solved the problem by moving the update method to the constructor, thanks for your help :)
