### ISSUE TITLE
Invalid field.key value in observers/interceptors callback func

### ISSUE THREAD

**Issue by isomoar** [foxhound87/mobx-ajv-form#291]
When I pass `observers` object into form constructor, in callback function I receive the value of field's `name` prop in `key` instead of actual `key` value. For example in here, I expect `field.key` to be equal `0` or `1`, but not `number`:

```js
const observers = {
  'additionalPhones[].number': [{
    key: 'value',
    call: ({ field, change, form }) => {
      console.log(`key: ${field.key}`);
      console.log(`name: ${field.name}`);

      return change;
    }
  }] 
};
```
Prints

```
key: number
name: number
```

v. 1.31.13

**Comment by foxhound87** [comment]
Maybe you need the key of the additionalPhones array, you can do field.container().key

**Comment by isomoar** [comment]
Yeah, this is exactly what I need! Thank you.
