### ISSUE TITLE
Question: Assigning multiple values to the MultiSelect component

### ISSUE THREAD

**Issue by jamhus** [foxhound87/mobx-ajv-form#293]
Hi 
We are having trouble assigning values to the MultiSelect component. 
The following syntax works in the context of an update call: 

```
"WorkCountries": {
             "value": "USA",
             "label": "USA"
      }
this.form.update({ ....
WorkCountries: this.employees.WorkCountries
```
But when we attempt to assign an array with multiple objects the component becomes unresponsive.

```
[{
             "value": "USA",
             "label": "USA"
          }, {
            "value": "Canada",
            "label": "Canada"
 }]
this.form.update({ .....
WorkCountries: this.employees.WorkCountries
```

**Comment by foxhound87** [comment]
The structure of the **Field** `value` depends on the MultiSelect component that you are using.

In your code, I can't see which data you are passing to the `update()` method and I can only suppose that those data structures are the fields definitions...

Consider using a custom `onChange` event handler to handle user input, and use the `extra` field prop to store the select options.

You can find some examples for the multiselect component on the [demo repo](https://github.com/foxhound87/mobx-react-form-demo/)

**Comment by foxhound87** [comment]
@jamhus did you find it useful? Maybe I can help you better if you can elaborate more on your code.

**Comment by jamhus** [comment]
in my code , i have 2 multiselect component, in the first one you select up to three countries , and in the second one you choose several cities from these countries 

```
 <MultiSelect field={form.$('WorkCountries')} onChange={(values) => onChange(values, form.$('PreferredRegions'))} />

   <MultiSelect field={form.$('PreferredRegions')} onChange={(values) => regionsOnChange(values)} />
```

```
const onChange = (values, PreferredRegions ) => {

    let valueArray = []

    if (Array.isArray(values)) {
        values.forEach(value => {
            if (typeof value === "string") {
                valueArray.push(value)
            } else if (typeof value === "object") {
                for (var key in value) {
                    if (key === "value") {
                        valueArray.push(value[key])
                    }
                }
            }
        })
    } else {
        for (let key in values) {
            if (key == "value") {
                valueArray.push(values[key])
            }
        }
    }  
    
   let _states = []

   states.forEach(state => {
       if (valueArray.indexOf(state.country) !== -1) {
         _states.push(...state.states)
     }
   }) 
   setTimeout(function () { PreferredRegions.set('extra', _states) }, 100)
   
}
```

and this is the update() method that i run in my store 

```
 WorkCountries: this.employees.WorkCountries,

 PreferredRegions: this.employees.PreferredRegions

```
and finally , this is the data from my json file 

```
 "WorkCountries": 
            {"value": "USA", "label": "USA"}
          ,

          "PreferredRegions": [
            "newYork",
            "LasVegas"
          ]
```

the problem is that when the data from my json comes with an array (like preferredRegions above)
the component becomes unresponsive and doesn't changes values!

the "WorkCountries" has only one object right now and it works fine , but as soon as i save multiple values , the component stops working

**Comment by foxhound87** [comment]
1. I cannot see how the fields definition and bindings are done. 
2. I don't know which `MultiSelect` component are you using. Consider that a custom input may pass different data structure inside the `onChange` handler.
3. When setting the fields values, they should match a structure compatible with your custom input.
4. Why are you using setTimeout inside the `onChange` handler?
5. Your `onChange` handler does not set the field value, and when and why are you updating using `update()`?
6. Consider to use `set()` to update the field value inside the `onChange` handler instead using `update()`.

**Comment by jamhus** [comment]
1- 
this is the fields definition
```

 WorkCountries: {
            name:'WorkCountries',
            label: 'Countries you want to work in',
            value: '',
            rules: 'required',
            extra: multiCountriesOptions,
        },
        PreferredRegions: {
            name:'PreferredRegions',
            label: 'Preferred regions',
            value: '',
            rules: 'required',
            extra: [],
        },

```

2- the multiselect component im using is the react multiselect in the demo

3-
the reason for using a setTimeout is that i get this error

> forceUpdate(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.

when i try to update the extra field from the onChange 

my onChange value is basically updating the list to give it different cities based on which country i choose

i know it is a little bit complicated but my main issue is when the data comes from the json file , my multiselect stops working

this is where i get the data and bind it to the component


    getData(form) {
        this.form = form;
        axios.get('http://localhost:3000/Employees/').then(res => {    
            res.data.map((field) => {
                field.values.map((value) => {
                    for (let key in value) {                    
                        for (let val in this.employees) {
                           if (key == val) {
                                this.employees[key]= value[key]
                            }
                        }
                    }
                })
            })
            this.updateForm();

        })  
    }

    updateForm() {
        switch (this.form.name) {
            case "Personal Details":
                this.form.update({
                    FirstName: this.employees.FirstName,
                    SurName: this.employees.SurName,
                })
                break;
            case "Position Details":
                this.form.update({
                    YearOfRegistration: this.employees.YearOfRegistration,
                    WorkCountries: this.employees.WorkCountries,
                    PreferredRegions: this.employees.PreferredRegions
                })
                break;
            
            default:
                break;
        }
        
    }

**Comment by foxhound87** [comment]
first of all, make your render method a pure function

**Comment by foxhound87** [comment]
Please, if you need more help, feel free to reopen this issue.
