### ISSUE TITLE
reduce size mobs-react-form use tree-shaking with webpack2

### ISSUE THREAD

**Issue by simonjoom** [foxhound87/mobx-ajv-form#294]
Hello foxhound, 
i used currently your new code of mobx-react-form, i did some adjustment to reduce his size. 
i passed 2 days to try decrease his size.

I'm little lazy to create a new repo so i describe here fast

First i change 
all "import _ from 'lodash'; "

to 
import isUndefined from 'lodash/isUndefined';
import isEmpty from 'lodash/isEmpty';
import isString from 'lodash/isString';
import isInteger from 'lodash/isInteger';
..Etc..

To avoid to import all lodash lib (significally decrease size)

According to webpack2 to use tree-shaking
export default { } is not working for that (webpack2 gave some error on build with that) 

by example 
in src/utils.js (i don't remember all files i changed)

i deleted:
/*
export default {
  props,
  checkObserve,
  checkPropType,
  hasProps,
  allowedProps,
  throwError,
  isPromise,
  isStruct,
  isEmptyArray,
  isArrayOfObjects,
  pathToStruct,
  hasUnifiedProps,
  hasSeparatedProps,
  allowNested,
  parseIntKeys,
  hasIntKeys,
  maxKey,
  makeId,
  $isEvent,
  $hasFiles,
  $isBool,
  $try,
};*/

do add like that

export const $isBool = ($, val) =>
  isBoolean(val) &&
  isBoolean($.target.checked);

export const $try = (...args) => {
};

export const ...

for tree-shaking and babel 
we need to compile with 
 "presets": [
      [
        "es2015",
        {
          "modules": false
        }
      ],

modules is "false"

Certainly if you pass a bit of your time to refactor your code accordlying to tree-shaking rules 
we could have a website faster to  load? 

Thanks for your work
Regards

**Comment by foxhound87** [comment]
Thanks for all your suggestions, I will try that!

**Comment by foxhound87** [comment]
About lodash imports I used `babel-plugin-lodash` which should already do that. But I will try your solution.

**Comment by simonjoom** [comment]
about my lodash solution it's certainly better to use this (more accurate), i use your source code directly , i guess that other developper will do same as me

lodash is not only the big deal, reduce size with webpack2 tree shaking is as well important (all library now try to fit on it :) ) 
by example i updated my 'recompose' lib recently i saw a change of 1000 octet only because they used  tree-shaking rules in their code.  (cf upper code src/utils.js)

Happy that what i suggest will help your project

**Comment by foxhound87** [comment]
Here you can see the new code edited with your suggestions and updated with webpack3  (webpack3 branch):

https://github.com/foxhound87/mobx-react-form/tree/webpack3

the difference when building is very small:

![webpack1](https://user-images.githubusercontent.com/1292494/27751025-aadc31e4-5dda-11e7-85ac-5216c0aa0c47.jpg)
![webpack3](https://user-images.githubusercontent.com/1292494/27751024-aad6ba5c-5dda-11e7-8c1d-5fd0d03dad21.jpg)

I also noticed that changing the lodash imports in that way doesn't change the bundle size.

Related: #58 #75 #124

**Comment by simonjoom** [comment]
yes i saw your change, but the problem is you re still full lodash library imported.
you have to be sure that you have no any more one time
import _ from 'lodash" in one file of your code

check in 
mobx-react-form/src/validators/DVR.js

ps: 
i use in my webpackconf 
  devtool: false,
  // What information should be printed to the console
  stats: {
    colors: true,
    reasons: false,
    hash: false,
    version: false,
    timings: true,
    chunks: true,
    chunkModules: true,
    cached: true,
    cachedAssets: true,
  },

like that you can see more accurately what webpack will bundle


comments:
for webpack 3 i read a post that tree-shaking is not really working so i recommend maybe to test before with webpack2 (as me) and after compare with result with webpack3


Certainly tree-shaking is working only in production mode (NODE_ENV=production), so be sure to check bundle size in production and not in development mode with webpack . (certainly webpack do more work in prod) 


As well you need to rewrite correctly the webpack.conf following webpack2 recommandation
you can see that you have to use 'rules'  
module: {
    rules: [{
      test: /\.jsx?$/,
      exclude: /(node_modules|tests|bower_components)/,
      options: {
    "presets": [
      [
        "es2015",
        {
          "modules": false
        }
      ],
      "stage-0",
      "react"
    ],
    "plugins": [..],
},
      loader: `babel-loader`,
    },

delete  lodash as well in plugins (no need)  because certainly web pack will import all the lib with this line as well
maybe you should to think to refactor code to minimize bundle size, i'm sure a simple user using only one validator (as me) and no extra feature no need all inside the box :)

Regards

**Comment by mwarger** [comment]
As far as I know, you can also do named imports.  i.e. `import { isInteger, isEmpty, isString } from 'lodash'`.  I like this way of doing it because I think it looks cleaner.

**Comment by simonjoom** [comment]
yeah no unfortunately it won't help to reduce size, this way will import all lodash as well normally

**Comment by foxhound87** [comment]
I updated the branch, no difference also installing webpack2.

About the validators, It's on the roadmap, they will be split into different validator drivers packages.

**Comment by simonjoom** [comment]
try to change query to options as me .. query is i think is deprecated for webpack2 (but i not sure) 

 module: {
    rules: [{
      test: /\.jsx?$/,
      exclude: /(node_modules|tests|bower_components)/,
      options: babelConfig, -> //for me babelConfig is the object with babel plugins and presets
      loader: `babel-loader`,
    },

after me i use 
transform-export-extensions 

not add-module-exports .. i  don't know what is doing add-module-exports but if it's doing things bad for tree-shaking ... maybe try transform-export-extensions  instead

 
Hmm i think i found what you cannot see a difference.. you want to bundle in umd , so i think it will create a library 'static' with all your code in the box.

Me i use your source code from my code . 
So when i use one feature of your code, web pack don"t build the code not used in your library in my bundle (thanks the tree-shaking) 
So keep to use export const blablabla 

and not anymore
 export default {
...
}
seems better for now

so only you can see tree-shaking working if you do as me (i think)
compile from a demo example and from the source code of mobx-react-form 
like me add a alias in webpackconf 
  alias: { 
      'mobx-react-form': path.resolve(__dirname, './temp/mobx-react-form/src')
}


if you do not see other difference in output then it was the plugin babel lodash did the things. (i did not use this in my config)  and i was wrong
after tree-shaking was used only in your file utils.js and parser.js 
so it's not a huge difference of bits

just keep that in mind that tree-shaking not working with transform-es2015-modules-commonjs 
and modules:false do that babel not transform in  "commonjs" who is a problem for this optimisation.

yeah to finish this thread , webpack is nice but we need lot of time to test different config before to get a good optimization.

**Comment by simonjoom** [comment]
just updated my comment read upper about library umd in output

**Comment by foxhound87** [comment]
Do you think you can contribute with a PR on the new branch?

**Comment by simonjoom** [comment]
Just to comment about tree-shaking:

I constated that tree shaking cannot work if i use one package (or library already babelyfied ) or if i use directly from the source code.

For me now, to reduce code i use alias of my important lib to the src and let webpack and babel do their work.

By example i use material-ui so i added:
      'material-ui': path.resolve(__dirname, './temp/material-ui-next/src'),

and do not use the normal way. 
If the package of the installer is already builded maybe with others version of web pack, then in the final result i can see lot of function imported never used.

So it's not really relative to your code but more about webpack things

**Comment by darkowic** [comment]
That would be a great improvement. 'mobx-react-form' is huge itself and in addition, it requires the whole lodash which is also a huge library.

**Comment by foxhound87** [comment]
I opted to externalize the lodash lib
