### ISSUE TITLE
Value property is set to an object when omitting some field properties 

### ISSUE THREAD

**Issue by mdansei** [foxhound87/mobx-ajv-form#297]
Hi, I noticed when I omit label, default, placeholder, value, all together this sets the value property 
to an object and I think it's the field definition object, here's an example : 

```
fields: {
    username: {
      rules: 'checkUser|required|string|between:5,15',
      validators: [checkUser],
    },
    email: {
      rules: 'required|email|string|between:5,20',
    }
```

When I log the value property I get this : 
```
Object {rules: "checkUser|required|string|between:5,15"}
Object {rules: "required|email|string|between:5,20"}
```

I don't know if this is considered  as a bug, but I think it's good to set the value property to empty if none of other properties are provided :)

**Comment by foxhound87** [comment]
Thank You for reporting this! Should be fixed now.
Let me know if you encounter other issues.
