### ISSUE TITLE
Can not access validator object with custom vjf directly 

### ISSUE THREAD

**Issue by mdansei** [foxhound87/mobx-ajv-form#298]
Hi, I'm trying to use `validator ` object with my custom `vjf` , but what I get is `undefined` if I type something like this : 
`validator.isEmail(field.value)`

on the other hand this is working : 
` validator.package.isEmail(field.value)`

**Comment by foxhound87** [comment]
Thank you for reporting this.

**Comment by foxhound87** [comment]
Made some test and it's working in my case using validator v8.

If you can provide your packages versions or a [CodeSandbox](https://codesandbox.io/) would be better for me to help you. 

Thank you.
