### ISSUE TITLE
how to use a observer inside the form validationHandlers

### ISSUE THREAD

**Issue by Marinolinderhof** [foxhound87/mobx-ajv-form#299]
```
class Handlers extends MobxReactForm {
  onSuccess(form) {
    alert('Form is valid! Send the request here.');
    // get field values
    console.log('this.props:', this.props);
    console.log('Form Values!', form.values());
  }

  onError(form) {
    // get all form errors
    console.log('All form errors', form.errors());
    // invalidate the form with a custom error message
    form.invalidate('This is a generic error message!');
  }
}
```
and now i want to do something like 
``` export default inject({store})( observer(new Handlers({ fields }, { plugins })) );``` 

But that doesn't work, what i'm i missing?

**Comment by foxhound87** [comment]
It seems you are trying to use the Form instance as a react component decorated with the mobx-react functions. The Form cannot be used in that way because it is not a react component, it is a mobx store.

**Comment by Marinolinderhof** [comment]
My bad. you may close this issue. I tried to use the observer to import actions. you can do something like

thanks for your help and the whole mobx-react-form cause i love it.
```
import store from 'store';

const actionAdd = (...values) => store.action(...values);

```

**Comment by foxhound87** [comment]
Thank you! If you need more help, feel free to reopen this issue.
