### ISSUE TITLE
Validate without changing state

### ISSUE THREAD

**Issue by shanielh** [foxhound87/mobx-ajv-form#300]
I would like to validate a form without changing the validation state. The scenario is that I'm "previewing" the output of the form without asking for user permission in every field change, for that I don't want to change the validation state (Errors that was previously should stay, new errors should not be added).

Is there a way to do that right now?

BTW - If you want I can pull request :+1:

**Comment by foxhound87** [comment]
Thank you for the PR. Your implementation seems correct, but I think It can be achieved without touching the Validation Plugins files, maybe can be implemented directly into the Field class file.

**Comment by shanielh** [comment]
There is a problem with the implementation. It doesn't send a new "isValid" value which based on the latest validation data. 

I'll be happy to have some guidance if you have alternative implementation idea.

**Comment by foxhound87** [comment]
`isValid` depends on the fields error messages. If the messages are not set, `isValid` is true.

**Comment by foxhound87** [comment]
For this purpose we may introduce a new computed property for the errors messages to be defined on changeState=false.

As the whole Form state is mutating anyway, I think 'changeState' is misleading, something like 'updateErrors' or something similar should be better.

Did you tried the 'showErrors' option, maybe it can be useful for your case?

**Comment by shanielh** [comment]
I did try it. It wasn't useful because setting it to true did show errors on fields that are pristine, and when setting to false - it hide the errors on fields that are not pristine.

**Comment by shanielh** [comment]
@foxhound87 - What do you think I should do? if I don't update the errors, there must be a way to get the new validation status without mutating the form. I was thinking on returning the new validation status from the promises somehow.

**Comment by foxhound87** [comment]
I will take a look as I find some time. But I think the way is to create a new error messages property in the Field class, as I said previously. The flag into the validation plugins will tell which property to use to save the messages, instead of using the regular one. Then, into the Field class, `checkValidationErrors` and `resetValidation` should be reimplemented to check also the new "hidden" error messages property. This should work in theory, or maybe I'm still missing something of your use case :D

**Comment by shanielh** [comment]
@foxhound87 Any news on that? :smile:

**Comment by foxhound87** [comment]
The `resetValidationBeforeValidate` form option has been introduced for this purpose.
But it is experimental
