### ISSUE TITLE
Why separated properties not working in multi select?

### ISSUE THREAD

**Issue by chocholand** [foxhound87/mobx-ajv-form#303]
I made field.
```
const fields = [
  'functionType[]'
]
const values = {
  'functionType': [{ value: 'SEARCH', label: 'search' }]
}

const labels = {
  'functionType': 'Funtion Type'
}
const extra = {
  'functionType': [
    { value: 'SEARCH', label: '검색' },
    { value: 'FILE_SAVE', label: '저장' },
    { value: 'DETAIL', label: '상세보기' }
  ]
}

export default {
  fields,
  values,
  labels,
  extra
}
```

but not working in MultiSelect (mobx-react-form-demo)

```
onChange(data) {
  form.$('functionType').set(data)
}
```
so I add onChange but still not working.

So I changed to united properties. It's working.
```
export default {
  fields: {
    'functionType': {
      label: 'Function Type',
      value: { value: 'SEARCH', label: '검색' },
      rules: 'required',
      extra: [
        { value: 'SEARCH', label: '검색' },
        { value: 'FILE_SAVE', label: '저장' },
        { value: 'PDETAIL', label: '상세보기' }
      ],
    }
  }
}
```

What's the difference between the two?

**Comment by foxhound87** [comment]
In your code, the form structure and values are different: in the **separated mode** you are defining `functionType` as an array, in the **unified mode** is an object. 

The main difference between the two modes is that with the **unified mode** you cannot handle complex nested data structures like nested array of objects.

**Comment by chocholand** [comment]
@foxhound87 yeah, I know.
I'm just wondering why **the separated mode** is not working in MultiSelect (mobx-react-form-demo) and **the unified mode** is working in that.
Do you mean that I have to change to this?
```
const values = {
  'functionType': { value: 'SEARCH', label: 'search' }
}
```

**Comment by foxhound87** [comment]
yes, and 'functionType[]' should be 'functionType'

**Comment by chocholand** [comment]
I changed to this, but not working.

```
const fields = [
  'functionType'
]
const values = {
  'functionType': { value: 'SEARCH', label: 'search' }
}

const labels = {
  'functionType': 'Funtion Type'
}
const extra = {
  'functionType': [
    { value: 'SEARCH', label: '검색' },
    { value: 'FILE_SAVE', label: '저장' },
    { value: 'DETAIL', label: '상세보기' }
  ]
}

export default {
  fields,
  values,
  labels,
  extra
}
```

and I changed too, in mobx-react-form-demo, It's not working too.
```
const fields = [
  'name',
  'revenue',
  'assets',
  'products',
  'productsMultiselect'
];

const values = {
  'name': 'Apple',
  'revenue': '233.715',
  'assets': 305.277,
  'projects': 'iMac',
  'productsMultiselect': { value: 'watch', label: 'Watch' }
};

const labels = {
  'name': 'Company Name',
  'revenue': 'Revenue (Billion $)',
  'assets': 'Assets (Billion $)',
  'projects': 'Products',
  'productsMultiselect': 'Products - Multiselect (react-select)'
};

const extra = {
  'products': productsOptions,
  'productsMultiselect': multiProductsOptions
};

export default {
  fields,
  values,
  labels,
  extra
}
```

I just want to know how it works.

**Comment by foxhound87** [comment]
It should work, I will take a look to check what's wrong.

**Comment by foxhound87** [comment]
I replicated the issue, thank you for reporting this.

You encountered this issue because defining `values` as object/array when using **separated mode** creates nested fields automatically. Instead, that values should be set to a single field.

Until I fix it, you can avoid the `values` in fields definition (at least for that specific field key), instead use `set()` after the form instance is created:

```javascript
const fields = [
  'functionType'
]

const labels = {
  'functionType': 'Funtion Type'
}

const extra = {
  'functionType': [
    { value: 'SEARCH', label: '검색' },
    { value: 'FILE_SAVE', label: '저장' },
    { value: 'DETAIL', label: '상세보기' }
  ]
}

const form = new Form({ fields, labels, extra });

form.$('functionType').set([{ value: 'SEARCH', label: 'search' }]);
```

Eventually, you can use `set()` into the [`onInit()` hook of the Form Instance](https://foxhound87.github.io/mobx-react-form/docs/events/event-hooks.html#execute-code-on-instance-init).

If you use the `onInit()` hook, check which version you are using because the [Event Hooks](https://foxhound87.github.io/mobx-react-form/docs/events/event-hooks.html) implementation is changed, I suggest to upgrade anyway.

If you are using version `1.32`, you can use hooks on fields. 

I tested this configuration on the demo repo (which is using the field hook):

```javascript

new Form({
  fields: [
    'productsMultiselect',
  ],
  extra: {
    productsMultiselect: [
      { value: 'iphone', label: 'iPhone' },
      { value: 'watch', label: 'Watch' },
      { value: 'imac', label: 'iMac' },
    ],
  },
  hooks: {
    productsMultiselect: {
      onInit(field) {
        field.set([{ value: 'watch', label: 'Watch' }]);
      },
    },
  },
});
```

Thank You for your patience.

**Comment by KubaDotVaclavik** [comment]
Your workaround seting value after form initialization has some poor consequence. The form's property `isDirty` is true and calling `onReset` clears the multiselect completely. Is there any other workaround? Unfortunately, the library is unusable for my purpose. I cannot find out how to use it with multiselect and preserve features like form resetting and indicate dirty state.

Thanks for this awesome library.

**Comment by foxhound87** [comment]
@KubaDotVaclavik  You can try also `field.set('initial', ...);`

**Comment by foxhound87** [comment]
Tested with next version in demo repo, when adding the multi select values (as object) it will not create nested field but will be applied as field value
