### ISSUE TITLE
Prevent Validation of "disabled" Fields (validateDisabledFields Option)

### ISSUE THREAD

**Issue by chbdetta** [foxhound87/mobx-ajv-form#304]
Trie `disabled`, but the form still validate the disabled field. The use case is where the input could be hidden by the user, and when they do so, I want to stop validate those hidden fields so the form submission can pass.

**Comment by foxhound87** [comment]
This feature is not yet implemented but in the meantime, you can do it yourself by using [observe](https://foxhound87.github.io/mobx-react-form/docs/events/mobx-events.html) with `disabled` as `key` prop which calls a function that removes and adds the validation rules/functions. 

I will implement it in the future updates. Thank You for your suggestion!

**Comment by chbdetta** [comment]
The feature seems not working as I expect.
Disabled fields are not validated if they are disabled from the start. But if the field is enabled at first, and invalidate by user input. Then if the user disable it, the from validation will not pass. The error from last validation is not gone after field is disabled.

**Comment by foxhound87** [comment]
Try to use `field.resetValidation()` before disabling the field.
If this is working for you, I will release a fix.
Thank You.

**Comment by kapilpipaliya** [comment]
Disabled fields are not validated if they are disabled from the start. any way to enable validation on disabled field?

**Comment by foxhound87** [comment]
@kapilpipaliya maybe you need to set `validateDisabledFields: true` only for some fields:

https://foxhound87.github.io/mobx-react-form/docs/fields/defining-flat-fields/unified-properties.html#define-specific-fields-options

(can be done also in separated mode)

or after the form is initialized:

```javascript
field.set('options', {
   validateDisabledFields: true
});
```
