### ISSUE TITLE
Missing Define or Override Error Messages section in docs

### ISSUE THREAD

**Issue by d4rky-pl** [foxhound87/mobx-ajv-form#305]
The entire section `Define or Override Error Messages` links to non-existent files.

**Comment by foxhound87** [comment]
I'm aware of this, thank you for reporting this anyway. 
This topic was discussed in some past issues if you need it.

**Comment by robksawyer** [comment]
@foxhound87 Does the ability to make custom error messages for existing validation rules exist? If so, can you point me to some information? I'd basically like to add custom messages to the following because the labels are long and they don't make sense being used in the validation message.

Labels:
```
labels: {
        password: 'Your old password',
        newpassword: 'Enter a new password (min 8 characters)',
        newpassword_confirmation: 'Confirm your new password',
      },
```
and 

```
rules: {
        password: 'check_password|required|string',
        newpassword: 'required|string|between:8,50|confirmed',
        newpassword_confirmation: 'required|string|between:8,50',
      },
```

Current validation error message example.
```
The Enter a new password (min 8 characters) confirmation does not match.
```

I'd like it to be.
```
The new password confirmation does not match.
```

**Comment by robksawyer** [comment]
For others, I searched the closed issues and found the following related issues. 

- <https://github.com/foxhound87/mobx-react-form/issues/287>
- <https://github.com/foxhound87/mobx-react-form/issues/49>

The following snippet was most helpful.

Overriding error messages is different depending on which plugin you're using.

- Using Vanilla Javascript Validation Functions (VJF) you can provide it into the function. The function have to return a boolean or an array with [boolean, string], which the second argument is the error message for the [custom functions](https://foxhound87.github.io/mobx-react-form/docs/validation/modes/vjf-custom.html).
- Using Json Schema Validation Keywords (SVK) with [ajv](https://github.com/epoberezkin/ajv) you can provide [error messages for custom keywords](https://github.com/epoberezkin/ajv/issues/161), or [override existing custom messages](https://github.com/epoberezkin/ajv/issues/181).
- Using Declarative Validation Rules (DVR) you can provide custom error messages for [custom registered rules](https://foxhound87.github.io/mobx-react-form/docs/validation/modes/dvr-custom.html), or you can override the default messages when extending the plugin:

```js
const plugins = {
  dvr: {
    package: validatorjs,
    extend: ($validator) => {
      // here we can access the `validatorjs` instance
      var messages = $validator.getMessages('en');
      messages.required = 'Whoops, :attribute field is required.';
      $validator.setMessages('en', messages);
    },
  },
};
```

**Update:** I ended up using the following.
```js
dvr: {
  package: validatorjs,
  extend: ( $validator ) => {
    // @see https://github.com/foxhound87/mobx-react-form/issues/305
    var messages = $validator.getMessages('en');
    messages.confirmed = 'New password confirmation does not match.';
    messages.between = 'Password must be between :min and :max.';
    $validator.setMessages('en', messages);
  }
}
```

**Comment by jonasdumas** [comment]
If you use DVR Validator , **to automatically change the language for all errors**, you can simply do it like this:

```
import validatorjs from 'validatorjs';
import MobxReactForm from 'mobx-react-form';
import { observer } from 'mobx-react';

// For french For example:
validatorjs.useLang('fr');
```

It would be so nice @foxhound87 if  you have the time to copy/past all related solutions from the forum into to the missing documentation. Even if it's drafty because you maybe don't have time, it'll be very helpfull !

**Comment by foxhound87** [comment]
@jonasdumas I will, If you also have some time make a PR on the `docs` branch.

**Comment by foxhound87** [comment]
I removed the broken links in the documentation.
I will not document this since each package has its own implementation.
So it's better to read directly the related documentation.
