### ISSUE TITLE
Inconsistency in .errors()

### ISSUE THREAD

**Issue by d4rky-pl** [foxhound87/mobx-ajv-form#306]
If a field never had a validation error then the return value for `.errors()` on that field is `null`. But if a field had a validation error that was then resolved, the return value is `undefined`.

This tripped me over when I was writing a function to check if any field has any active errors (which is different from `isValid`).

**Comment by foxhound87** [comment]
Thank you for reporting this.

**Comment by foxhound87** [comment]
Made a fix, without errors we will get always `null`.
