### ISSUE TITLE
re/calculating all form fields after one field is changed

### ISSUE THREAD

**Issue by farrukh-abbas** [foxhound87/mobx-ajv-form#307]
Hi,

I'm using the Mobx-react-form nestedField demo example as it is (the same code). I want to be able to run a function in the onchange event of specific fields, the function needs access to all the fields in the form in order to recalculate / update other fields of the form. 

what I want to achieve is a calculator where items are added to a complex form and as soon as the quantity or the price of an item is updated, the total gets recalculated. The form has multiple lists of items. 

How can I do that? 

Much appreciated.

**Comment by foxhound87** [comment]
I suppose you are using an array of fields to handle the items. So you can create a mobx computed property which will iterate all fields and sum all values.

**Comment by farrukh-abbas** [comment]
yes i'm using the construct specified in the nestedFields demo project. here is a sample

```javascript
const fields = {
    'basket.name',
    'basket.totalPrice',
    'basket.totalQuantity',
    'backet.list',
    'basket.list[].name',
    'backet.list[].subTotal',
    'basket.list[].items',
    'basket.list[].items[].name',
    'basket.list[].items[].price',
    'basket.list[].items[].quantity',
}
```

Im also trying to figure out, how would i update the relevant list subtotal meaning how to know the index of the list of which the item was updated.

**Comment by foxhound87** [comment]
I think you can do something like:

```javascript
  @computed get total() {
    let total = 0;

    form.$('fieldsArray')
      .map(field => (total = total + parseFloat(field.value)));

    return total;
  }
````

to get the key of an array element, use the `key` prop.

**Comment by foxhound87** [comment]
If you need to know which is the parent field, use the `container()` method on the current field.

**Comment by farrukh-abbas** [comment]
Great, thanks.

Where should i call this function? sorry, Im a newb with react and mobx.

how will this function be triggered every time any value changes in the form ?

**Comment by foxhound87** [comment]
The mobx computed can be used inside a react component decorated with mobx-react observe. The computed is written as a function but is used like a prop, inside your react component call it without "()", it will act as a property, and will be updated automatically on every state change.

**Comment by farrukh-abbas** [comment]
super thanks alot. Good work with the library.
