### ISSUE TITLE
form.values().path isn't consistent with form.$(path).value

### ISSUE THREAD

**Issue by sadasant** [foxhound87/mobx-ajv-form#310]
Currently (on version 1.31.15), we have a form with nested fields that is getting mixed results when we try to retrieve values. The nested fields are composed of a simple field called `organization` with a fields property, where there's at least one field called `organization.name`, for example. When we try to get the values with form.values(), the result for organization is undefined, however when we try to get `form.$('organization').value`, we get an object representing the nested fields, for our example it would be: `{ name: '' }`.

Thanks for the hard work! Let me know if I can help you with anything.

**Comment by foxhound87** [comment]
Please, when opening this kind of issue it's better to provide at least the code, what's the form structure? I can fix the issue faster if you replicate it providing a github repo or a [codesandbox](https://codesandbox.io/) with comments and logs.

What's `form.values().path` ?

**Comment by foxhound87** [comment]
Any update?

**Comment by foxhound87** [comment]
When trying to replicate your issue I found another bug, I think It's related to yours. 

I'm releasing a fix, please check it out. Thank you.

**Comment by foxhound87** [comment]
I used this fields structure:

https://github.com/foxhound87/mobx-react-form/blob/cbc429076b9cfaf8d49bc2cbd9d3892d1c1c51a0/tests/data/forms/fixes/form.r.js#L3-L8

**Comment by foxhound87** [comment]
@sadasant I had to rollback this fix because I misunderstand your issue. 

Please, can you elaborate it better? Thank You.

**Comment by foxhound87** [comment]
Closing this, I need the form structure to help you. feel free to reopen.
