### ISSUE TITLE
Using .bind() in render

### ISSUE THREAD

**Issue by jcalfee** [foxhound87/mobx-ajv-form#312]
Can this bind be moved outside of the render life-cycle (outside of render)?

https://foxhound87.github.io/mobx-react-form/docs/getting-started.html
```js
<input {...form.$('username').bind()} />
```

If the form is re-rendering outside of mobx then this bind is going to unfortunately ensure react will consider the virtual DOM different and force it to update the real DOM even if the rest of the render did not change.

**Comment by foxhound87** [comment]
What are you trying to achieve? Can you better explain the last sentence?

You can use it to just retrieve the field's properties, or using mobx `autorun` outside the react render method:

```javascript
import { autorun } from 'mobx';

autorun(() => {
  // this function will be executed when an observable prop changes 
  console.log('field changed:', form.$('myField').bind());
});
```

more info on mobx autorun: https://mobx.js.org/refguide/autorun.html

**Comment by jcalfee** [comment]
It is not related to mobx.  It is usually better to avoid using .bind in the render method.  Bind always returns a new object reference.  It causes react to re-render even if the rendered DOM really did not change.  This will cause loss of performance.

**Comment by foxhound87** [comment]
You should provide a test case. I'm using `mobx-react-devtools` to check the rendering and it's all ok. `mobx-react-form` needs `mobx`, it will ensure a better rendering, if you don't use it can depend on your state management implementation. Anyway, you can remove `bind()` and manually pass the props to the components if you prefer.

**Comment by jcalfee** [comment]
I'm not using the lib at the moment so I really can't do a test case.  I think your on the right track though if this is a safe change and something you want.  I'm just giving a tip that I think will help your examples look good.

**Comment by foxhound87** [comment]
Thanks for the suggestion, really appreciated. I'm going to close this issue, feel free to reopen if you need.
