### ISSUE TITLE
data disappear

### ISSUE THREAD

**Issue by dyf2015** [foxhound87/mobx-ajv-form#320]
when i add two row and input "1", the second row will disappear！

![image](https://user-images.githubusercontent.com/16314313/29999361-d4c367d2-9077-11e7-9a76-2475b5e1cea3.png)

**Comment by dyf2015** [comment]
Only input 1 will disappear

**Comment by foxhound87** [comment]
Please, can you replicate your issue on a repo or codesandbox? Thank You

**Comment by foxhound87** [comment]
Please also show your handlers/hooks if you are using custom ones. Are you using the update() method?

**Comment by dyf2015** [comment]
![image](https://user-images.githubusercontent.com/16314313/30002171-1f497d16-90d5-11e7-9a64-1ee19df4c74b.png)

**Comment by dyf2015** [comment]
use update to add row

**Comment by dyf2015** [comment]
![image](https://user-images.githubusercontent.com/16314313/30002182-59989786-90d5-11e7-8e18-df8f0758c20b.png)

**Comment by dyf2015** [comment]
![image](https://user-images.githubusercontent.com/16314313/30002192-a8666e92-90d5-11e7-8a20-3aaeacf3a679.png)

**Comment by dyf2015** [comment]
thank you!

**Comment by dyf2015** [comment]
![image](https://user-images.githubusercontent.com/16314313/30002205-f472c31c-90d5-11e7-8e69-8284adb5fcf5.png)
![image](https://user-images.githubusercontent.com/16314313/30002208-fda208b2-90d5-11e7-9036-d185aa5f759e.png)

**Comment by foxhound87** [comment]
The `update()` method will recreate the fields tree, for this reason, you lost previous fields in your array. 

You should use the [`add()`/`del()`](https://foxhound87.github.io/mobx-react-form/docs/actions/shared.html#add--del) methods to handle the array of fields, or you can wire the built-in [`onAdd`/`onDel` Event Handlers](https://foxhound87.github.io/mobx-react-form/docs/events/event-handlers.html#onadde--ondele) on your buttons, they will do it for you.

**Comment by foxhound87** [comment]
Right now I'm seeing that about the **update()** method the docs say "for example add/del fields array". I forgot to remove it, it was for an older package version. Fixing.

**Comment by dyf2015** [comment]
But this happens when I enter the number 1 in the text box on the second line, and it does not happen when I enter any other character.

When I default two lines of data will occur, and will only occur in the second line.

**Comment by dyf2015** [comment]
When I entered the data is the default two lines, I only triggered the text box onchange, and did not trigger update.

**Comment by dyf2015** [comment]
All other types of fields can be used normally without causing the entire line to disappear.

**Comment by dyf2015** [comment]
This is a strange question, thank you!

**Comment by foxhound87** [comment]
I cannot replicate your issue, it can be related to your code.

**Comment by foxhound87** [comment]
Please replicate your issue on a minimal implementation with codesandbox

**Comment by dyf2015** [comment]
Ok if you have codesandbox url

**Comment by foxhound87** [comment]
https://codesandbox.io/

Thank You

**Comment by dyf2015** [comment]
https://codesandbox.io/s/w246qj0jkk

**Comment by dyf2015** [comment]
Simulation is good, you try to enter the text of the second line 1, you can see the abnormal results.

**Comment by dyf2015** [comment]
![image](https://user-images.githubusercontent.com/16314313/30003384-9c86c9f0-90ee-11e7-9019-18ec2c1e44c0.png)

**Comment by dyf2015** [comment]
I went to sleep, hope this can help you find the problem, thank you!

**Comment by foxhound87** [comment]
Relased a fix, this issue was created by a misunderstanding of #310. I rolled back that fix.
