### ISSUE TITLE
onSubmit stopped work in onClick since 1.32

### ISSUE THREAD

**Issue by aldarund** [foxhound87/mobx-ajv-form#323]
Was working before 1.32
```
   const form = new LoginForm({fields}, {plugins});
class LoginForm extends MobxReactForm {

    async onSuccess(form) {
        const values = form.values();
        try {
            await stores.appState.authenticate(values.email, values.password);
        } catch (e) {
            notification.alert("Invalid Login Or Password");
            return;
        }
        browserHistory.push('/dashboard/');
    }

    onError(form) {
    }
}

 <Button modifier="material" onClick={form.onSubmit}>Login</Button>
```
And nothing happens on click after 1.32

**Comment by foxhound87** [comment]
The Event Hooks & Validation Hooks have been reimplemented in version `1.32`, now you have to create an `hooks` method which returns the hooks (if you are extending the class), or an `hooks` object (if you want to pass them on form initialization).

For more info, take a look at the new documentation pages:
[Validation Hooks - on form initialization](https://foxhound87.github.io/mobx-react-form/docs/events/validation-hooks/constructor.html)
[Validation Hooks - extending the class](https://foxhound87.github.io/mobx-react-form/docs/events/validation-hooks/extending.html)

**Comment by pdfowler** [comment]
@foxhound87 - this is a great change in 1.32 - makes things much more consistent with the initialization of the form. However, I just lost a full afternoon to this and REALLY wish you had followed [semver](http://semver.org) more closely.

> MAJOR version when you make incompatible API changes
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.

This change clearly requires a MAJOR version bump, as you did not provide the backwards-compatibility. 

Other than the technicality - keep up the good work! We love your rfx-stack as a foundation!

**Comment by foxhound87** [comment]
@pdfowler yes I know, I'm sorry for this, for now I suggest to use `~` in your package.json. 
Right now I'm relesing only fixes for the `patch`, and breaking changes for the `minor`.
I will adopt full semver when I decide to release the 2.0.
