### ISSUE TITLE
Init form with values from selected document

### ISSUE THREAD

**Issue by hillmark** [foxhound87/mobx-ajv-form#325]
I have a routing mechanism, which holds a document :id that when parsed updates a `selectedDocument` observable field in my root store with an object reference to that document taken from an array of documents.

When the component at the /document/:id/edit path is rendered (for example), I would like the corresponding form instance to have it's values populated with those of the currently `selectedDocument`, and when the route changes the values to be automatically those of the newly `selectedDocument`.

As a general rule what would be the most suitable way of handling this, so that the form's values were in sync with the current document? I know `form.update()` can be used to update the field values, so perhaps this is more a case of whether there's a preferred approach as to how and where this is done, i.e. in the render method of the component, or outside of it?

Any help would be greatly appreciated.

Many thanks.

**Edit**

In the approach outlined above the form is a singleton whose values are simply updated to reflect the current document, which my not be the correct pattern; perhaps a new instance should be created?

**Comment by foxhound87** [comment]
You can create a new instance or update it, it's up to you. For example, if you have to define the field structure dynamically you can create the instance when you hit the page.

The update of the form instance can be done usually in `componentDidMount` react lifecycle method (or for specific solution depending on your routing system).

**Comment by hillmark** [comment]
That's very useful, thanks.

When I tried: `form.init(values)` on an existing form instance the validation was no longer being applied. Are additional steps required when re-initializing / updating the form instance with new values?

**Comment by hillmark** [comment]
That helps. Thank you.
