### ISSUE TITLE
componentWillUnmount the form settings?

### ISSUE THREAD

**Issue by robksawyer** [foxhound87/mobx-ajv-form#327]
I have the following setup in my `LoginForm.jsx`.
```
@inject('store')
@observer
export default class LoginForm extends Component {

  constructor(props) {
    super(props);
    this.store = this.props.store;
    this.form = new LoginFormSettings(this.props.store);
  }
...
}
```

And I'm wondering if by not currently using `componentWillUnmount` it's causing me issues when switching between my sign up form (setup in a similar manner as above) and login form. The issue is that when I get back to the login form, after visiting sign up form, I get a password validation error (see image below).

What's the proper way to unmount the form in `componentWillUnmount`? Do I need to? Like so...

```
componentWillUnmount() {
    delete this.form;
 }
```

Error when switching from sign up form back to login form.
![screen shot 2017-09-13 at 4 36 46 pm](https://user-images.githubusercontent.com/179419/30405631-d02ed8f0-98a1-11e7-85b2-25b50fc34736.png)

**Comment by robksawyer** [comment]
**Update:** The `delete this.form` doesn't fix the error.

**Comment by foxhound87** [comment]
Hi @robksawyer, maybe the `clear()` method can solve your issue.

**Comment by robksawyer** [comment]
@foxhound87 Thanks, I also found <https://github.com/foxhound87/mobx-react-form/issues/111> helpful.

**Comment by foxhound87** [comment]
Great! Can we close this?

**Comment by robksawyer** [comment]
Yep.
