### ISSUE TITLE
File selection

### ISSUE THREAD

**Issue by cristianfraser** [foxhound87/mobx-ajv-form#329]
Hey, I just started using this library, and I stumbled with buggy behaviour with the file input.

When selecting a file using a form field, no file is selected. This can be seen in the live demo:

https://foxhound87.github.io/mobx-react-form-demo/demo.html

After choosing a file, it just shows "uploading", and when submitting, the values for each field remains empty. Am I doing something wrong or is this not expected behaviour?

**Comment by foxhound87** [comment]
The files are stored into the `files` field prop, not the `value` field prop.

Or using the `onDrop` Event Hook:

> unified field definition example
```javascript
hooks: {
  onDrop: field => console.log('onDrop', field.files),
},
```

**Comment by cristianfraser** [comment]
I see, but still in the demo, after selecting a file to upload, the file input doesn't change from `no file chosen` and the preview only shows 'uploading'. Haven't really tried that the file is uploaded correctly or not yet, but should the input display the file chosen instead of `no file chosen`? Is the demo working as intended?

**Comment by foxhound87** [comment]
The file are listed below the upload button. After selecting the files it still says `no file selected` but it's just a text that needs to be updated in the UI.

**Comment by cristianfraser** [comment]
Is there any way to update the `no file selected` text to display the selected file? Or at least `1 file`?

**Comment by foxhound87** [comment]
Not right now, but you can hide the file input component when the Field's `file` prop has elements, and display another message.

**Comment by cristianfraser** [comment]
Bumping this.

Is a more native behaviour on the roadmap? That is, selecting a file with a file input and have it show its value?

Also, if my file field is `required`, validation will fail because the value of that field is empty. How could I `require` a file input?

What's necessary in order to update the native file input label for when a file is uploaded?

**Comment by foxhound87** [comment]
Sorry for the delay, these enhancements needs to be still implemented. I will look into your needs for the futures updates. Thank you for your patience.

**Comment by cristianfraser** [comment]
Thanks a lot! In the mean time, I just hid the native file input and show in a custom label if there is a file selected or not.

**Comment by iamrodrigo** [comment]
Hey @foxhound87 is there an update about this? What would be the right way to validate the file in case it has to be handled manually?
