### ISSUE TITLE
Live Demo broken

### ISSUE THREAD

**Issue by sakulstra** [foxhound87/mobx-ajv-form#33]
Hello, 
Thanks for this package!

Anyways, for me it seems like the live demo is broken.

Chrome 53, on Ubuntu

**Comment by foxhound87** [comment]
Hi, can you provide more info on the error please?

**Comment by sakulstra** [comment]
When visiting https://mobx-react-form-demo-zgltrpjjwi.now.sh/
1. I can't change the form type - i can click on the select, but nothing happens.
2. I can't edit the form - it simply resets as soon as i defocus
![bugs](https://cloud.githubusercontent.com/assets/4396533/18715500/da15f21e-8019-11e6-986a-dfbfe68d9f31.png)
3. There are some errors in the console e.g. `error: [mobx] An uncaught exception occurred while calculating your computed value, autorun or transformer. Or inside the render() method of an observer based React component. These functions should never throw exceptions as MobX will not always be able to recover from them. Please fix the error reported after this message or enable 'Pause on (caught) exceptions' in your debugger to find the root cause. In: 'CompanyWidgetsForm@562.isValid'. For more details see https://github.com/mobxjs/mobx/issues/462
index.js?a065:1 stacks @ index.js?a065:1r @ index.js?a065:1(anonymous function) @ index.js?a065:1spyReport @ mobx.js?1f6a:1285handleExceptionInDerivation @ mobx.js?1f6a:906ComputedValue.peekUntracked @ mobx.js?1f6a:732ComputedValue.get @ mobx.js?1f6a:748(anonymous function) @ mobx.js?1f6a:240get @ mobx.js?1f6a:2484(anonymous function) @ Form.js?d51e:216tryCatcher @ bluebird.js?d5a9:5236Promise._settlePromiseFromHandler @ bluebird.js?d5a9:3242Promise._settlePromise @ bluebird.js?d5a9:3299Promise._settlePromiseCtx @ bluebird.js?d5a9:3336(anonymous function) @ bluebird.js?d5a9:165(anonymous function) @ bluebird.js?d5a9:4490`
4. The mobx dev tool doesn't work :)

**Comment by foxhound87** [comment]
These errors are already reported on the MobX repo, waiting to find out what they are caused:
https://github.com/mobxjs/mobx/issues/570

If you disable the `mobx-react-devtools` logging (the last icon to the right) and reload the page, all should work as expected.

![da15f21e-8019-11e6-986a-dfbfe68d9f31](https://cloud.githubusercontent.com/assets/1292494/18716280/8c2e705a-801c-11e6-825d-c0996c09c24a.png)

**Comment by foxhound87** [comment]
Fixed. The `html-webpack-plugin` was injecting 2 time the `build.js` into the index page.
