### ISSUE TITLE
Dependent fields

### ISSUE THREAD

**Issue by cristianfraser** [foxhound87/mobx-ajv-form#330]
I'm looking for somehow to make two fields dependent on the value of each other. Reading https://github.com/foxhound87/mobx-react-form/issues/235 gives some hints about setting a new *value* if the bound field is changed. But what I'm looking for is somewhat different:

I have two datepicker fields, using `react-datepicker`. The component can receive `startDate` or `endDate` so that date finally picked is between those two. What I'd like is to be able for the value selected to be passed as a prop to the other field, rather than setting the value of the other field. 

Can't really think of a straightforward way of doing this.

**Comment by foxhound87** [comment]
I think you can just pass the field value to your component, I don't see the issue or maybe you should elaborate it more.

**Comment by foxhound87** [comment]
Did you solved this?

**Comment by cristianfraser** [comment]
I did actually, just had to do some more tinkering with the form.
