### ISSUE TITLE
 How do I pass multiple values ​​when the component changes?

### ISSUE THREAD

**Issue by dyf2015** [foxhound87/mobx-ajv-form#331]
The usual usage：
onChange(value)

I need the usage：
onChange(value,valueSpan,valueObj)

**Comment by foxhound87** [comment]
I think you can use a closure, for example:

```javascript
const onChange = (value, valueSpan, valueObj) => (e) => { ... };
```

**Comment by dyf2015** [comment]
thanks,Can it be bound in two directions?

when component valueSpan changes, it can be synchronized store?
when store valueSpan changes,it can be synchronized component?

**Comment by dyf2015** [comment]
![image](https://user-images.githubusercontent.com/16314313/31698187-c35fe68c-b381-11e7-9cc3-1362cc9e54e3.png)

**Comment by dyf2015** [comment]
thank you,I solved it.
