### ISSUE TITLE
Feature request: field.isValidated & form.isSubmitted

### ISSUE THREAD

**Issue by jcheroske** [foxhound87/mobx-ajv-form#334]
I'd love to see an `isValidated` boolean on the field object, that gets flipped from false to true once the field has been validated for the first time.

I'd also like to have an `isSubmitted` flag on the form object, that shows if the form has ever been submitted.

**Comment by foxhound87** [comment]
I'm sorry but your request is too specific for your case and it can be easily implemented extending the form class.

**Comment by the-noob** [comment]
Slightly piggybacking on this... do you see any issues with implementing `isSubmitted` like
```JavaScript
export default class Form extends MobxReactForm {
  @observable isSubmitted = false;
  
  @action setIsSubmitted = () => {
    this.isSubmitted = true;
  }

  hooks() { // eslint-disable-line
    return {
      onSubmit(instance) {
        // eslint-disable-next-line
        instance.setIsSubmitted();
      },
    };
  }
}
```
And then in my field:

```JavaScript
export default observer(({
  field,
  ...other
}) => {
  return (
    <div style={{ clear: 'both' }}>
      <TextField
        {...field.bind({ ...other, error: field.state.form.isSubmitted && field.hasError, helperText: field.error})} // eslint-disable-line
      />
    </div>
  );
});
```

**Comment by foxhound87** [comment]
I think you should use the action like:

```javascript
  @action setIsSubmitted() {
    this.isSubmitted = true;
  }
```

or


```javascript
  setIsSubmitted = action(() => {
    this.isSubmitted = true;
  });
```

but I think you can achieve that using the built-in packages's options.

**Comment by the-noob** [comment]
Indeed, I was wrongly supplying the initial values/defaults. `field.hasError` works fine.

**Comment by foxhound87** [comment]
The `submitted` & `validated` counters has been implemented.
