### ISSUE TITLE
resetValidationStatusOnSubmit option

### ISSUE THREAD

**Issue by mnstrsound** [foxhound87/mobx-ajv-form#336]
What is the correct way to set disabled property to a field so it doesn't validate? I tried it this way 
```
renderPreviewControls(cn) {
        const { settingsForm } = this.props;
        const preview = settingsForm.$('preview');
        const use = settingsForm.$('preview.use');
        return (
            <fieldset className={ cn('fieldset') }>
                <legend className={ cn('legend') }>
                    { preview.label }
                    <input { ...use.bind({
                        onChange: () => {
                            const useField = settingsForm.$('preview.use');
                            const useFieldValue = useField.get('value');
                            const previewWidthField = settingsForm.$('preview.width');

                            previewWidthField.set('disabled', useFieldValue);
                            previewWidthField.set('rules', useFieldValue ? Rules.preview.width : '');

                            useField.set('value', !useFieldValue);
                        }
                    }) }
                    />
                </legend>
                { this.renderPreviewWidthControl(cn) }
                { this.renderPreviewHeightControl(cn) }
                { this.renderPreviewPostfixControl(cn) }
            </fieldset>
        );
    }
```
or
```
const observers = {
    preview: {
        use: [{
            key: 'value',
            call: ({ form, change }) => {
                form.select('preview.width').set('disabled', !change.newValue);
            }
        }]
    }
}
```
but it’s not working for me. It sets disabled property to the field but it’s still validating.

**Comment by mnstrsound** [comment]
/node_modules/mobx-react-form/lib/Validator.js
<img width="733" alt="2017-10-29 17 25 23" src="https://user-images.githubusercontent.com/11842809/32145277-459abfbe-bcce-11e7-8bb4-1e691887c221.png">
always equals `false`

**Comment by foxhound87** [comment]
The fields are validated on form initialization, so do a `resetValidation()` eventually or disable the `validateOnInit ` form option. Also, check the value that you set to the disabled prop.

I'm not able to replicate your issue. If you can provide a codesandbox would be better.

Thank you.

**Comment by mnstrsound** [comment]
@foxhound87 In my case I don't want to validate "width" and "height" fields if "use" field is not checked. That's why I set "disabled" and "rules" properties to the "width" and "height" fields. 
Please check this [codesandbox](https://codesandbox.io/s/j3vzln8yj5). Can you tell me the best practice to do that?

**Comment by foxhound87** [comment]
Thank you for the codesandbox, I will check it tomorrow.

**Comment by foxhound87** [comment]
Add this inside the observer function just before the set() calls:

```
previewWidthField.resetValidation();
previewHeightField.resetValidation();
```

and should work.

This because the form errors and other validation props are not automatically cleared on each submission.

**Comment by foxhound87** [comment]
https://codesandbox.io/s/x7k67xo38p

**Comment by foxhound87** [comment]
Anyway I mark this issue as `enhancement`. 

I think should be nice to have a form option to do this automatically on submit.

**Comment by foxhound87** [comment]
@mnstrsound can you check if the latest version fixes your issue?

**Comment by foxhound87** [comment]
Not going to implement `resetValidationStatusOnSubmit` option because I introduced `validateOnInit` option which can be set to false to disable validation on submit.

To prevent disabled fields to be validated use `validateDisabledFields: false` option.
Use `retrieveOnlyEnabledFieldsValues: true` if you want to get only enabled values when using `get('value')` or `values()`
