### ISSUE TITLE
field.set(obj) doesn't update form.touched and form.changed

### ISSUE THREAD

**Issue by Vargentum** [foxhound87/mobx-ajv-form#337]
I have a field with an empty object as initial value. I'm using `field.set` to dynamically add some new keys. It works good, but form properties (touched, changed) don't reflect these changes. 

Also, could you provide some examples how to deal with Array and Object values? Current docs don't clarify this enough.

**Comment by foxhound87** [comment]
Right now the `set()` method doesn't change other fields props. 

I need to think more about how to handle this, as the `set()` method doesn't handle specific behavior for each props right now.

About dealing with complex fields structure, did you take a look to the [demo repo](https://github.com/foxhound87/mobx-react-form-demo)?

**Comment by andfk** [comment]
Same issue for me. `form.set('changed', true)` as simple temporal fix is not allowed neither so for now there is not a way to change form state manually? (at least until we find a solution).

**Comment by danielkcz** [comment]
It feels rather intuitive that you need to call `form.select(field).onUpdate(value)` to actually update a `changed` flag. Took me quite some time to figure that out from source code :(

**Comment by foxhound87** [comment]
From version 5.8 field set() will trigger onChange hook on ‘changed’ field prop increment. 

‘touched’ prop is changed only if the user interact with inputs
