### ISSUE TITLE
Help wanted: How to define arrays using unified syntax?

### ISSUE THREAD

**Issue by jcheroske** [foxhound87/mobx-ajv-form#339]
I'm trying to define a form using unified syntax, and can't seem to figure out how to define nested arrays. What is the unified syntax equivalent for the following separated syntax:
```
const fields = [
  'name',
  'addresses',
  'addresses[].street',
  'addresses[].city',
  'addresses[].state'
]
const labels = {
  name: 'Name',
  addresses: 'Addresses',
  'addresses[].street': 'Street',
  'addresses[].city': 'City',
  'addresses[].state': 'State'
}
```
Any help is much appreciated.

**Comment by foxhound87** [comment]
Right now cannot be possible to handle arrays with the `unified` mode.

Follow this issue for more updates: https://github.com/foxhound87/mobx-react-form/issues/197

**Comment by foxhound87** [comment]
I've updated the package introducing the `struct` prop.

Take a look here: 
https://github.com/foxhound87/mobx-react-form/blob/master/tests/data/forms/fixes/form.q1.js

**Comment by eurekin** [comment]
In the form.q1.js, how do I go about adding a validation rule to 'tags[].name' ?
