### ISSUE TITLE
do not throw error when update undefined fields (option strictUpdate: false)

### ISSUE THREAD

**Issue by sakulstra** [foxhound87/mobx-ajv-form#34]
Hello again ;)
When I try to run form.update() I get an `Uncaught TypeError: Cannot read property 'update' of undefined` error... It seems like the package is simply missing the export for update?

Regards,
Lukas

edit: seems like i'm doing sth wrong here as it's even covered in your tests
... ah it actually was my fault. When providing a property inside update() which isn't set inside fields the library errors out. Would it be an option for you to extend https://github.com/foxhound87/mobx-react-form/blob/master/src/Form.js#L189 with a !== check if the field exists before updating it?

**Comment by foxhound87** [comment]
Yes, that's why your are trying to update a form field that does not exist.
It's ok form me to throw an error here. Can you explain me why it shouldn't throw in your case?

Anyway I think to provide a functionality to create new fields also after the form is initialized.
So you can extend it adding input fields dynamically. Maybe you wanted to obtain this?

**Comment by sakulstra** [comment]
In my case i have an object like: 

``` js
const obj = {
  id: "someid",
  name: "somename",
  description: "bla",
  slug: "some slug",
  ...
};
```

returned from the database, but the form only handles name and description. The calculated fields like slug or id are only there because I need them in some other places. For sure I could modify the object, now that I know, but the error message `Cannot read property 'update' of undefined` was kind of misleading.

And I actually think it's not the worst idea to check if the field exists, so you could create different forms and validations with the same data provided from a backend.
Imagine e.g. a userObject

```
const user = {
  id: "someid",
  name: "somename",
  bio: "bla",
  timezone: "some slug",
  privacy: "public",
  ...
};
```

which you could use than to create a form for profile(name,bio) and another e.g. settings(timezone,privacy) without sorting out the relevant field twice(in the schema and the object).

**Comment by foxhound87** [comment]
The error can be handled better, I will improve the error handling anyway. 
Thank you for the suggestion.

The only drawback with your approach is the form will create some unused fields.

I would have rather done something like this using lodash:

``` javascript
const userProfileForm = new Form({
  fields: _.omit(user, ['timezone', 'privacy']);
}); 

const userSettingsForm = new Form({
  fields: _.omit(user, ['name', 'bio']);
}); 

// merge the two forms values
const editedUser = _.merge({
  userProfileForm.values(),
  userSettingsForm.values(),
});

// or single form with original object
const editedUser = _.merge({ 
  user, userSettingForms.values(),
});
```

Anyway this approach is good if you don't have to set labels or rules on each field key.
For the next releases, I will give the possibility to initialize forms values, labels and rules separately.

**Comment by sakulstra** [comment]
Why would the form create unused fields?
My suggestion was:

``` js
update(obj) {
    _.each(obj, (val, key) => {
      if(key in this.fields) this.fields[key].update(val));
   }
  }
```

So fields which doesn't exist just get skipped. Eventually It would be good to do this via an optional parameter, so that it doesn't skip unintentionally.

**Comment by foxhound87** [comment]
Every key you specify into your `fields` object will create a field.

I could do that check but why should you update a not-existing field? 
I already rejected this pull requrest for the same reason: https://github.com/foxhound87/mobx-react-form/pull/10

Maybe I don't get the point. You should provide a real example.

**Comment by sakulstra** [comment]
Okay In our real example we have a real backend which provides data via mobx to a Component:
`ListComponent`, `AddComponent` and `EditComponent`. Both add and edit components include the same `AwesomeForm` Component which utilizes `react-mobx-form`, but edit should prepopulate the form with dynamic data coming from the backend.

My approach was this in the `AwesomeForm`:

```
componentWillReceiveProps(p) {
    if (p.container.doc) {
      form.update(p.container.doc);
  }
}
```

Which fails because container doc.actually includes some computed values which aren't in the form (because they are computed, like e.g. slug).

What I could do now is manipulating the doc inside componentWillReceiveProps to only contain the relevant data in the update call.
This would actually work, but making every change extremely verbose.

**Comment by foxhound87** [comment]
It's ok, thank you for your explanation.
I will implement this with a `strictUpdate` option with default `false`.
Only enabling it will throw an error if the field is undefined, not throwing errors as default behavior.

**Comment by sakulstra** [comment]
Thanks a lot!
That would really help me!

**Comment by sakulstra** [comment]
Looking at the code I don't quiet understand why, but there's a bug inside :/
Assuming my form has a field `name` and i pass the following data to form.update()
`
const obj = { name: "SomeName", sthElse: "-KSHJV0voLMasB-qE-Zj" };
`
everything works.
When i do it the other way around:
`
const obj = { sthElse: "-KSHJV0voLMasB-qE-Zj", name: "SomeName" };
`
there will be no error, but also no update.

Regards,
Lukas
