### ISSUE TITLE
`onDel` calling `onAdd` handler

### ISSUE THREAD

**Issue by the-noob** [foxhound87/mobx-ajv-form#340]
https://github.com/foxhound87/mobx-react-form/blob/3619f926bedd22c6262d0feb646096a9446ce137/src/Base.js#L98-L99

Not sure if it's expected behaviour, was just skimming over the code, but shouldn't that call `onDel` ?

**Comment by foxhound87** [comment]
yes, it's a copy/paste error, I will release a fix asap.
