### ISSUE TITLE
can not set error messages to form.

### ISSUE THREAD

**Issue by kapilpipaliya** [foxhound87/mobx-ajv-form#342]
I can not set errors to the form. the following line dont set errors to the form.
form.set('error', errorsObject);
please fix it, it might a bug.

**Comment by foxhound87** [comment]
`error` is a mobx computed, so you cannot set it in that way, you need to use the `.invalidate('my error message')` method (on a form or field instance). 

If the errors are not yet shown, cosider to call `.showErrors()` just after `.invalidate()`.

https://foxhound87.github.io/mobx-react-form/docs/api-reference/form-methods.html
https://foxhound87.github.io/mobx-react-form/docs/api-reference/fields-methods.html

**Comment by foxhound87** [comment]
Feel free to reply if you need more help.
