### ISSUE TITLE
Input/Output converters with form as Separated Properties

### ISSUE THREAD

**Issue by andfk** [foxhound87/mobx-ajv-form#345]
Seems its possible to define the input/output converters using the unified properties form declaration but is it possible with the separated properties too? In the docs it explains only for unified mode and checking the source code still didn't get from it how its possible. 

I tried with properties like:
`inputs: {} & outputs: {}` or `converters: { input: {} }`..

Can anyone clarify this?
Many thanks

PS: I will PR to the docs for this

**Comment by foxhound87** [comment]
use `input: {}` and `output: {}`, not plurals.

Let me know if you encounter some other issues (the converters will be better reimplemented in future versions).

If you are creating a PR, I appreciate your contribution, thank you!

**Comment by andfk** [comment]
Many thanks @foxhound87! It worked. Added the PR :)
