### ISSUE TITLE
Feat: disable label on Field instance

### ISSUE THREAD

**Issue by eranabir** [foxhound87/mobx-ajv-form#347]
How can i disable the Label Property for Input field ?
if i remove the label its using the name of the field as a label 
thanks!

```javascript
export const formFields = {
    email: {
        name: 'email',
        placeholder: 'email',
        rules: 'required|email|string',
        value: ''
    },
}
```

**Comment by foxhound87** [comment]
You should use empty labels for now. I will fix this in the future releases.

**Comment by kapilpipaliya** [comment]
even if I set empty value to label. still it displays a label.

**Comment by Bobinhos** [comment]
I have the same issue. If not to use label, label becomes a name.
