### ISSUE TITLE
[Question]is form.$validating observable?

### ISSUE THREAD

**Issue by noru** [foxhound87/mobx-ajv-form#348]
Hi,

I'm using async validation in my form and I want to catch the "validating" state and render indicators on DOM.

I tried `<Indicator show={form.$validating} />` but with no luck. Seems it is not an observable.

Currently extends the Form class and declare my own "isValidating" property and action to set the value. But I still have to call it in my VJF manually like this:

```javascript
function check({ field, form }) {
  const msg = `something wrong`
  form.loading()
  return asyncCheck(field.value)
    .then(({ data }) => {
      return [true]
    })
    .catch(() => [false, msg])
    .finally(() => {
      form.loading(false)
    })
}
```

I suppose it must be smarter than this but haven't found what I want in the document. So would you please show me how to do it in the right way? Thanks a lot.

Really appreciated this lib!

**Comment by ekozhura** [comment]
@noru as far as I know, `form.validating` changes its value on a form validation (e.g., when you try to submit a form). When your async validation runs on a field's `onChange` event, `form.validating` isn't affected, instead `field.validating` is.

**Comment by noru** [comment]
@ekozhura thanks for the answer. I've tried and it did work as expected.
