### ISSUE TITLE
performance of mobx-react-form

### ISSUE THREAD

**Issue by simon998yang** [foxhound87/mobx-ajv-form#349]
I just cloned the demo app, and running in development mode playing on register (simple)  page.  I feel there is an obvious delay showing validation message after I tick untick the terms checkbox. 

Considering this is a rather simple page, such delay seems unreasonable. Can this be overcomed? 

This concern really bothers me as I'm planning to use mobx-react-form for very large complex form. 

Looking forward to hearing your advice on the matter.

**Comment by foxhound87** [comment]
The validation is debounced, for this reason you have a default `validationDebounceWait` form option to 250. I think you need to set `validationDebounceWait` to 0  on form or single field instance.

**Comment by simon998yang** [comment]
wow, it does the trick. what a great library. appreciate your timely reply very much!
