### ISSUE TITLE
How to write computed field on nested row?

### ISSUE THREAD

**Issue by kapilpipaliya** [foxhound87/mobx-ajv-form#350]
How to write computed field on nested row?

**Comment by foxhound87** [comment]
can you elaborate it better? thanks

**Comment by kapilpipaliya** [comment]
I have:
  fields: [
    'position',
    'description',
    'diamonds',
    'diamonds[].position',
    'diamonds[].material_id',
    'diamonds[].color_id',
    'diamonds[].pcs'
  ]
I want to add two calculated functions to diamonds array: this fields should not added to form values.
'diamonds[].pointer'
'diamonds[].weight'

**Comment by foxhound87** [comment]
Computed are only available when extending the form/field classes.
Cannot be handled using only the form constructor.
This is a codesandbox example with nested fields:
https://codesandbox.io/s/mobx-react-form--computed-ee5kl1?file=/components/Form.js

**Comment by kapilpipaliya** [comment]
Thanks for your reply.
