### ISSUE TITLE
Field initially validated on blur, then validated on change

### ISSUE THREAD

**Issue by codebury** [foxhound87/mobx-ajv-form#353]
Hi.

It's possible that the initial form validates initially the fields on blur, but afther the first blur, the validation be on change? For example, I start typing in the Password field and no validation is performed. Then I click on Confirm Password but the Password field shows an error. I correct the Password and as I type, the field is being validated.

I've tryed with:

`<input {...this.correoForm.$('CorreoConfirm').bind() } onBlur={this.onBlur} className="form-control" />`

```
onBlur = (field) => {
        var b = this.correoForm.$(field.target.name);

        if (b.state.options.get("validateOnChange") === true) return;

        b.state.options.set({ validateOnChange: true, validateOnBlur: false });
}
```

I think that code overrides default field's onBlur configuration because form never validates the field on blur, only on change.

Thanks.

**Comment by jonasdumas** [comment]
+1

**Comment by luketanner** [comment]
+1

**Comment by marjan2k** [comment]
Won't validateOnChangeAfterInitialBlur work for your case?
https://foxhound87.github.io/mobx-react-form/docs/form/form-options.html

**Comment by codebury** [comment]
Hi @marjan2k!

It has been a while since I opened the issue and this package has had some fixes and enhancements, so I will give a try to your recomendation as soon as posible since I focused on other projects. 

Thanks.

**Comment by foxhound87** [comment]
Closing because `validateOnChangeAfterInitialBlur` has been implemented.

**Comment by foxhound87** [comment]
#477
