### ISSUE TITLE
Labels starting with integers are blank

### ISSUE THREAD

**Issue by antonzy** [foxhound87/mobx-ajv-form#355]
https://github.com/foxhound87/mobx-react-form/blob/de3c09a80fbc78d2a7cf05c5589b223c7776763c/src/parser.js#L33
This code seems to be the cause.

Is there a reason for supporting this behavior?

**Comment by foxhound87** [comment]
@antonzy I introduced it for a reason, but I don't remember why right now. 
I will look if it can be removed.
Thank You.

**Comment by foxhound87** [comment]
To be fixed with #347
