### ISSUE TITLE
How to use mobx-react-form with typescript?

### ISSUE THREAD

**Issue by yvanwangl** [foxhound87/mobx-ajv-form#356]
I love this package so much, i want to use it. But is there any way to use `mobx-react-form` with `typescript`? Tkx

**Comment by foxhound87** [comment]
Typescript is not supported right now, but I think I will implement a runtime type checking like mobx-state-tree

**Comment by yvanwangl** [comment]
@foxhound87 Thanks for your reply, for now , i write form.js file with ts : )

**Comment by novellizator** [comment]
anything new on this front?
