### ISSUE TITLE
hide/show component depending on the status of others

### ISSUE THREAD

**Issue by simon998yang** [foxhound87/mobx-ajv-form#360]
Hi,

Could you kindly point out where I can find some example code, or idea how to implement hide/show component/fieldset depending on other component(s), i.e whether a checkbox is ticked or not, or the value of input? 

Best Regards,

**Comment by foxhound87** [comment]
You can use the following syntax:

`{form.$('myField').myProp && <MyComponent />}`

**Comment by simon998yang** [comment]
you probably get me wrong. I meant, for example, for fields = ['a', 'b'], initially I display 2 input components. but once the lenght of InputA's value is greater than 2 (it could be any condition based on the value of InputA) , InputB need to be removed from UI, further more the value of InputB should be removed from model as well. 

hope I explain myself clear this time. Thanks in advance.

**Comment by ekozhura** [comment]
@simon998yang hi, please take a look at docs https://foxhound87.github.io/mobx-react-form/docs/actions/shared.html#add--del maybe this will help

**Comment by simon998yang** [comment]
Thanks Ekozhura, the doc about add--del seems about add/del item to array. I cannot co-relate it with the question I asked

**Comment by ekozhura** [comment]
@simon998yang I might have the same issue as you - i have a form with optional field and I need somehow dynamically add it to form. Adding to array won't work to me as well. So what I did try, and maybe that will help you to - I used `initField` method on my form:

```
        myForm.initField('email', 'email', {
            label: 'Email',
            type: 'text',
            placeholder: null,
            validators: required
        }, true);
``` 

You can call it in your `onChange` handler to react on user's input.

Though, there is a possibility to do the same with `.add` method: 

```
        myForm.add('', {
            key: 'email',
            label: 'Email',
            type: 'text',
            placeholder: null,
            validators: required
        }, true);
```
validators won't apply for this field, and i haven't figured out why.

Hope this helps you

**Comment by simon998yang** [comment]
@ekozhura  Thanks a lot, it looks like the way to go. I will give it a try when i have time. Please keep me posted if you make validators work.

**Comment by ekozhura** [comment]
@simon998yang from what I see in source code, `add` method uses initField under the hood, but the opts except `key` are ignored. So not only validators aren't applied, even label - check this sandbox https://codesandbox.io/s/rmp41637z4 so maybe you have to use `initField` directly.
