### ISSUE TITLE
Is `onInit` deprecated in the latest version?

### ISSUE THREAD

**Issue by zhaoyi0113** [foxhound87/mobx-ajv-form#361]
I was using `onInit` to do some initial work in my extended form as below. There are some dynamic validation rules added in this method. But I found out that this method is not used in the version 1.32.3. So what is the alternative way to do the initialization work?

```
onInit() {
    // add dynamic validation on each field
    this.$('hostRadio').observe({
      key: 'value',
      call: ({ form, change }) => {
        this.addHostRules(form, change.newValue);
        form.validate();
      },
    });
}
```

**Comment by foxhound87** [comment]
`onInit` is not deprecated, it was moved into the `hooks` object (or method if using a class).

https://foxhound87.github.io/mobx-react-form/docs/events/event-hooks.html#execute-code-on-instance-init

**Comment by zhaoyi0113** [comment]
Oh, thanks.
