### ISSUE TITLE
onDel and onAdd do not update dirty state of collection fields.

### ISSUE THREAD

**Issue by pkfryer** [foxhound87/mobx-ajv-form#367]
With collections as nested fields, removing or adding members to the collection is not recognised by the form as dirty.  The devtools show no change.  isDefault and isPristine are true on the parent form, isDirty is false.  The collection field also shows the same even though the default and value properties are correct and show different content.
This is definitely not correct behaviour for the form.  Is there any work around for this currently whilst a fix is made?

**Comment by IamKritika** [comment]
I was also facing the same problem. Whenever I add a new field to the form with some initial values the onchange hook attached to the form is not working. 

Anyway for now you can try using form.observe till this gets fixes

**Comment by stubar** [comment]
I am getting the same issue.  I've had a read of the form.observe documentation but have no idea how to use it to approach this particular problem.  Could you provide a brief example please.

**Comment by foxhound87** [comment]
Fixed https://github.com/foxhound87/mobx-react-form/commit/c6193d7021f3e1e55ea204247404a19f758425d0
