### ISSUE TITLE
I18N

### ISSUE THREAD

**Issue by 4ware** [foxhound87/mobx-ajv-form#370]
How to activate a different language for errors with DVR (validatorjs)?

Thanks, Kai

**Comment by jmkoomen** [comment]
You can add a file containing:


`import Validator from 'validatorjs';`
`const messages = {`
`  confirmed: 'De :attribute bevestiging komt niet overeen',`
`  email: ':attribute heeft de verkeerde format',`
`  date: ':attribute is geen geldige datum',`
`  integer: ':attribute moet een getal zijn',`
`  min: {`
`    numeric: ':attribute moet minimaal :min zijn',`
`    string: ':attribute moet minimaal :min karakters zijn'`
`  },`
`  max: {`
`    numeric: ':attribute mag niet groter zijn dan :max',`
`    string: ':attribute mag niet meer dan :max karakters zijn'`
`  },`

`  //custom`
`  'contains-uppercase': ':attribute moet een hoofdletter bevatten',`
`  'contains-lowercase': ':attribute moet een kleine letter bevatten',`
`  'contains-number': ':attribute moet een getal bevatten'`
`};`

`Validator.setMessages('nl', messages);`


and then importing it in your own validations file

`import 'translations/validations-nl';`
