### ISSUE TITLE
Example with Defining Nested Fields as Unified Properties

### ISSUE THREAD

**Issue by Gi972** [foxhound87/mobx-ajv-form#372]
hello,

can you help me ?,
I want  use a nested form with the Defining Nested Fields as Unified Properties, but I dont understand  the build of model .

Can you make a example with the nested field demo but with  the Defining Nested Fields as Unified Properties. on codesandox

thanks

**Comment by foxhound87** [comment]
I've updated the package with `struct` prop.

Take a look here: 
https://github.com/foxhound87/mobx-react-form/blob/master/tests/data/forms/fixes/form.q1.js
