### ISSUE TITLE
Feature proposal: Observe the whole form

### ISSUE THREAD

**Issue by prayerslayer** [foxhound87/mobx-ajv-form#379]
This issue is related to best practices with mobx-react-form, maybe I got it wrong and there's a better way to do it. If so, I'm happy to get educated :)

Consider the example from #378 again. It's quite a large form, multiple steps and every step has a couple of inputs. What do I do if I want to externalize the form's state? For instance, because I want to persist to and rehydrate from IndexDB or another kind of session-independent storage, so that partial input doesn't get lost on accidental page refresh.

What I ended up doing was basically this:

~~~ jsx
constructor() {
  this.form = new MobxReactForm(/* ... */);
  ['shipping', 'billing', 'signup'].forEach(field => {
    this.form.observe({
      path: field,
      key: 'value',
      call: ({ change }) => this.props.store.setData(field, change.newValue)
    });
  });
}
~~~

Of course, a shorter and more generic version of the above would be

~~~jsx
this.form.observe({
  key: 'value',
  call: ({ change }) => this.props.store.setData(change.newValue)
});
~~~

However this yields an error. Is there a better way to achieve this?

**Comment by foxhound87** [comment]
In the next releases we now have ‘onChange()’ hook at Form level.

@prayerslayer can we consider this issue solved?
