### ISSUE TITLE
Bug: Updating Buffers in nested field leads to infinite loop (?)

### ISSUE THREAD

**Issue by prayerslayer** [foxhound87/mobx-ajv-form#380]
Situation: I have a couple of file inputs and need to work with the contained data.

~~~jsx
function readFile(file) {
  return new Promise((resolve, reject) => {
    const fileReader = new FileReader();
    fileReader.onload = event => {
      resolve(event.target.result);
    };
    fileReader.onerror = error => {
      reject(error);
    };
    fileReader.readAsArrayBuffer(file);
  });
}

function readFiles(files) {
  return Promise.all(files.map(file => readFile(file)));
}

// in some component
<input
  type="file"
  multiple
  onChange={e => {
    readFiles(Array.from(e.target.files))
    .then(files => this.props.form.update({'files': files}))
  }}/>
~~~

If I select a file, the tab crashes eventually. I recreated the issue in [this codesandbox](https://codesandbox.io/s/8lqq89z4y9). See line 32 in `Form.js`. Interestingly, if I use `form.set('files, files)`, there's no problem.

**Comment by foxhound87** [comment]
This is because with set() you are actually updating the “files” field prop. Instead update() will change the “value” prop of the field (not the “files” prop)
