### ISSUE TITLE
How Do I connect Data from My store to the form before initiating the form ?

### ISSUE THREAD

**Issue by klaussa** [foxhound87/mobx-ajv-form#384]
Hi,

I am having some data stored into a MobxStore. 
I want to put the default values from the MobxStore into the Form. I tried using the extended class and injecting the store ( using no decorators ) and It didn't work.

**Comment by jennasalau** [comment]
You do it when you create the form using the [values](https://foxhound87.github.io/mobx-react-form/docs/form/form-initialization.html) property.

```
const form = new MyForm({values: { firstName: props.myMobXStore.firstName }});
```

**Comment by klaussa** [comment]
@jennasalau 

Totally get that, but I'm doing that in a javacript file, no class at all.  So even if I import the thing, when that file is runned my store is undefined. Where shall the props come from ?

**Comment by jennasalau** [comment]
It sounds like you're not understanding mobx-react rather than mobx-react-form.

You need to inject your store into your component.

```
import React from 'react';
import {inject, observer} from 'mobx-react';
import MyForm './MyForm';

@inject('myMobXStore')
@observer
export default class MyComponent extends React.Component {
     constuctor(props) {
           super(props);
           this.form = new MyForm({values: { firstName: props.myMobXStore.firstName }});
     }

     render() {
          return <form>...</form>
     }
}
```

**Comment by starktech** [comment]
How can I pass a function from my store to be used in the onSuccess hook?  I have a demo setup using the 'Getting Started (class)' demo.  I can't inject my store directly into the form.class.js file, and I can't seem to pass a function from my Parent level component that has the store @inject decoration.  

I'm sure I'm missing something obvious here, any help would be very appreciated!  Thanks

**Comment by klaussa** [comment]
@starktech 

Just import your store in the Form.class.js 

```
Import Store from ...

class YourClass extends Form {
     hooks{
        onSuccess(form) {
           //Use  Store
            Store.method( ... )
           }
     }
}

```
To mention that I treat my stores as singletons so when I import it is already initialised.

**Comment by starktech** [comment]
Wow!  Talk about staring me right in the face!  Thank you so much, saved me a ton of aggravation!

**Comment by klaussa** [comment]
@jennasalau 
On the same note,

How can I take the isDirty property of the form and store it in my own GlobalStore  and use it in another component? 

I've tried this but when I change to another selection, the global store still reflects that the for isDirty:

```
@inject('myMobXStore')
@observer
export default class MySettingsComponent extends React.Component {
     constuctor(props) {
           super(props);
           this.form = new MyForm({values: { firstName: props.myMobXStore.firstName }});
           props.myMobXStore.setmyform(this.form);
     }

 componentWillUnmount(){
        this.props.myMobXStore.setmyform(null);
        this.form.clear()
    }

     render() {
          return <form>...</form>
     }
}

@inject('myMobXStore')
@observer
export default class Header extends React.Component {
	render(){
		My form is: {this.props.myform.isDirty ? 'Show Some button': 'Show another button'}
	}
}

```

Going on another SettingsComponent shows me a good form but the dirty is still there. 



**UPDATE**

Even trying in a hook:
```
 onInit(form){
                myMobXStore.setSettingsForm(form);
 },
```

The form.isDirty is not updated.

**Comment by foxhound87** [comment]
The `isDirty` property is not working as expected in some cases and has to be fixed.

**Comment by foxhound87** [comment]
@klaussa `isDirty/isPristine` has been fixed.
