### ISSUE TITLE
how i can bind default value from my inupt?

### ISSUE THREAD

**Issue by MnMansour** [foxhound87/mobx-ajv-form#385]
I try to pass value from my input i try this way

```
export const Input = observer(({field, value}) => (
  <div>
    <label>
      {field.label}
    </label>
    <input  {...field.bind({value})}/>
    <small className={css.helper}>{field.error}</small>
  </div>
));

```
the value it's come from server after i fetch it in my mobx store and pass it as props to my input component.

now it's work and my input showing value, but when i try to change it it's not change.

**Comment by foxhound87** [comment]
Passing props to the binding method will only override the current field value, not set it in the store.
To update the values of your field you should use the field `field.set('value', ...)` method.
