### ISSUE TITLE
Showing a Loading Indicator

### ISSUE THREAD

**Issue by klaussa** [foxhound87/mobx-ajv-form#388]
Hi,
I was wondering how can I create a boolean inside the Form Class I made that would help me tailor the loading states ? My code looks like this.

```
class Settings extends Form {
	setup(){
		this.loading = false;
	}

	hooks(){
		return{
			onSuccess(form) {
				if(!this.loading){

					this.loading = true // <-At this point the Ui should change but it doesnt.
					
					api.get().then(()=>{
						this.loading = false;

						
					})

				}
			}
		}
	}

}
```

Any suggestion with comes to any approach is welcomed.
Also I don't have decorators enabled in babel. Don't want to eject

**Comment by foxhound87** [comment]
You can use `submitting` and `validating` props, 
this is an example of a loading indicator component:

```javascript
{(form.submitting || form.validating) ?
  <LoadingIndicator /> :
  <button
    type="submit"
    onClick={form.onSubmit}
    disabled={form.submitting}
  >Submit</button>}
```
