### ISSUE TITLE
Required label asterisk, but not in error message

### ISSUE THREAD

**Issue by chrusart** [foxhound87/mobx-ajv-form#389]
I want to add * to field label, but don't want to have it in error message, can I do it somehow?

for example:
label: 'E-mail address *'
error: 'Field E-mail address is required'

**Comment by mapsupetran** [comment]
Just conditionally add an html paragraph right after the field:

<input ... />{ !!field.error && <p>*</p> }

Then style accordingly...

**Comment by marlonsupetran** [comment]
Just conditionally add an html paragraph right after the label:

`<label ... />{ !!field.error && <p>*</p> }`

or

`<label ...>
  E-mail address{ !!field.error && <p>*</p> }
</label>`

...depending on how you structured your form, then style accordingly...
