### ISSUE TITLE
Integrating ajax data with form 

### ISSUE THREAD

**Issue by electricBonfire** [foxhound87/mobx-ajv-form#396]
I am having some issues integrating ajax data with the form. I have not seen any examples of this in the documentation or faqs and am not sure I'm even going about this the right way.

I am using the Class Method for constructing the Form. In my component I am instantiating the Form and rendering with default values. I have a componentDidMount method which should be updating the values of the form but it is not working. In the code below I have replace my ajax call inside componentDidMount and am simply redefining the object which the form values are pulled from.

I'm fairly new to React and Mobx so I may be missing something simple and/or this may be a poor approach. Any advice? Thanks!

    import React, { Component } from 'react';
    import { observable, action } from 'mobx';
    import { inject, observer} from 'mobx-react';
    import { Form as BaseForm } from 'mobx-react-form';
    import validatorjs from 'validatorjs';

    class Payment {
        amount = 0;
    }
    
    class Form extends BaseForm {
        @observable payment = new Payment();

        plugins() {
            return { dvr: validatorjs };
        }
   
        setup(){
            return {
                fields: {
                    amount: {
                        label: 'Amount',
                        placeholder: 'Amount',
                        rules: 'required|string',
                        value: this.payment.amount
                    }
                }
            }
        }
    
        hooks(){
            return {
                onSuccess(form) {
                    alert('Form is valid! Send the request here.');
                    // get field values
                    console.log('Form Values!', form.values());
                },
                onError(form) {
                    alert('Form has errors!');
                    // get all form errors
                    console.log('All form errors', form.errors());
                }
            };
        }
    }
    
    @inject("PaymentStore")
    @observer
    class PaymentForm extends Component {
        form = new Form();
    
        @action
        componentDidMount(){
                this.form.payment = { amount: 10 }
        }
    
        render() {
            return (
                <div>
                    <form onSubmit={this.form.onSubmit}>
                        <label>
                            {this.form.$('amount').label}
                            <input {...this.form.$('amount').bind()} />
                            <p>{this.form.$('amount').error}</p>
                        </label>
                   </form>
                </div>
            )
       }
    }

**Comment by webdeveloperpr** [comment]
I think your issue is related to mine. I maned to get something working check it out.
https://github.com/foxhound87/mobx-react-form/issues/409

**Comment by betancourtl** [comment]
You might need to update the value through the form functions

```javascript
// here is an example
  componentDidMount() {
    const { token } = this.props.match.params;
    const form = this.props.passwordResetForm;

    form
      .$('token')
      .set('value', token);

   // trigger the validations after the update
    form
      .$('token')
      .validate({ showErrors: true });
  }

```

**Comment by foxhound87** [comment]
You can do ajax requests in the event hooks provided by the package
https://foxhound87.github.io/mobx-react-form/docs/events/event-hooks.html

**Comment by foxhound87** [comment]
or the validation hooks as well...
https://foxhound87.github.io/mobx-react-form/docs/events/validation-hooks.html
