### ISSUE TITLE
Soft Delete

### ISSUE THREAD

**Issue by kapilpipaliya** [foxhound87/mobx-ajv-form#398]
I have form with fields:    
fields: [
      'rank',
      'slug',
      'company',
      'gstNo',
      'parentId',
      'contacts',
      'contacts[].rank',
      'contacts[].firstName',
      'contacts[].lastName',
      'contacts[].email',
      'contacts[].phone',
      'contacts[].mobile',
      ],
I want inercept on contacts array, when row is deleted, i want to set field.set('value', {delete: true}) insted of actually deleting a row.
thanks for a great library.

**Comment by kapilpipaliya** [comment]
Please someone reply. Recently issues are not resolved by author in time as he may not have time.

**Comment by foxhound87** [comment]
@kapilpipaliya you can use the `disabled` field prop in conjunction with `retrieveOnlyEnabledFields` form option.

**Comment by kapilpipaliya** [comment]
Thanks, but i want when row is deleted, i want to set field.set('value', {delete: true}) if id key exist in row and hide, else delete row.

**Comment by shrugs** [comment]
@kapilpipaliya just change your delete button to set that property

```

delete = () => {
  this.props.field.$('delete').set(true)
}

<button onClick={this.delete}>
```

**Comment by kapilpipaliya** [comment]
what i done fianlly:
```
<span
  onClick={(e) => {
    const row = this.contacts.$(rowKey)
    if(row.has('id')){
      row.set('value', {delete: true})
    } else {
      row.onDel(e);
    }
  }}
>
  Delete
</span>
```
