### ISSUE TITLE
Cannot intercept `fields` key

### ISSUE THREAD

**Issue by shrugs** [foxhound87/mobx-ajv-form#407]
The docs mention that one can 

> Specify fields as key and the nested fields map will be observed or intercepted (add/del).

But due to the implementation, passing `key: 'fields'` with an interceptor causes the code to attempt to intercept `field.$fields`, a property which doesn't exist, causing the error.

https://github.com/foxhound87/mobx-react-form/blob/master/src/shared/Events.js#L36

I'm not sure what the intended behavior is, but it'd be nice to either

1. mention in the docs that `fields` can only be observed, or
2. update the code to not prefix `key: 'fields'` with `$`

**Comment by foxhound87** [comment]
I think this will not be fixed due to a mobx issue
