### ISSUE TITLE
How would be the most efficient way to setState onSuccess hook?

### ISSUE THREAD

**Issue by ghost** [foxhound87/mobx-ajv-form#412]
I would like to set a state of the parent component onSuccess hook.
I cant find a proper way to do this... Should I do something like this?

```
constructor(props) {
	    super(props);
            this.handler = this.handler.bind(this)
	    this.state = {
	      myState: 'init'
	    };
	 };

	handler(newState) {
    	    this.setState({myState: newState});
  	};

.....

<Form form={form}  handler={this.handler}/>
```

if this is the right approach, then I'm stuck... don't know how to pass handler to form.onSubmit

**Comment by foxhound87** [comment]
See `bindings` and `event hooks` on the docs, it should help.
