### ISSUE TITLE
Checkbox is not working with release 1.3.4

### ISSUE THREAD

**Issue by duyenho** [foxhound87/mobx-ajv-form#414]
We upgraded to the version 1.3.4 and the form checkboxes are no longer working.

We downgraded to 1.32.3 and everything is fine again.

We would like to use the latest version.

**Comment by foxhound87** [comment]
The version 1.3.4 refers to the old mobx-ajv-form package, which is deprecated.
There's no 1.3.4 version for mobx-react-form.

**Comment by kapilpipaliya** [comment]
when you set the `<input type="checkbox"` field value `null`, component can't able to switch its status.
you have to process input before it gets to the component like:
`    input: {
      field_name: value => Boolean(value)
    },
`pass input object to mobx form to make it working.
