### ISSUE TITLE
.container() of direct subfield of form returns undefined

### ISSUE THREAD

**Issue by wwahammy** [foxhound87/mobx-ajv-form#416]
Currently, I'm trying to get the container for the a field which is a direct child of Form. When I do so, the .container() returns undefined. I'm not sure if that's intended but it's a bit surprising to me. Preferably, I think .container() should return the Form itself. Based on a quick look at the code, I suspect this could be fixed by modifying https://github.com/foxhound87/mobx-react-form/blob/1dab427b70c9f63a21f269b339a80a7a9fbd76aa/src/shared/Utils.js#L52

to:
```javascript
   return cpath ? this.select(cpath, null, false) : this;
```

I could be wrong though :smile:

**Comment by foxhound87** [comment]
Your proposal should be ok. I will look into it for the next release.
