### ISSUE TITLE
Empty array field starts life dirty

### ISSUE THREAD

**Issue by stubar** [foxhound87/mobx-ajv-form#417]
Hi Thanks for all your hard work making this project, it has save me loads of time building big forms.

I have an object array in my form that starts as an empty array.  As soon as I init the form it is dirty.  If I initialise the form with the array containing a single object it is not Dirty.  The problem is I want an empty array as the initial state as more often than not the user won't want to add anything to this array.  I have tried using defaults, values (using the separate props approach) and neither of those with the initial empty array and it is still dirty.  I notice the nested form demo also starts off dirty so I am guessing there is something up with the dirty checking code?

**Comment by stubar** [comment]
I have found this is to do with 
```
lib/Field.js:490
```
If I pass my values in as mobx observables it correctly compares it with the default and isDirty is correct.  If however I pass in plain js object it compares an array to observableArray which of course fails.

However if I pass values in as observables (in order to get round the above problem) the isValid is straight away false because the array value appears as " " in devtools which of course fails against the schema which is expecting an array.  A way of fixing this is by doing this
```
    key: 'isDirty',
    get: function get() {
      debugger
      return this.hasNestedFields ? this.check('isDirty', true) : !(0, _isEqual3.default)(_mobx.toJS(this.$default), _mobx.toJS(this.value));
    }
```
It normalizes the values to plain JS.  I have no idea what implications this has though as I don't know the codebase well enough.  I'm now deciding whether to fork or create a sort of higher order isDirty function in my form component which considers the isDirty state of the underlying mobxreactform but also doublechecks for nested arrays.

**Comment by benjamingeorge** [comment]
downgrading to 1.33 works too.

**Comment by LeoDT** [comment]
if you extend your own base form class you can use ```makeField``` to return a field with a overrided ```isDirty``` property.

**Comment by foxhound87** [comment]
Fixed https://github.com/foxhound87/mobx-react-form/commit/c6193d7021f3e1e55ea204247404a19f758425d0
