### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by annslittleflower** [foxhound87/mobx-ajv-form#420]
Hi guys, writing you just in case you will find an bug that i had encountered with today: 
```javascript
const fields = [
  // {
  //   name: 'email',
  //   label: 'Email',
  //   rules: 'email',
  // },
  {
    name: 'password',
    label: 'Password',
    value: '22',
    rules: 'required|string|between:5,25',
  },
];
```

it is a part of code where bug was. If those objects are different, or missing some keys i dont know exactly, this error is risen. Please explain this behaviour in comments above if somebody knows what just happened, cause i did not understand anything))) thanks in advance

**Comment by foxhound87** [comment]
I can't replicate your issue.

**Comment by foxhound87** [comment]
Can you provide the full error stack trace?

**Comment by foxhound87** [comment]
I'm closing this issue. Feel free to reopen if you need.
