### ISSUE TITLE
form is not valid although fields are changed and have non zero length

### ISSUE THREAD

**Issue by annslittleflower** [foxhound87/mobx-ajv-form#421]
`rules: 'required|string|between:5,25',`

i have such rules

```javascript
 handleInputChange = (e: any) => {
    console.log(e.target.name);
    // this.setState({
    //   [e.target.name]: e.target.value,
    // });
    mobxCredentialsFormInstance.$(`${e.target.name}`).set(e.target.value);
  }
```

and such update function

the question is - why forms is still invalid? when i delete required rule it works

**Comment by foxhound87** [comment]
You should not use `setState` because `mobx-react-form` already handles the form/fields state, see `bindings` in the doc.

Have you loaded the DVR validation plugin?

**Comment by foxhound87** [comment]
I'm closing this issue. Feel free to reopen if you need.
