### ISSUE TITLE
form.clear() does not clear input type="file"

### ISSUE THREAD

**Issue by vwong** [foxhound87/mobx-ajv-form#422]
I'm using input of `type="file"` and I can read the file itself with `form.select('myFieldName').files`, however, when I'm done with it, I can't clear the file selection with `form.clear()` nor with `form.select('myFieldName').clear()`.

Is this a bug? Or a misunderstanding on my part?

**Comment by foxhound87** [comment]
Some functionalities for file handling  are still not implemented. You need to handle it manually for now.

**Comment by Dakkers** [comment]
@vwong were you able to handle this manually?

**Comment by vwong** [comment]
I created a two-layered solution, where the `<input type="file" />` is hidden, and interacted with through a second `<input type="text" />`.  It's the second one that is in the form, and thus gets cleared accordingly.  Unfortunately, I can't find the `mobx-react-form` solution hidden in my git history, so the following is my solution after I actually ended up dropping `mobx-react-form` and rolling my own instead*.  The solution should be pretty similar though.  Good luck!

```javascript
@observer
export class File extends Component {
  input = React.createRef()
  state = { filename: '' }

  onChange = (e) => {
    const { name, files: [ file ] } = e.target
    this.props.onChange(name, file) // your signature may be different
    this.setState({ filename: file.name })
  }

  onClick = () => {
    this.input.current.click()
  }

  render () {
    const { value, name, label, error, onChange, ...props } = this.props
    const { filename } = this.state

    // first <input /> is actual element, with css display: none
    // second <input /> is the one user sees, and the one the form uses
    return (
      <p>
        <label htmlFor={name}>{label}</label>
        <input id={name} name={name} {...props} type='file' onChange={this.onChange} aria-invalid={!!error} ref={this.input} />
        <input value={filename} onClick={this.onClick} onKeyPress={this.onClick} placeholder='Nothing selected' readOnly />
        {error && <span>{error}</span>}
      </p>
    )
  }
}
```

* No disrespect to the package. I think it is a great package, but my goal was to reduce dependencies in order to improve performance - smaller bundles, faster parsing, etc...

**Comment by foxhound87** [comment]
The clear() and reset() methods have been recently tested and are clearing the ‘files’ prop correctly.
