### ISSUE TITLE
updating the form fields after form intialization

### ISSUE THREAD

**Issue by ar7casper** [foxhound87/mobx-ajv-form#423]
I've got a model that uses MobxReactForm.

First I define the fields, options & plugins, then, when data is received from the backend, I'd like to update the fields.

```
import MobxReactForm from 'mobx-react-form';

const fields = {
  minimum: {
    value: 1,
    label: 'label',
    rules: 'required|mumeric',
  },
  presets: {
    fields: {
      enabled: {
        value: false,
        type: 'checkbox',
      },
      amounts: {
        value: [],
        rules: 'numeric',
      }
}

const form = new MobxReactForm({ fields }, { plugins, options });

class MobxStore {
  @observable form = form;

  @action updateInfo = () => {
    form.init(newValues);
  }
}

```

In the docs, I see that the init should happen on class instantiation.
Looking for a way to do something like - 
```
form.init(somethingThatWillUpdateTheValuesOfTheForm);
```
For some reason, https://foxhound87.github.io/mobx-react-form/docs/actions/form.html#re-initialize-all-fields, doesn't seem to work.

Would love to get your help please.
@foxhound87

**Comment by ar7casper** [comment]
Managed to find the `.update` method. 
The only pain point I had with it is that I had to define the structure all over again, couldn't find an easy way to give it an object and for the update function to deduct what goes where.

**Comment by foxhound87** [comment]
You can also use the `onInit()` hook and the field `set()` method like this:

```javascript
const hooks = {
  onInit(form) {
    form.$('myField').set('value', ...);
  }
};

new Form({ fields, hooks });
```
