### ISSUE TITLE
[Help] custom validation with AJV

### ISSUE THREAD

**Issue by stubar** [foxhound87/mobx-ajv-form#424]
I want to define a custom validation function using AJV without using $ajv.addKeyword if possible.  

Can I mix validation plugins?

To be specific a fields data must **not** exist in a remote api call to be considered valid.

Is this possible?

**Comment by foxhound87** [comment]
Sorry for the delay.
1) Yes, you can mix validator.
2) you can create the validation you need when extending the plugins.
