### ISSUE TITLE
Nested array on add event

### ISSUE THREAD

**Issue by benjamingeorge** [foxhound87/mobx-ajv-form#428]
Is there a way to attach an arbitrary event listener to the "add" event of a nested field array such as "apparel.variants[]" ?   I would like to trigger the handler anytime a new item is added to "apparel.variants[]"

I currently have a work around using observe but I wonder if this is the wrong way to do it. 
```js
this.props.form.observe({
            path: "apparel.variants",
            key: "value",
            call: ({ form, field, change }) => {
                if (change.newValue) {
                    this.handleChangeTab(change.newValue.length - 1);
                }
            }
        });
```

**Comment by benjamingeorge** [comment]
I guess this doesn't work because it reacts to any nested arrays under apparel.variants as well.

**Comment by foxhound87** [comment]
I think you need to use `key: “fields”`
