### ISSUE TITLE
String Fields with `default` value cause field to initialize as `isDirty` on form init

### ISSUE THREAD

**Issue by pdfowler** [foxhound87/mobx-ajv-form#436]
version: v1.34
Using modified `_.extend.js` from `rfx-core`
May also relate to #417 since I first discovered this with a nested field

I came across this today after rebuilding one of our more intricate forms. The behavior seems counter-intuitive to me, but may be intentional.

### Repro Form init and code:
```
const unifiedFields = [
    {
      name: 'title',
      label: 'Shift Title',
      rules: 'required|string|between:5,50',
      default: '',
    },
    {
      name: 'description',
      label: 'Shift Description',
      rules: 'required|string|min:5',
    },
];

/* NOTE: getFlatFieldDefinition defined below */
const separatedFields = getFlatFIeldDefinition(unifiedFields);

const values = {
  title: 'This is my title',
  description: 'This is my Description'
};

const form = new ShiftForm({ ...separatedFields, values })

console.assert(form.isPristine, 'Form should be pristine')
console.assert(!form.isDirty, 'Form should not be dirty')
console.assert(form.$('title').isPristine, 'Title should be pristine')
console.assert(form.$('description').isPristine, 'Description should be pristine')
```

I find that any field that has a default value is set to 'dirty' if it gets a value, which, like I said is counter-intuitive to me. I consider the `default` values to be useful in the general form definition, allowing use as both a create and edit form for an entity.

My guess is that by setting a default value, the field gets set to 'isDirty' at that point. Setting the same field with the `value` does not reset it to `pristine` in the case where an existing entity's values are being set on the form.

Note: this does not seem to affect fields with an empty "type", a nested `array` set to default values of `[]`, eg: `{ name: 'address.loc`, label: 'Coordinates', default: { type: 'Point', coordinates: [] }`.

This isn't a hard bug to work around, but can be a little confusing as it is not doing what I expected.

### Additional library code:
``` 
function getSeparatedProperties(fields, key) {
  return _.reduce(
    fields,
    (val, f) => {
      val[f.name] = f[key];
      if (!_.isEmpty(f.fields)) {
        _.each(f.fields, (subField) => {
          val[`${f.name}[].${subField.name}`] = subField[key];
        });
      }

      return val;
    },
    {},
  );
}

function getFlatFieldDefinition(fields) {
  const flatFields = _(fields)
    .map((f) => {
      const fieldArray = [f.name];
      if (!_.isEmpty(f.fields)) {
        _.each(f.fields, (subField) => {
          fieldArray.push(`${f.name}[].${subField.name}`);
        });
      }
      return fieldArray;
    })
    .flatten()
    .value();

  return {
    fields: flatFields,
    labels: getSeparatedProperties(fields, 'label'),
    rules: getSeparatedProperties(fields, 'rules'),
    defaults: getSeparatedProperties(fields, 'default'),
    placeholders: getSeparatedProperties(fields, 'placeholder'),
  };
}
```

**Comment by foxhound87** [comment]
Sorry, I still need to test your case.
And yes can be related to #417

**Comment by foxhound87** [comment]
Fixed https://github.com/foxhound87/mobx-react-form/commit/c6193d7021f3e1e55ea204247404a19f758425d0
