### ISSUE TITLE
How to set fields to its default value inside constructor of form class

### ISSUE THREAD

**Issue by yashkh** [foxhound87/mobx-ajv-form#437]
I'm trying to call the mobx react form more than once and the problem is that when I call it suppose the second time, the field has the same value as it was updated the first time.

constructor(props) {
 super({ fields }, { plugins });
 this.newFields = Object.assign({}, fields);
}

So the `newFields` has the previous updated value every time I try to call the form. How can I get the default fields value like every time when I call the form?

One thing I found is that when I manually refresh the page, the fields gets back its original value which is obvious. Please correct me if I'm going wrong, I'm new to React and using this for the first time.

**Comment by pdfowler** [comment]
After saving changes, clearing changes, or otherwise closing the form, are you calling `form.clear()`? If the form isn't cleared, it will remain in the current state until it's next opened.

**Comment by yashkh** [comment]
No I'm not calling clear()

**Comment by yashkh** [comment]
I tried adding a clear() method at the beginning of the constructor but still the field values do not change.

**Comment by yashkh** [comment]
Any idea how I can reset the form fields to its default value?

**Comment by pdfowler** [comment]
We call `clear` at end of the form lifecycle (eg: at the end of everything that happens in our `onSubmit` hook). This code is a little old, but is what we based our form setup on: https://github.com/foxhound87/rfx-stack/blob/master/src/shared/forms/post.js

*Edit*: you might want to look at `form.init`: https://foxhound87.github.io/mobx-react-form/docs/actions/form.html#re-initialize-all-fields

**Comment by foxhound87** [comment]
to handle default values, you should define `default`/`defaults` prop when initializing the form.
Then use the `reset()` method to load them.

**Comment by utftu** [comment]
pls do applying default values by d-e-f-a-u-l-t

**Comment by pdfowler** [comment]
@utftufutukgyftryidytftuv FWIW, here's how I handle applying default values on form init:

```
export function init(
  values = {},
  defaults = {
    roles: ['user'],
  },
) {
  return new MyForm({
    fields,
    values: _.defaults(values, defaults),
    defaults,
  });
}
```
