### ISSUE TITLE
when the field value is undefined, validation rules not applied.

### ISSUE THREAD

**Issue by kapilpipaliya** [foxhound87/mobx-ajv-form#438]
i have `rules: 'required` for a field, but when its value is `undefined` its not validated before form submit.

**Comment by Dakkers** [comment]
@kapilpipaliya do you mean when you submit the form? or when you change the field?

**Comment by kapilpipaliya** [comment]
When i submit the form.

**Comment by Dakkers** [comment]
would you be willing to share your code?

**Comment by foxhound87** [comment]
Cannot replicate this issue without a form config.
Undefined values are working correctly, at least in new the next releases.
Feel free to reopen this issue with a codesandbox.
