### ISSUE TITLE
[Help] How do i disable a field and prevent output in form.values()

### ISSUE THREAD

**Issue by haThaiHoang** [foxhound87/mobx-ajv-form#439]
Thanks for great js library.
As title. I have "email" and "password" fields and i want to disabled "email" field" as:
```
[{
      name: 'email',
      disable: true,
      label: 'Email',
      rules: 'required|email',
}, {
      name: 'password',
      label: 'Password',
      type: 'password',
      rules: 'required|string|min:4',
}]
```
By default, result of form.values() contain "email" property but I don't need it
 just:
```
{
  password: "something"
}
```
Is there a way to solve it?
`Thank you!`

**Comment by foxhound87** [comment]
You should set `retrieveOnlyEnabledFields: true` in form options:

https://foxhound87.github.io/mobx-react-form/docs/form/form-options.html
