### ISSUE TITLE
How to distinct required form fields fields (DVR validation)

### ISSUE THREAD

**Issue by kidroca** [foxhound87/mobx-ajv-form#441]
I want to present **required** form fields with a different label e.g. `${label} *` so I need to distinct these fields using the Form/Field API 

I went over the Field documentation but didn't see anything related

Ideally `field.bind()` should return something like `{ required: bool, ...rest }`

**Comment by foxhound87** [comment]
If you need you can create your own bindings:
https://foxhound87.github.io/mobx-react-form/docs/bindings/custom.html
