### ISSUE TITLE
label is blank string when reading on array field.

### ISSUE THREAD

**Issue by kapilpipaliya** [foxhound87/mobx-ajv-form#447]
I set Label on field like this:
```
labels:{ ..images[]: "Images"}
```
I read the label like this:
```
<h5>{form.$('images').label}</h5>
```
it gives blank string.

**Comment by bin16** [comment]
~~Same question, it works for my login form, but not for another one.
I can get name from `form.$(field).name`, but get a empty string from`form.$(field).label`~~

solved. for me, form.init is called again

**Comment by kapilpipaliya** [comment]
Thanks, it should be `labels:{ images: "Images"}`
