### ISSUE TITLE
Form.isDirty / isPristine Doesn't work when removing item from array field

### ISSUE THREAD

**Issue by levic92** [foxhound87/mobx-ajv-form#450]
When removing an item from an array field form.isDirty doesn't work and still thinks the form is pristine.

A secondary problem is if I have a field such as "photos" and I treat this as an array field with no sub attributes then adding an item will not make form dirty.

Maybe for array fields the length should also be used to check if the form is dirty?

**Comment by foxhound87** [comment]
Related to 
#417
#436
#367

**Comment by foxhound87** [comment]
Fixed https://github.com/foxhound87/mobx-react-form/commit/c6193d7021f3e1e55ea204247404a19f758425d0
