### ISSUE TITLE
Adding a new object in array 

### ISSUE THREAD

**Issue by andrefox333** [foxhound87/mobx-ajv-form#451]
According to the docs https://foxhound87.github.io/mobx-react-form/docs/actions/shared.html#add--del,

Adding into my array with something like below works if hobbies is an array of strings.
```
 form.$('hobbies').add({ value: 'soccer' });
```

But what if hobbies is an array of nested fields? ie.
```
hobbies[].foo
hobbies[].bar
```

If I try to add it with something like below, it doesn't work...
```
form.$('hobbies').add({ foo: 'test', bar: 'drive' })
```

How have you guys added a new item in an array with initial values?

**Comment by foxhound87** [comment]
use an array on the add() method:

```javascript
form.$("hobbies").add([{
  foo: "test",
  bar: "drive"
}]);
```
