### ISSUE TITLE
Unable to get value for non-simple inputs

### ISSUE THREAD

**Issue by ilyakatz** [foxhound87/mobx-ajv-form#456]
Using this example

https://github.com/foxhound87/mobx-react-form-demo/blob/master/src/components/inputs/SimpleSelect.jsx#L1, 

I created a field that is a simple dropdown and added it to the form. However, if I inspect the values when form is submitted (eg, in `onSuccess` for a form), the value of that field is a blank string.

I'm using this style of form initialization

https://foxhound87.github.io/mobx-react-form/docs/getting-started.html

Maybe I'm missing something, but is there documentation on how to define value attribute for a non-simple inputs?

**Comment by foxhound87** [comment]
Can you provide the code of your dropdown?

**Comment by ilyakatz** [comment]
I was able to figure it out. Looks like that it's possible to create form using different methods. One of the methods is using the hash in the form. I followed an example (which I can't find now) that used a form hash that didn't fully work. Since I can't find it now, I'll have to close it. If I come across it, I'll post it.
