### ISSUE TITLE
How to use demo

### ISSUE THREAD

**Issue by rosieks** [foxhound87/mobx-ajv-form#458]
How can I use demo? I would like to create some form similar to one that I have found in demo but actually it's hard to find how to achieve that. It would be nice to have some example code like here: https://redux-form.com/7.4.2/examples/simple/

**Comment by Dakkers** [comment]
better demo code is definitely something to be desired - it's all over the place in terms of setup, etc. which part are you hoping to accomplish?

**Comment by foxhound87** [comment]
In the demo repo I use all the extensible functionalities of the package. 
I don't think I will change it. Rather I will create more codesandboxes and link it in the docs.
