### ISSUE TITLE
initial for nested field

### ISSUE THREAD

**Issue by simon998yang** [foxhound87/mobx-ajv-form#459]
For your nested fields demo

```javascript
const fields = [
  'club.name',
  'club.city',
  'members',
  'members[].firstname',
  'members[].lastname',
  'members[].hobbies',
  'members[].hobbies[]',
];

const initials = {
  club: {
    name: 'Jazz Club (initials)',
    city: 'New York (initials)',
  }
};
````

I want to give initials to members as well, 

I tried following, but without success.  am i doing something wrong?

```javascript
const initials = {
  club: {
    name: 'Jazz Club (initials)',
    city: 'New York (initials)',
  },
members: [{
    firstname: 'initFirstName',
    lastname: 'initLastName',
    hobbies: ['initHobby1', 'initHobby2'],
  }]
};
```

**Comment by Dakkers** [comment]
@simon998yang see https://github.com/foxhound87/mobx-react-form/issues/463 , I think you just need to use `Form.init` instead of `initials` in the constructor

**Comment by foxhound87** [comment]
@simon998yang This should be fixed, try the new version using `initials` in the constructor.
