### ISSUE TITLE
Drop support for mobx3

### ISSUE THREAD

**Issue by Dakkers** [foxhound87/mobx-ajv-form#460]
https://github.com/mobxjs/mobx#browser-support

Mobx3 has no active branch. Mobx4 is LTS, and Mobx5 is current. As such, we should just drop mobx3 support.

**Comment by foxhound87** [comment]
I don't think I will drop the support. 
Maybe there is someone that is still using mobx3.
Some of my projects still depend on it.

**Comment by Dakkers** [comment]
You could say the same thing about IE9.

**Comment by foxhound87** [comment]
I wrote IE6 workarounds for years :D
