### ISSUE TITLE
Array initials doesn't render

### ISSUE THREAD

**Issue by rosieks** [foxhound87/mobx-ajv-form#463]
I have problem with initializing array with values. I have prepared the following demo: https://codesandbox.io/s/m5o8l00vv8

It works for *number* field but doesn't for *numbers*. What I do incorrect?

**Comment by Dakkers** [comment]
@rosieks here's my version of your demo, which renders the fields:

https://codesandbox.io/s/v0242mq0r0

and just in case the sandbox doesn't work, here's the code:

```
import React from "react";
import ReactDOM from "react-dom";
import MobxReactForm from "mobx-react-form";
import { observer } from "mobx-react";

import "./styles.css";

const Editor = observer(function Editor() {
  const initials = {
    numbers: ["1", "2", "3"],
    number: "3"
  };
  const fields = ["numbers", "numbers[]", "number"];
  var form = new MobxReactForm({ fields, initials }, {});
  form.init({
    number: "3",
    numbers: ["1", "2", "3"]
  });

  return <Form form={form} />;
});

const Form = observer(function Form({ form }) {
  console.log(form.$("numbers"));
  return (
    <div>
      {form.$("numbers").map(f => {
        console.log(f);
        return <Number field={f} />;
      }) /* This one doesn't render */}
      <input {...form.$("number").bind()} />
    </div>
  );
});

const Number = observer(function Number({ field }) {
  return <input {...field.bind()} />;
});

function App() {
  return <Editor />;
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

```

**Comment by Dakkers** [comment]
in my experience you should always wrap your Form renderer in `observer`, since the `form` prop (from mobx-react-form ) tends to be an observable.

the thing that made it work, though, was the `form.init({ ... })`

**Comment by rosieks** [comment]
Unfortunately `init` crash if one field is not provided: https://codesandbox.io/s/qlm6q2wrk4
Not sure if this is by design or this is another bug

**Comment by Dakkers** [comment]
it could be either. the "init" may override the `initials` entirely -- which would then make `number` not defined in your case. I don't use the `initials` fields -- I only use `.init`. (sorry that this is not an actual solution to the root problem, but it's the work around that's worked for me)

**Comment by foxhound87** [comment]
The init() method will overwrite the  form state with new one. To update use the update() or the set() methods. See the doc for more info.
