### ISSUE TITLE
Don't import _ from lodash to reduce bundle size

### ISSUE THREAD

**Issue by Dakkers** [foxhound87/mobx-ajv-form#464]
Only a handful of Lodash functions are used. It's better to import them on their own so that tree-shaking can occur. There's also some functions that can be replaced with native JS. I don't mind making a PR for this.

**Comment by vkrol** [comment]
> It's better to import them on their own so that tree-shaking can occur.

Already done https://github.com/foxhound87/mobx-react-form/issues/58. 

> There's also some functions that can be replaced with native JS.

This is a good idea.

**Comment by foxhound87** [comment]
I opted to externalize lodash, I tried every webpack and babel config, but the treeshaking is not working.

**Comment by foxhound87** [comment]
@Dakkers if you came up with PR with a working configuration, feel free to reopen this issue.

**Comment by vkrol** [comment]
@foxhound87 could you elaborate why `babel-plugin-lodash` was removed? This affected those users who do not use UMD bundles. For them, the entire `lodash` is included in the bundle now.

**Comment by foxhound87** [comment]
@vkrol I removed it and used `lodash-webpack-plugin` instead. 
On the UMD implementation, the user should include it as dependency.

**Comment by vkrol** [comment]
@foxhound87 
> I removed it and used lodash-webpack-plugin instead.

But this plugin will work for UMD users only.

> On the UMD implementation, the user should include it as dependency.

What dependency?

**Comment by foxhound87** [comment]
I mean including `lodash` as dependency (for UMD usage).

**Comment by foxhound87** [comment]
And using `babel-plugin-lodash` the bundle size did not change.
