### ISSUE TITLE
How to update file field if it was previously initialized

### ISSUE THREAD

**Issue by rosieks** [foxhound87/mobx-ajv-form#465]
Hi,
I'm trying to create form with file field. It works fine until I initialise it with default value. In such case it changing file stops working. Here is sample code: https://codesandbox.io/s/kwppx13zzv

It works fine if there is no `init` function called. But if it is then it stop working. To reproduce try to upload file.

**Comment by foxhound87** [comment]
did you take a look at the demo repo?

**Comment by foxhound87** [comment]
The ‘init()’ method has been deprecated in the next releases
