### ISSUE TITLE
Nested Fields Not Generating Error Message [dvr]

### ISSUE THREAD

**Issue by marjan2k** [foxhound87/mobx-ajv-form#474]
Hi,

DVR with validatorjs is not generating error messages for nested fields even though the nested field's flag hasError becomes true

![image](https://user-images.githubusercontent.com/14934345/51044881-2f076b00-1590-11e9-870b-1ceb9200de39.png)

**Comment by foxhound87** [comment]
Is this the initial state?
Did you submitted the form?

**Comment by IamKritika** [comment]
@foxhound87 Even I am facing the same issue, hasError on field is true but error message is not displayed.
If I have required validation on nested field, no message is displayed if it's empty.

**Comment by foxhound87** [comment]
If the form is not yet submitted check the showErrorsOnInit/validateOnInit form options.

**Comment by marjan2k** [comment]
I'm closing this issue. The messages didn't get generated because I meddled with by providing a custom onChange function.
