### ISSUE TITLE
DVR Plugin - required_if etc. makeLabels

### ISSUE THREAD

**Issue by lukasniestroj** [foxhound87/mobx-ajv-form#480]
the latest makeLabels function throws an exception if a rule like "required_if:field,value" is supplied. 
The line https://github.com/foxhound87/mobx-react-form/blob/master/src/validators/DVR.js#L55 results in a form select of the "value" which results in an exception.

**Comment by foxhound87** [comment]
I can't replicate the issue.
Please can you send a PR with a failing test?
If you can help I could ship this fix in the next release.
Thank you.

**Comment by Nodios** [comment]
I notices the same thing: I managed to replicate it [here](https://repl.it/@Nodios/Testing-mobx-forms)

**Comment by foxhound87** [comment]
@Nodios it does not start.

**Comment by Nodios** [comment]
@foxhound87  I just started it without a problem?

**Comment by Nodios** [comment]
@foxhound87 See [this](https://github.com/foxhound87/mobx-react-form/blob/c6193d7021f3e1e55ea204247404a19f758425d0/src/validators/DVR.js#L59)

```
_.each(rule.value.split(','), (p) => {
    const f = this.state.form.$(p);
    if (f && f.path && f.label) {
        labels[f.path] = f.label;
    }
});
```

The `_.each()` is iterating over the split items, but split items are in format `field,value`, line with
the `_.each()` shouldn't exist but rather you should just access the first item of a split.

Something along these lines:
```
const f = this.state.form.$(rule.value.split(',')[0]);
if (f && f.path && f.label) {
    labels[f.path] = f.label;
}
```

Correct me if I'm wrong

**Comment by Nodios** [comment]
I just noticed that this might not be the case. You will have to have a special rule for handling _required_if_ since it's the only one that has the structure _field,value_ rather than _field,field_

**Comment by foxhound87** [comment]
maybe @riceyeh can give more info about this implementation, since the function was written by him.

**Comment by riceyeh** [comment]
@Nodios, you are right that both required_if and required_unless are exceptions to the required_* case on the if condition on line 58 in makeLabels() in DVR.js. In addition, 'different' rule is also qualified for makeLabels.

@foxhound87, I suggest to modify the makeLables(...) to the following code:

```javascript
  makeLabels(validation, field) {
    const labels = { [field.path]: field.label };
    _.each(validation.rules[field.path], (rule) => {
      if (typeof rule.value === 'string' && rule.name.match(/^(required_|same|different)/)) {
        _.each(rule.value.split(','), (p, i) => {
          if (!rule.name.match(/^required_(if|unless)/) || (i % 2 === 0)) {
            const f = this.state.form.$(p);
            if (f && f.path && f.label) {
              labels[f.path] = f.label;
            }
          }
        });
      }
    });
    validation.setAttributeNames(labels);
  }
```

**Comment by foxhound87** [comment]
@kozodev still can't start the repl project, can you port it to codesandbox?
@riceyeh @kozodev please create a PR with failing tests and the new implementation.

**Comment by foxhound87** [comment]
I replicated it here: 
https://codesandbox.io/s/r03z3zojxn

The error I get is: 
`Uncaught (in promise) Error: The selected field is not defined (true)`

@kozodev is it the same error?

**Comment by Nodios** [comment]
It is

**Comment by foxhound87** [comment]
@riceyeh this line `if (!rule.name.match(/^required_(if|unless)/)` works only for `if` and `unless`. what about `with` and `without` (wich you can find in the offical doc)?

**Comment by foxhound87** [comment]
@riceyeh and why that match on `same|different` and not only `required_`?

**Comment by foxhound87** [comment]
I made tests for this configuration:

```javascript
import validatorjs from 'validatorjs';
import { Form } from '../../../../src';
import dvr from '../../../../src/validators/DVR';

const plugins = {
  dvr: dvr(validatorjs),
};

const fields = [{
  name: 'passwordConfirm',
  label: 'Password Confirmation',
  rules: 'required_if:passwordRequired,true',
  value: '',
}, {
  name: 'passwordRequired',
  label: 'Password Required',
  type: 'checkbox',
  value: true,
}];

class NewForm extends Form {}

export default new NewForm({ fields }, { plugins, name: 'Fixes-480' });
```

but after `submit()` the form is still valid, should be invalid...

**Comment by foxhound87** [comment]
I think because it does not recognize `'true'` string as boolean.

Related: https://github.com/skaterdav85/validatorjs/issues/285

**Comment by foxhound87** [comment]
Using string values is working.

**Comment by foxhound87** [comment]
and still the `passwordRequired` label is missing from the error message

**Comment by foxhound87** [comment]
I updated `validatorjs` to latest version and the label worked. I'm relasing the fix.

**Comment by codebury** [comment]
In my case, required_if is handling boolean parameter as string: 
`rules: 'required_if:apto,true'`
So validation is always passing (Chrome 79.0.3945.88).

As a workaround, I solved the issue casting the value to string after checking if it's not null or undefined and then registering it using `Validator.registerImplicit`:

```
let op = this.validator._objectPath(this.validator.input, req[0]);        
        if ((op != undefined && op != null ? op.toString() : null) === req[1]) {
            return this.validator.getRule('required').validate(val);
        }
```
Maybe it's not optimal, but it works and could help anyway.

**Comment by gazpachu** [comment]
`rules: 'required_if:field,true'` that's also not working for me. The field is a checkbox. Latest versions of validator and mobx-react-form
