### ISSUE TITLE
Issue with form.update and field.set

### ISSUE THREAD

**Issue by pawelkeska** [foxhound87/mobx-ajv-form#483]
I'm having issue to set form field. which is an array, after the update my values form:

`form.update({
   'users_assigned' : ['11', 14', '16']
})`

next, i tried updating this filed by:

`form.$('users_assigned').set(['20', '21'])`

And nothing change but when i used method set on form, everything is ok, below is example:

`form.set({
   'users_assigned' : ['11', 14', '16']
})
`form.$('users_assigned').set(['20', '21'])`
`

I read in documentation, that method update recreate the fields tree and provide new values, is that problem ? but method set change the properties of existent/selected fields.

I can't perform update and then set field because update method create new instance and method set operates on old value ??

**Comment by foxhound87** [comment]
if you are dealing with arrays, consider using `add()` and `del()` methods.

**Comment by foxhound87** [comment]
```javascript
    ["1", "2"].map(value => form.$("array").add({ value }));
```

**Comment by foxhound87** [comment]
when using `set()`, you are changing the `value` property of the field, this means the field does not have nested fields, but an array of values.

**Comment by pawelkeska** [comment]
Thanks, That's what I wanted
