### ISSUE TITLE
submitted counter property not available

### ISSUE THREAD

**Issue by janezgec** [foxhound87/mobx-ajv-form#484]
`form.submitted`
is supposed to be a computed property containing a counter of how many times form was submitted as shown in the docs:
https://foxhound87.github.io/mobx-react-form/docs/api-reference/form-properties.html

However, there is no such property... Am I missing something?

**Comment by foxhound87** [comment]
did you installed the latest version?

**Comment by janezgec** [comment]
Thanks, that did it
