### ISSUE TITLE
Cascading dropdown with remote data (select field)

### ISSUE THREAD

**Issue by saysmaster** [foxhound87/mobx-ajv-form#487]
I'm new to mobx-react-form and I was wondering how am I to implement select fields that change their options dynamically based on from values. For instance I have a `customerId `field. The user has to select from all available customers in a drop-down. When a customer is picked, the user has to select, through another drop-down, from all the available customer contacts for that particular customer. The available contacts would be fetched from a rest api upon customer selection.

I read into the documentation that the `extras` field property can be used for custom implementations. Is there a way to update the `extras` field dynamically?

If not, i am thinking of another approach. Creating an observable object that will be responsible for fetching options from an api, and storing them in its 'options' property. Then storing that object as the `extras` property of the field, so the `extras` field won't actually change, but the drop-down component would bind it's `props.options` to the 'extras.options' property.

Would that be a sensible approach?

**Comment by foxhound87** [comment]
```javascript
// set
instance.state.extra({ data }); 

// get
const data = instance.state.extra('data');
```

see also this comment: 
https://github.com/foxhound87/mobx-react-form/issues/303#issuecomment-325210858

**Comment by saysmaster** [comment]
What does the `instance` represent here? Form instance or field instance?

Also, if I want to create a template for my custom dropdown implementation, could I do something like this?

```
MyDDTemplate = ({ $try, field, props }) => ({
	...,
        options: $try(props.options, field.state.extra('options'))
	...
})
```

**Comment by foxhound87** [comment]
`instance` can be a Form or Field in this case.

You can do that, but I suggest to rename `options` because is a prop reserved for the form/field options. Btw, you can set directly `field.set('extra', ...);` which is the `extra` prop of that specific field, instead using `field.state.extra()` which is a global extra state accessible from all instances.
