### ISSUE TITLE
How to prevent reseting values if initial values didn't change?

### ISSUE THREAD

**Issue by rosieks** [foxhound87/mobx-ajv-form#489]
I want to create component that contains initialValues and some other properties. Unfortunately if I change some property of that component all values in my form are reset to initial value (despite that initial values didn't change). I would expect that `init` method doesn't reset form, but rather change default values. I have prepared some demo that show the problem: https://codesandbox.io/s/2p37zllqwj

Just type something in form and then click Submit. After that the text "submitting" appears but unfortunately values go back to initial.

Any idea?

**Comment by foxhound87** [comment]
First of all, you have to move `form.init(state.initialValue);` outside the components, otherwise, you will get an error because it's not a pure function and also because it will cause to re-init the form to each re-render of the component.

**Comment by foxhound87** [comment]
if you want to keep the state of the form consider using `update()` or `set()` instead of `init()`

**Comment by foxhound87** [comment]
I'm closing this as the `init` method will be deprecated in next version.
