### ISSUE TITLE
How to define/override validation error messages text?

### ISSUE THREAD

**Issue by odyssey-spec** [foxhound87/mobx-ajv-form#49]

**Comment by foxhound87** [comment]
Hi @joneyphair,
it depends on which plugin you are using.

- Using Vanilla Javascript Validation Functions (VJF) you can provide it into the function. The function have to return a boolean or an array with [boolean, string], which the second argument is the error message for the [custom functions](https://foxhound87.github.io/mobx-react-form/docs/validation/modes/vjf-custom.html).

- Using Json Schema Validation Keywords (SVK) with [ajv](https://github.com/epoberezkin/ajv) you can provide [error messages for custom keywords](https://github.com/epoberezkin/ajv/issues/161), or [override existing custom messages](https://github.com/epoberezkin/ajv/issues/181).

- Using Declarative Validation Rules (DVR) you can provide custom error messages for [custom registered rules](https://foxhound87.github.io/mobx-react-form/docs/validation/modes/dvr-custom.html), or you can override the default messages when extending the plugin:

``` javascript
const plugins = {
  dvr: {
    package: validatorjs,
    extend: ($validator) => {
      // here we can access the `validatorjs` instance
      var messages = $validator.getMessages('en');
      messages.required = 'Whoops, :attribute field is required.';
      $validator.setMessages('en', messages);
    },
  },
};
```

I will improve the documentation about custom error messages in the future.

**Comment by odyssey-spec** [comment]
thx

**Comment by timarney** [comment]
Is there a way to set a generic message for all error types on a field or do you need to override each type i.e. show Invalid Password for all these (required|string|between).

**Comment by foxhound87** [comment]
I think you can achieve that using `.invalidate('a generic error message')` on Fields instances when they don't pass validation (for example observing Field's isValid prop). The invalidate method will overwrite the last error message.

**Comment by cgat** [comment]
For the DVR case, it seems to be impossible to set custom message messages for the conditional rules (require_if) because a) it doesn't appear to be possible to make conditional rules with the register rule method and b) custom messages are passed into the constructor, which we don't have access to.

**Comment by jonasdumas** [comment]
If you use DVR Validator , **to automatically change the language for all errors**, you can simply do it like this:

```
import validatorjs from 'validatorjs';
import MobxReactForm from 'mobx-react-form';
import { observer } from 'mobx-react';

// For french For example:
validatorjs.useLang('fr');
```

**Comment by foxhound87** [comment]
Related to #305
