### ISSUE TITLE
Implementations with react-native

### ISSUE THREAD

**Issue by optimatex** [foxhound87/mobx-ajv-form#490]
Hi. I used this [approach](https://github.com/foxhound87/mobx-react-form/issues/218#issuecomment-323716825) from other issues. But I got the next behavior:
1) I received console.logs from my handlers
```
const handleOnChange = field => text => {
  console.log('%c handleOnChange', 'color: #0087d4', text);
  field.set(text);
};
```
they show me that input is reacted to typing but the value is not preserved. 
the whole component is next
```
import React from 'react';
import { TextInput } from 'react-native';

const handleOnChange = field => text => {
  console.log('%c handleOnChange', 'color: #0087d4', text);
  field.set(text);
};

const WrappedInput = props => {
  return (
    <TextInput
      {...props.field.bind({ onChange: () => {} })}
      onChangeText={handleOnChange(props.field)}
    />
  );
};

export default WrappedInput;
```

are there some examples using this lib with react-native?

**Comment by foxhound87** [comment]
Maybe you should wrap your component in a mobx-react `observer`.

Also you should look at [**Event Hooks** (on fields)](https://foxhound87.github.io/mobx-react-form/docs/events/event-hooks/constructor.html#defining-hooks-on-field) defining the `onChange` Event Hook on field initialization for the constructor. It will still call the built-in `onChange` Event Handler so the lib will update the field itself.

**Comment by foxhound87** [comment]
You definitely have to look [bindings](https://foxhound87.github.io/mobx-react-form/docs/bindings/)

You need to bind `onChangeText` to the built-in `onChange` handler:

```javascript
<TextInput
      {...props.field.bind()}
      onChangeText={props.field.onChange}
/>
```

**Comment by mike1023** [comment]
@foxhound87 could you show a completed demo, I meet a same problem....

**Comment by foxhound87** [comment]
@mike1023 my snippet in the comment above should be enough.

**Comment by foxhound87** [comment]
Tested on react native and I had no issues.
I close this.
