### ISSUE TITLE
Reaction after group adding nested fields

### ISSUE THREAD

**Issue by tryfonkov** [foxhound87/mobx-ajv-form#491]
Hi!
I have a table row consisting of two parts, which are represented by form fields.
1. Category - is an `<select>` element.
2. Composition - a list whose values depend on the selected category.
When a category is selected via a graphical interface (change `<select>`), then the field handler `onChange` is triggered, then `onChange` hook (here the nested fields are added to the Composition) and only then all the new fields are rendered.
The problem is that when I need to change the category programmatically (`form.$('category').onChange(value)`), the render is triggered after each addition of a new field.

Console output (change via `<select>`)

```
end hook
render item
render item
```

Console output (programmatically change):

```
window.mobxForm.$('category').onChange(2) 
[undefined, undefined]
render item 
render item 
render item 
render item 
end hook 
```
https://codesandbox.io/s/38q15n328m

What could be the reason for this behavior?

**Comment by foxhound87** [comment]
Cannot access `window.mobxForm`.
I edited the code here: https://codesandbox.io/s/1v3ymzm6w4
Added a button to programmatically change the select field value to `2`.

**Comment by tryfonkov** [comment]
I added an instance of the form to the `window` to check the value change using the console. Like this:
```
class App extends React.Component {
  constructor(props) {
    super(props);
    this.form = window.mobxForm = new Form({ fields });
  }
```
1. `window.mobxForm.$('category').onChange(2)` - render on each iteration of adding a field, the hook `onChange` is not yet complete.
2. call handler `onClickSelect2` when the button is pressed - all fields are added, the hook is complete and only after that the rendering begins.

**Comment by foxhound87** [comment]
I did it, for some reason when I write `window.mobxForm` in the console, it returns `undefined`

**Comment by tryfonkov** [comment]
Please try this:
```
class App extends React.Component {
  constructor(props) {
    super(props);
    this.form =  new Form({ fields });
    setTimeout(() => {
      this.form.$("category").onChange(2);
    }, 3000);
  }
```

**Comment by foxhound87** [comment]
Using this code is logging 3 renderings and then `end hook`

**Comment by tryfonkov** [comment]
Yeah, right. What is the reason that when you click on the button, the fields are first added and the hook is completed, and then the render is performed? The function (`this.form.$("category").onChange(2)`) call is the same in both cases.

**Comment by foxhound87** [comment]
But the rendered result is correct, right?

I think this behavior is related on how mobx and react handles the rendering

**Comment by tryfonkov** [comment]
Ok! Thanks!
