### ISSUE TITLE
Are there breaking changes in V2?

### ISSUE THREAD

**Issue by andrefox333** [foxhound87/mobx-ajv-form#494]
More of a question, want to bring in V2 but just checking if there are any breaking changes I need to be aware of. Thanks. :)

**Comment by foxhound87** [comment]
The release has no breaking changes.

The v2 has been released automatically by semantic-release due to an unwanted **breaking changes** comment of a commit from the PR #488 , but in reality the code of that commit was "cleared" by the author.

**Comment by danconnell** [comment]
You could have squashed my commits or asked me to, @foxhound87

**Comment by foxhound87** [comment]
You are right, but I could have not notice that comment from the github interface
