### ISSUE TITLE
setting a field's value to null does not have effect on the nested fields' values

### ISSUE THREAD

**Issue by riceyeh** [foxhound87/mobx-ajv-form#495]
Setting field's value to null does not have effect on the nested field's value with the following test example:

const fields = [
	'club',
	'club.name',
	'club.city'
];
const labels = {
	'club': 'Club',
	'club.name': 'Name',
	'club.city': 'City'
}
const values = {
	club: {
		name: 'JJSC',
		city: 'Taipei'
	}
}
$999 = new Form({ fields, labels, values }, { name: 'club form' })

describe('set null value', () => {
	it.only('', () => {
    expect($999.$('club.name').value).to.be.equal('JJSC')
    expect($999.$('club.city').value).to.be.equal('Taipei')
    $999.$('club').set(null) // <-- set club to null
    expect($999.values()) // <-- this expect fails, setting null value has no impact on nested fields' values
      .to.be.deep.equal({
        club: {
          name: '',
          city: ''
        }
      })
  })
});

**Comment by foxhound87** [comment]
This because if a field has nested fields, its values cannot be set, it is computed.

**Comment by foxhound87** [comment]
But maybe this can be enhanced

**Comment by riceyeh** [comment]
I have created a pull request #496 to set each nested field's value to empty string when the field is set to null. This makes sense and consistent  because a null-valued field has it nested fields empty-string-valued in a form construction as what is done with pull request #493

**Comment by foxhound87** [comment]
@riceyeh did you see my comment in #496 ?
