### ISSUE TITLE
'this' is undefined when using custom validation rules

### ISSUE THREAD

**Issue by mdakovac** [foxhound87/mobx-ajv-form#501]
When using custom rules with `DVR`, e.g.
```
const customRules = {
	less_than: {
		rule: (value, req, attr) => {
			console.log("Value of this", this);
			return (this.validator.input[attr] < this.validator.input[req]);
		},
		message: 'err'
	},
};
```
validator cannot be accessed since `this` is undefined.

Issue reproduction: [https://repl.it/@Nodios/Mobx-React-Forms-custom-validator](https://repl.it/@Nodios/Mobx-React-Forms-custom-validator)

**Comment by Nodios** [comment]
bump

**Comment by foxhound87** [comment]
What do you expect `this` to be in that context?
