### ISSUE TITLE
Ignoring Extended DVR Rules

### ISSUE THREAD

**Issue by GeorgeWL** [foxhound87/mobx-ajv-form#502]
I'm not sure what the reason is to be honest, recently updated our webpack version and ever since, the custom validation rules seem to be being ignored entirely.

The string rules are still being registered however.

Tested by setting it to console log on blur in the parent form with the form.errors(), and in each case, when entered a value that was valid for the string rules and not valid for the custom extended rule, it would give the error as null.

https://gist.github.com/GeorgeWL/71cecc23ee6733766386ad5bcc5bb4b9 for the snippet of the file containing our form initializer.

Version: 1.36.1
webpack: 4.30.0
webpack-dev-server: 2.9.4
webpack-cli: 3.3.1
webpack-manifest-plugin: 1.3.2
webpack-dev-server: 3.3.1

**Comment by asim-khan** [comment]
I am also getting the same issue. Form validation is not working.

**Comment by foxhound87** [comment]
Did you tried an older version of the mobx-react-form? What about an older version of webpack? Is it working?

**Comment by foxhound87** [comment]
Also which kind of validation mode are you taking about?

**Comment by foxhound87** [comment]
I took a look at your snippets.
The `extend` callback param has changed in the latests versions.

you should try like this:

`extend: ({ validator, form }) => { ... }`

and not

`extend: $validator => { ... }`

**Comment by GeorgeWL** [comment]
@foxhound87 It was working fine before the team went and updated the modules that were outdated, Babel and Webpack, to newer versions.

This is still using the older version however, rather than the newer.

**Comment by foxhound87** [comment]
So you can confirm that using an older version of webpack is working?
Also try to update the package and use the new syntax that I suggested.
Let me know.

**Comment by GeorgeWL** [comment]
I can confirm that before updated webpack it was working.

I'll try the new syntax later, see if it's something caused by newer webpack or an issue with the module

**Comment by GeorgeWL** [comment]
Yep. Updating mobxform made it all work again, guess that older versions aren't keen on webpack 4

**Comment by foxhound87** [comment]
Great! Good to hear
