### ISSUE TITLE
null date is set to be empty string '' after setup

### ISSUE THREAD

**Issue by riceyeh** [foxhound87/mobx-ajv-form#507]
A null value for a field with type 'date' is initialized to have a value '' after a form construction. The is not consistent with the scenario adding a field with type date, which will have default null value. An example:

const fields = [
	'people',
	'people[]',
	'people[].name',
	'people[].birthday'
];

const types = {
	'people[].birthday': 'date'
}

const values = {
	people: [{
		name: 'adam',
		birthday: null
	}]
}

class NewForm extends Form {}

export default new NewForm({ fields, types, values }, { name: '$999' });

 expect($.$999.$('people.0.birthday').value).to.be.equal(null) // for now, it is incorrectly to be ''
 expect($.$999.$('people').add().$('birthday').value).to.be.equal(null) // but added field is correctly  to be null

**Comment by riceyeh** [comment]
If pull request #508 is accepted, the isDirty method should be changed to 

    return !_.isUndefined(this.initial) &&  // Now, it is !_.isNil(this.initial) 
      !_.isEqual(this.initial, this.value);

because null, just like '', could be the initial value.

**Comment by foxhound87** [comment]
> If pull request #508 is accepted, the isDirty method should be changed to
> 
> ```
> return !_.isUndefined(this.initial) &&  // Now, it is !_.isNil(this.initial) 
>   !_.isEqual(this.initial, this.value);
> ```
> 
> because null, just like '', could be the initial value.

it is already using `isNil`
