### ISSUE TITLE
Field.invalidate() and validate for field with nested field not blocked form submit

### ISSUE THREAD

**Issue by Desteel** [foxhound87/mobx-ajv-form#519]
Hello. I use structure 
```
mainField
 - nestedAnswerField
 - nestedCommentField
```
And i need validate `mainField`. I set validation for `mainField`, i get `hasError` as `true` and error message, but form can submit and `form.errors` not display that errors.
And if i use `Field.invalidate()`, i also get `hasError` as `true` and error message, but form can submit.

I also tested this with your example from [docs](https://foxhound87.github.io/mobx-react-form/docs/validation/plugins/VJF/extend.html)
```javascript
export function isEmail({ field, validator }) {
  if (validator.isEmail(field.value)) return true;
  return field.invalidate(`The ${field.label} should be an email address.`);
}
```

**Comment by foxhound87** [comment]
can you provide a codesandbox please?

**Comment by Desteel** [comment]
> can you provide a codesandbox please?

[Sandbox](https://codesandbox.io/s/mobx-react-form-issue-519-7vp1m)

Thank you.

**Comment by foxhound87** [comment]
Thank you for reporting this issue.

for now you can use this workaround to make it work until I fix it:

```javascript
const weekValidator = ({ field, form }) => {
  const hasAnswer = Object.keys(field.value).length;

  console.log('week hasAnswer ', hasAnswer);

  if (!hasAnswer) form.invalidate(); // <---

  return [hasAnswer, 'Error message: the week is empty, but form can submit'];
};
```

**Comment by Desteel** [comment]
Thank you!

**Comment by foxhound87** [comment]
@Desteel updated sandbox:
https://codesandbox.io/s/mobx-react-form-issue-519-forked-e29qi9
now should work as expected

Note: `retrieveOnlyEnabledFields` has been renamed to `retrieveOnlyEnabledFieldsValues` in next releases.
