### ISSUE TITLE
isDirty is always true for forms with Nested Fields as Unified Properties

### ISSUE THREAD

**Issue by mdakovac** [foxhound87/mobx-ajv-form#523]
As the title says, if fields are defined something like this:
<pre><code>const fields = [{
    name: 'fieldA',
    label: 'fieldA'
}, {
    name: 'fieldB',
    label: 'fieldB',
    fields: [{
        name: "nestedB",
        label: "nestedB"
    }]
}];
</pre></code>
form is always dirty. 

Repl link with full reproduction:  [link](https://repl.it/@mdakovac/mobx-react-form-nested-fields)

**Comment by foxhound87** [comment]
@riceyeh any idea about this issue?

**Comment by riceyeh** [comment]
I will submit a pull request for solving this problem and others.

**Comment by r1y4h** [comment]
hi @riceyeh 

This is still an issue with Seperated Properties in v2.0.8. isDirty is always true if nested fields of an array has initial values.
