### ISSUE TITLE
How to set field autoFocus?

### ISSUE THREAD

**Issue by sneas** [foxhound87/mobx-ajv-form#524]
Hi, thank you for `mobx-react-form`!

Is it possible to set up `autoFocus` of a particular field to `true` through the field configuration without calling `focus()` method explicitly?

This way obviously isn't working:

```js
const form = new MobxReactForm({
    fields: [
        {
            name: 'firstName',
            label: 'First Name',
            autoFocus: true,
        },
    ],
});

console.log(form.$('firstName').bind().autoFocus); // false
```

**Comment by foxhound87** [comment]
It is not possible because it should eventually unfocus also all other fields recursively if you use `autoFocus: true` for more fields. I don't think it is a good idea to allow focus in this way.

You can use hooks like this:

```javascript
new MobxReactForm({
  fields: [{
    name: 'firstName',
    label: 'First Name',
  }],
}, {
  hooks: {
    onInit(form) {
      form.$('firstName').focus();
    }
  }
});
```

**Comment by foxhound87** [comment]
If it doesn't work yet use `createRef` and  `forwardRef`:
https://codesandbox.io/s/form-focus-d4ttb
