### ISSUE TITLE
focus method doesn't work

### ISSUE THREAD

**Issue by ha3** [foxhound87/mobx-ajv-form#529]
Hello,

I try to focus another input with `field.focus()`  but it doesn't work.

Below, `form.$('password').focus()` doesn't focus to the next CustomInput.

```javascript
<CustomInput
    field={form.$('email')}
    ref={(input) => this.emailInputRef = input}
    returnKeyType='next'
    onSubmitEditing={() => form.$('password').focus()}
    blurOnSubmit={false}
/>

<CustomInput
    field={form.$('password')}
    ref={(input) => this.passwordInputRef= input}
/>
```

```javascript
const CustomInput = observer(React.forwardRef(({ field, ...restProps }, ref) => (
    <Input
        {...field.bind()}
        {...restProps}
        ref={ref}
        onChangeText={field.sync}
        onFocus={field.onFocus}
        onBlur={field.onBlur}
        value={field.value}
    />
));
```

**Comment by foxhound87** [comment]
Maybe you should bind the `autoFocus` prop to your component, or use the `bind()` method with the spread operator which is simpler.

**Comment by ha3** [comment]
Thank you. I couldn't understand the second part of your answer. Could you please elaborate? For the first part, I added `autoFocus` prop to my CustomInput as below but it didn't work:

```javascript
const CustomInput = observer(React.forwardRef(({ field, ...restProps }, ref) => (
    <Input
        {...field.bind()}
        {...restProps}
        ref={ref}
        onChangeText={field.sync}
        onFocus={field.onFocus}
        onBlur={field.onBlur}
        autoFocus={field.focused}
        value={field.value}
    />
));
```

**Comment by foxhound87** [comment]
I mean `autoFocus={field.autoFocus}`,
but it should be already binded if you use `{...field.bind()}`.
I also see that you mixed `{...field.bind()}` with other props that are not required except for `onChangeText` (because you are using react-native).

this should be enough:

```javascript
const CustomInput = observer(React.forwardRef(({ field, ...restProps }, ref) => (
    <Input
        {...field.bind()}
        {...restProps}
        ref={ref}
        onChangeText={field.onChange}
    />
));
```

also, are you sure that `onSubmitEditing` has been executed?

**Comment by ha3** [comment]
I checked with console log and `onSubmitEditing` seems to be executed. But it doesn't focus to the next field and next field's `focused` state doesn't change either.

**Comment by foxhound87** [comment]
Can you provide a codesandbox?

**Comment by ha3** [comment]
Here: https://codesandbox.io/s/react-native-m4jdu

Since a keyboard doesn't show up when a `TextInput` is clicked on codesandbox, `onSubmitEditing` seems untestable. So, I added an extra button for you to test focus method.

**Comment by foxhound87** [comment]
maybe this issue occurs only in react native,
temporarily you can use:

`onSubmitEditing={() => this.passwordInputRef.focus()}`

**Comment by foxhound87** [comment]
I see that occurs also with react (not native)
I created an example in codesandbox
https://codesandbox.io/s/form-focus-d4ttb
