### ISSUE TITLE
on method is undefined

### ISSUE THREAD

**Issue by sebasgavi** [foxhound87/mobx-ajv-form#530]
https://codesandbox.io/s/form-quickstart-m6pvi

(just forked the quickstart sandbox and added `console.log(form.$("email").on);` to prove the on method is undefined)

I don't know if I'm using it wrong, but I can't make it work.

What I need is to set up a onSubmit hook, or something that gets called when the user tries to submit the form. The problem is I need to setup this after the form has been initialized.

**Comment by foxhound87** [comment]
There's no `on` method.

Maybe you need this:
https://foxhound87.github.io/mobx-react-form/docs/events/validation-hooks/override.html
