### ISSUE TITLE
form.init() has a bug

### ISSUE THREAD

**Issue by georgebbbb** [foxhound87/mobx-ajv-form#561]

**Comment by georgebbbb** [comment]
Hi, there, 
```

import { Form } from "../../../../src";

const fields = ["qwerty"];

const values = { qwerty: ["a"] };

class NewForm extends Form {}

const form = new NewForm({ fields }, { name: "Fixes-A" });

form.init(values)

form.$("qwerty").set(["a", "b"]);

export default form;
```

and
![image](https://user-images.githubusercontent.com/3108440/102472775-9938bc80-4091-11eb-8fb8-b4814e35e29a.png)

**Comment by foxhound87** [comment]
please can you make a codesandbox with this issue?

**Comment by foxhound87** [comment]
Yes, the `init()` method have still some issues.
Actually, you should pass the `values` on the form constructor and use the `update()` method to change fields values after the form has been initialized.

**Comment by foxhound87** [comment]
I see that this issue happen only if the field initial value has an array of only one item.

**Comment by foxhound87** [comment]
I think I'm going to deprecate init method in next releases

**Comment by foxhound87** [comment]
the `init()` method has been deprecated in the next version
