### ISSUE TITLE
[MobX] Cannot apply '@observable' to 'Form.prototype.$submitting':

### ISSUE THREAD

**Issue by zif002** [foxhound87/mobx-ajv-form#569]
Hi, I have updated mobx to version 6 and updated the mobx-react-form plugin to version 3.0.0 for the latest version, but I got an error, which can be related to the example code below. thanks for the help
https://codesandbox.io/s/form-quickstart-forked-lmlud?file=/index.js

**Comment by vkrol** [comment]
@zif002 FYI https://github.com/foxhound87/mobx-react-form/pull/566

**Comment by zcaceres** [comment]
This is a big problem for those of us who are trying to upgrade.

**Comment by exinferis** [comment]
I agree - this is a real showstopper and would be much appreciated to be merged soon.
