### ISSUE TITLE
No longer able to use components in form config (labels, placeholders, ...)

### ISSUE THREAD

**Issue by evstinik** [foxhound87/mobx-ajv-form#572]
Hi, latest version of mobx-react-form (3.1) and mobx (6.1) seems to be failing on common use case which was working on previous version we were using (mobx 5.15, mobx-react-form 1.39).

Code sandbox with reproduced problem: https://codesandbox.io/s/form-quickstart-forked-qhokp?file=/form.js

When I specify component instead of plain string as a value for label or placeholder it's failing with different errors:
- _Cannot read property 'propTypes' of undefined_ for FormattedMessage from react-intl
- _Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports._ for custom components

**Comment by foxhound87** [comment]
You should not pass component as label, it should be a string.
The other errors are not related to the library.

**Comment by evstinik** [comment]
Ok, thanks
