### ISSUE TITLE
using form properties in computed props

### ISSUE THREAD

**Issue by mogadanez** [foxhound87/mobx-ajv-form#574]
https://codesandbox.io/s/form-quickstart-forked-5qm1s

trying to use  form props in computed props, but value is not refreshed.

```
get sumbitingOrValidating() {
    return this.form.submitting || this.form.validating;
  }
```

**Comment by foxhound87** [comment]
you have to 

`import { observer } from "mobx-react";`

and use it on your component

https://codesandbox.io/s/form-quickstart-forked-vxfdu9
