### ISSUE TITLE
lodash-cherry-pick

### ISSUE THREAD

**Issue by vkrol** [foxhound87/mobx-ajv-form#58]
Hello!

We want to use mobx-react-form in our application, but we cannot because we use the old lodash version (3.x) globally on the whole site, so sooner or later we can clash with the some lodash breaking changes (3.x vs 4.x). I think that peer dependency on the lodash is very bad. Probably you need to drop the lodash dependency or include it in the library bundle (drop it from the webpack.config.babel.js/externals section).

Probably the best solution will be cherry picking individual lodash functions, for example:
`import intersection from "lodash/intersection"`
Also you can use this plugin https://github.com/lodash/babel-plugin-lodash.

I can help with the pull request if you approve.

**Comment by foxhound87** [comment]
Now I'm using webpack only for the UMD build (which is not working for an issue with decorators and I have to figure it out) and I suppose that if we want to cherry pick lodash functions with minimal efforts we need to setup webpack for the commonjs build. 

I wonder if using babel-plugin-lodash and lodash-webpack-plugin together we do not have to touch the code, because otherwise we should also edit the next version of the package that I'm writing which uses more lodash: https://github.com/foxhound87/mobx-react-form/tree/nested-fields.

what's your advice?
Thank you for your help

**Comment by foxhound87** [comment]
@vkrol we should create a `lodash-cherry-pick` branch to merge it also into the `nested-fields` branch afterward.

**Comment by vkrol** [comment]
Thanks, I'll think about it.

Also I think that you need to relax the lodash version constraint to the ^4.16.2. What you think about it?

**Comment by foxhound87** [comment]
It's ok for me. 

Greenkeeper should check each release through CI builds.

**Comment by vkrol** [comment]
Thanks, I will create the pull request. What you think about relaxing mobx version constraint too?

**Comment by foxhound87** [comment]
Let's do it.

**Comment by vkrol** [comment]
> I wonder if using babel-plugin-lodash and lodash-webpack-plugin together

I do not want to use lodash-webpack-plugin for now because it is "destructive" by default and we will have to decide what the feature sets (https://github.com/lodash/lodash-webpack-plugin#feature-sets) we should to enable. 

I can add the babel-plugin-lodash to the .babelrc. What do you think about it?

**Comment by foxhound87** [comment]
We can add it for sure, this should lighten the commonjs build.

Anyway I suppose that your issue with the older lodash version should occur only using the UMD build. 

If you use commonjs instead, the version of the package's dependencies should remain the version specified in the package.json despite you are using an older one in your project.

Tell me if I'm wrong.

**Comment by vkrol** [comment]
> We can add it for sure, this should lighten the commonjs build.

Thanks. I will create the PR tomorrow. 

> Anyway I suppose that your issue with the older lodash version should occur only using the UMD build.
> 
> If you use commonjs instead, the version of the package's dependencies should remain the version specified in the package.json despite you are using an older one in your project.
> 
> Tell me if I'm wrong.

Yes, you are right. I am sorry for the confusion. But the cherry picking is the good thing anyway :)

**Comment by vkrol** [comment]
If I add the babel-plugin-lodash to the .babelrc then this line of code https://github.com/foxhound87/mobx-react-form/blob/master/webpack.config.babel.js#L29 become useless and imported lodash methods will be included in the umd build. Is this the desired result?

**Comment by foxhound87** [comment]
Yes it is.

**Comment by vkrol** [comment]
> we should create a lodash-cherry-pick branch to merge it also into the nested-fields branch afterward.

@foxhound87 do I need to create the PR to the nested-fields branch or you do it yourself?

**Comment by foxhound87** [comment]
I will do it. I need to fix some lodash code first.

Thank you
