### ISSUE TITLE
Input with type="number" and field rules "required|numeric" is not validating for a specific type of numbers

### ISSUE THREAD

**Issue by lexprom** [foxhound87/mobx-ajv-form#596]
I've faced a problem where a field is not valid if the value of it is something like this: `+32.45` - decimal with a positive sign
I thought the problem was in the `validatorjs` but it's validating these cases.

Test cases:
1. "+32" -> `true`
2. "32.45" -> `true`
3. "-32.45" -> `true`
4. "+32.45" -> `false`

I've created a [sandbox](https://codesandbox.io/s/determined-bash-3ppli) with a form and a [sandbox](https://codesandbox.io/s/elastic-sun-1l2vy) with only `validatorjs`.

**Comment by foxhound87** [comment]
it seems something related to the type `number` on the input.
By removing `type` from `bind` it gets validated.

**Comment by lexprom** [comment]
@foxhound87 you mean by removing this part `field.bind({ type <--, placeholder })` ?
If so,  that's exactly the reason the input gets `text` type and it's not reproducing

**Comment by lexprom** [comment]
The problem is still there though 👀  
Or is it expected behavior?

**Comment by foxhound87** [comment]
I see that plain input with type number and value "+32.45" as string is not working

```
    <input type="number" value="+32.45" />
```

**Comment by lexprom** [comment]
It's not even working with the value "+32"  for some reason
