### ISSUE TITLE
Add https://greenkeeper.io/

### ISSUE THREAD

**Issue by patrykkopycinski** [foxhound87/mobx-ajv-form#6]
To keep dependencies up to date, i suggest using https://greenkeeper.io/ it'll limit manual work :)

**Comment by foxhound87** [comment]
Hi @patrykkopycinski 

I usually use npm-check-updates, 
but thank you for your suggestion,
I will take a look at greenkeeper too!

**Comment by foxhound87** [comment]
@patrykkopycinski  greenkeeper added!
