### ISSUE TITLE
cannot change disabled prop on fields

### ISSUE THREAD

**Issue by danseedo** [foxhound87/mobx-ajv-form#609]
When attempting to set the `disabled` prop on a field, `form.$('some_field').set('disabled', true)`, I get an error, `The selected property is not allowed (["disabled"])`. Is dynamically disabling a field not supported?

**Comment by foxhound87** [comment]
Are you using the next version? It should work but I think I made a mistake when refactoring because there is no test for the case. I will fix it asap and provide a test case.

**Comment by danseedo** [comment]
Yes, this was for version 5.3.0. It works fine in 3.2.0.
