### ISSUE TITLE
Get an array of fields when submitting a form

### ISSUE THREAD

**Issue by mistek131995** [foxhound87/mobx-ajv-form#627]
Hi, my form looks like this. How can I get the fields in array format when submitting the form?

![Снимок экрана (200)](https://github.com/foxhound87/mobx-react-form/assets/14914380/c584313f-b9f7-4479-9ee1-3b329468d0a0)

**Comment by foxhound87** [comment]
I think you need `form.values()` which can access all form values, 
for example, using it in an [event hook](https://foxhound87.github.io/mobx-react-form/docs/events/event-hooks.html)

If you need more support, post your form configuration or join us on [discord channel](https://discord.com/invite/CVV8w4zat4)
