### ISSUE TITLE
Incorrect initialization of fields with zero value

### ISSUE THREAD

**Issue by artptr** [foxhound87/mobx-ajv-form#68]
If a form is created by separated `fields` and `values` objects and a value is `0` then a corresponding field will be initialized with `""`:

``` javascript
const MobxReactForm = require("mobx-react-form");

const form = new MobxReactForm({
    fields: ["qwerty"],
    values: { qwerty: 0 },
});

console.log(form.fields.qwerty.value); // ""
```

The cause of the bug is incorrect calculating of an initial value here: https://github.com/foxhound87/mobx-react-form/blob/master/src/Field.js#L60
While `$value = 0` and `$field = ""` the result will be `""` despite the logical priority of `$value`'s value.

**Comment by foxhound87** [comment]
@artptr thank you, I will fix it asap.
