### ISSUE TITLE
validateOnChange option after form instance was created isn't working.

### ISSUE THREAD

**Issue by volodymyr-xn** [foxhound87/mobx-ajv-form#74]
Hi. I have the following issue: 
Changing validateOnChange option isn't change form validation behavior, if we change it after first form initialization, because this method:

``` javascript
observeFields() {
    if (this.$options.validateOnChange === false) return;
    // observe and validate each field
    _.each(this.fields, (field, key) =>
      observe(this.fields[key], '$value', () =>
        this.validate({ key, showErrors: true, recursive: true })));
  }
```

that responsible on onChange validation, is called only during form initialization processes.
If form was initialized with `validateOnChange` set to false, later updates to `true` - won't change field validation mechanism. 

And i have two ideas to resolve this issue:

1)
We can change `observeFields` method to the following: 

``` javascript
 observeFields() {
    // observe and validate each field
    _.each(this.fields, (field, key) =>
      observe(this.fields[key], '$value', () => {
        if (this.$options.validateOnChange === false) return;
        this.validate({ key, showErrors: true, recursive: true });
      }));
  }
```

And that will remove the issue. I can create pull request with this fix. 

2)
On the other hand, we can call `observeFields` method each time when `options` method is invoked. But in this case, we have to enable or disable `this.fields` observing accordingly to `this.$options.validateOnChange`.

**Comment by foxhound87** [comment]
Hi @volodymyr-shevchuk 
You are right.

mobx `observe()` returns a `disposer`. It will cancel every future updates until we call the `observe()` another time. A better solution would be to observe the form `$options` and observe/dispose when `validateOnChange` changes: http://mobxjs.github.io/mobx/refguide/observe.html

Feel free to implement which you want if you want to contribute with a pull requrest.
Anyway I will implement observe/dispose for the next version (nested-fields).

Thanks!

**Comment by foxhound87** [comment]
@volodymyr-shevchuk  After thinking about this issue on the `nested-field` branch, it turned out that I should keep track of the disposer for each field or nested field, which is too elaborate. Your simpler approach is what I'm going to implement :)
