### ISSUE TITLE
it can't work I just new a instance ?

### ISSUE THREAD

**Issue by yoohan-dex** [foxhound87/mobx-ajv-form#83]
``` javascript
const plugins = { dvr: validatorjs };

const fields = {
  email: {
    labal: 'Email',
    rules: 'required|email|string|between:5,25',
  },
  password: {
    label: 'Password',
    rules: 'required|string|between:5,25',
  },
};
```

``` javascript
class LoginForm extends MobxReactForm {

  onSuccess(form) {
    console.log('Form Values!', form.value());
  }

  onError(form) {
    console.log('All form errors', form.errors());
    form.invalidate('This is a generic error message!');
  }
}

export default new LoginForm({ fields, plugins });
```

that 's all the code and it can't work even though I just refer without passing the instance to my component .

and logs : 
`Uncaught Error: [mobx] Invariant failed: It is not allowed to create or change state outside an "action" when MobX is in strict mode. Wrap the current method in`action`if this state change is intended`

**Comment by yoohan-dex** [comment]
Oh I see that just I used the mobx without strict mode before .. so .. when it turns to strict my other states can't be directly changed.

**Comment by foxhound87** [comment]
you have to use mobx `action` to change the state.

Anyway you are mispelling `label` (not `labal`) and `form.values()` (not `form.value()`)
and maybe you are referencing an undefined field into the react component.

I can help you more If you can provide a jsfiddle.

**Comment by foxhound87** [comment]
I consider this issue closed for now because the error seems not related to the package but to your app state which was not using mobx strict mode.

**Comment by yoohan-dex** [comment]
Right, I have fixed it a few days, thank everyone 😊😊

Sent from my Samsung Galaxy smartphone.

-------- Original message --------
