### ISSUE TITLE
react in the package name is misleading

### ISSUE THREAD

**Issue by vkrol** [foxhound87/mobx-ajv-form#85]
Hello. I think that the word "react" in the package name is misleading. In theory mobx-react-form can be used with any UI library/framework.

What do you think about it?

**Comment by foxhound87** [comment]
We can work on this, I didn't tested the package outside a react project yet.
And we need to think to a proper name too.

**Comment by vkrol** [comment]
Sadly that mobx-form and mobx-forms already taken.

**Comment by anotherpit** [comment]
@foxhound87, actually you did: your tests have nothing to do with react. I'd suggest `mobx-form-state` name (and `FormState` or `MobxFormState` for the class). 

Pros:
- it doesn't mention react;
- it does perfectly describe the purpose of the lib;
- it eliminates naming ambiguity for form state classes and form component classes (e.g. `LoginFormState` and `LoginForm`).

Cons: backward incompatibility and need to publish new major version.

What do you think?

**Comment by foxhound87** [comment]
@anotherpit thank you for your suggestions!

I have to think about it a little more before because I already renamed it from `mobx-ajv-form` which is still downloaded... :|

**Comment by foxhound87** [comment]
Let's see what other people think and suggest :)

**Comment by anotherpit** [comment]
Well, I doubt as well. So, yeah, it'd be cool to discuss it here a bit.

**Comment by anotherpit** [comment]
BTW, thanks for the lib. Simply brilliant one!

**Comment by foxhound87** [comment]
Thank you :) I appreciate so much. 

But I have to thank you all for the support and contribution to make it even better!
The feedback from the community is very important for me.

I was thinking if we can still use this package name for some React specific improvements - like the devtools or form HOC wrappers for better integration, etc... - importing here the "core" from the future `mobx-form-xxx` package.

**Comment by msaron** [comment]
After trying to implement redux-form in my use case and getting frustrated I went searching for another library and googled for 'react form'.  If react was not in the name, I would never have found it. This is a great library and far better than redux-form. It is a pleasure to use. Thanks for all your effort. I am still reviewing your rfx library to see if I want to use feathers.

**Comment by foxhound87** [comment]
And in future would be cool to separate the validation functionalities in a different package, so we can have something like `mobx-form-state` and `mobx-form-validation` (with separated tests too).

**Comment by vkrol** [comment]
I don't think there's any point in fixing that anymore.
