### ISSUE TITLE
Feature request: touched state

### ISSUE THREAD

**Issue by vkrol** [foxhound87/mobx-ajv-form#86]
Hello. I think that the ability to track the touched state of the field will be very useful.

**Comment by foxhound87** [comment]
I will implement it asap!

**Comment by vkrol** [comment]
Thanks!

**Comment by foxhound87** [comment]
https://foxhound87.github.io/mobx-react-form/docs/events/events-handlers.html

**Comment by vkrol** [comment]
@foxhound87 thanks!
