### ISSUE TITLE
Handling of isDirty

### ISSUE THREAD

**Issue by kyasu1** [foxhound87/mobx-ajv-form#9]
I think that checking $value against originalValue is more intuitive.
the redux-form doing like this.
https://github.com/erikras/redux-form/blob/master/src/isPristine.js

**Comment by foxhound87** [comment]
I was wondering if a field should be dirty though the initial value is not empty (so even if equal to the initial value if exist). But I will fix it if that is considered a best approach.

I will introduce `isPristine` and `isEmpty` too.

**Comment by foxhound87** [comment]
https://github.com/foxhound87/mobx-ajv-form/commit/75649099611af4ae7fe4fd0c5fd4d8ccea648820

**Comment by kyasu1** [comment]
Thanks, looks better than before. However there is an issue when the field type is integer. Since you are directly setting the received form value to the `Fields.$value`, the initially integer type field becomes the string type, which breaks the pristine/dirty checks.

I think, in the `Field.setValue`, you need to parse and assign as Number if the type of schema is ‘integer’. ~~Probably similar handling is necessary for Array and Object fields.~~

**Comment by foxhound87** [comment]
Thanks for your suggestions, I will fix it asap.
I will implement support for more input types in the future, with updated tests and demo.

**Comment by foxhound87** [comment]
https://github.com/foxhound87/mobx-ajv-form/commit/27b70fe7e87848f7f1afbc6c1bad7cace765bc08
