### ISSUE TITLE
Multiple forms using the same fields

### ISSUE THREAD

**Issue by JZiebikiewicz** [foxhound87/mobx-ajv-form#91]
Hi, I'm creating import component with table of records, like:
![image](https://cloud.githubusercontent.com/assets/16606706/19479165/ca64b13e-9545-11e6-8202-5373e20d85e3.png)
How can I initialize form validation for each row using the same fields? Tried creating array containing Form instances. But it doesn't work (rows values change in the same time).

``` javascript
@observable recordsValidation = [];
recordsValidation.push( new Form({ plugins,  fields });
recordsValidation.push( new Form({ plugins,  fields });
```

**Comment by foxhound87** [comment]
You should define a `rules` (DVR) or `validate` (VJF) object and pass it to each of your forms.

Look here: https://foxhound87.github.io/mobx-react-form/docs/defining-flat-fields/separated-properties.html#define-separated-validation-objects

**Comment by foxhound87** [comment]
You can even initialize just the structure with empty fields providing a `fields` array to the constructor, like this:

``` javascript
const fields = ['id', 'title', 'company', 'type'];
```

and set fields values afterward using the `update()` method;

**Comment by JZiebikiewicz** [comment]
**Thanks for reply. I'll try and tell you if it works for me. :)**

So far my `plugins` variable was:

``` javascript
const plugins = {
  dvr: {
    package: validatorjs,
    extend: dvrExtend,
  },
};
```

and `fields`:

``` javascript
const fields = {
  id: {
    label: 'ID',
    value: '',
    rules: 'string|required',
  },
  title: {
    label: 'Title',
    value: '',
    rules: 'string|min:10|required',
  },
  company: {
    label: 'Company',
    value: '',
    rules: 'string',
  },
  type: {
    label: 'Type',
    value: '',
    rules: 'string',
  },
}
```

And then I created form instances:

``` javascript
@observable recordsValidation = [];
recordsValidation.push( new Form({ plugins,  fields });
recordsValidation.push( new Form({ plugins,  fields });
```

And passed to component like:

```
<Row form={ this.recordsValidation[0] } />
<Row form={ this.recordsValidation[1] } />
```

Weirdly values were 'connected' (when changing 1st row title, second ones changes too).

**Comment by foxhound87** [comment]
`recordsValidation.push` is missing an ending bracket.

You can try to give a unique name for each form and print them,
so we can ensure the forms has different instances:

``` javascript
recordsValidation.push(new Form({ plugins,  fields }, 'Form-A'));
recordsValidation.push(new Form({ plugins,  fields }, 'Form-B'));
```

and log: `this.recordsValidation[0].name`

I hope this can help.

**Comment by JZiebikiewicz** [comment]
It works nice. Even without giving names to each form. Thank you for support. :) 

I just had to update package from 1.11.12 to the newest 1.13.3...
