### ISSUE TITLE
Git Repo for mobx-react-form-demo<eom>

### ISSUE THREAD

**Issue by Kamaraju333** [foxhound87/mobx-ajv-form#94]

**Comment by foxhound87** [comment]
Why should I setup a demo repo?
And what "eom" means?

**Comment by Kamaraju333** [comment]
Demo was looking great so thought of asking (eom means end of message )

**Comment by foxhound87** [comment]
I don't want to separate the demo directory into a new repo because I use it to test the code directly from the source without build it or publish it on npm... unless there is a better way to do it.

**Comment by foxhound87** [comment]
For now I opted for a new branch with symlinks.

**Comment by foxhound87** [comment]
@Kamaraju333  FYI 

I created the [dedicated demo repo](https://github.com/foxhound87/mobx-react-form-demo), and It's updated with custom components.
